### ISSUE TITLE
permissionerror

### ISSUE THREAD

**Issue by colsona** [Megvii-BaseDetection/YOLOX#10]
> `Traceback (most recent call last):
  File "tools/demo.py", line 277, in <module>
    main(exp, args)
  File "tools/demo.py", line 210, in main
    os.makedirs(file_name, exist_ok=True)
  File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
`
Has anyone meet this issue?

**Comment by colsona** [comment]
> > `Traceback (most recent call last):   File "tools/demo.py", line 277, in <module>     main(exp, args)   File "tools/demo.py", line 210, in main     os.makedirs(file_name, exist_ok=True)   File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 213, in makedirs     makedirs(head, exist_ok=exist_ok)   File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 213, in makedirs     makedirs(head, exist_ok=exist_ok)   File "/home/lengyihong/anaconda3/lib/python3.8/os.py", line 223, in makedirs     mkdir(name, mode) PermissionError: [Errno 13] Permission denied: '/data' `
> > Has anyone meet this issue?

Something wrong in yolox/exp/base_exp.py. 
' self.output_dir = "./data/YOLOX_outputs"'
