### ISSUE TITLE
error in training, torch version 1.10

### ISSUE THREAD

**Issue by Enterprise-cv6** [Megvii-BaseDetection/YOLOX#1015]
The following errors occurred when I used yolox training

2021-12-22 16:31:05 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (18708), thread 'MainThread' (23316):
Traceback (most recent call last):

  File "tools\train.py", line 130, in <module>
    launch(
    └ <function launch at 0x0000014055C18820>

> File "E:\code\pytorch-yolox-windows-main\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000014059758040>

  File "tools\train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x00000140570E9550>
    └ <yolox.core.trainer.Trainer object at 0x000001405975DB80>

  File "E:\code\pytorch-yolox-windows-main\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001405970CCA0>
    └ <yolox.core.trainer.Trainer object at 0x000001405975DB80>

  File "E:\code\pytorch-yolox-windows-main\yolox\core\trainer.py", line 133, in before_train
    "Model Summary: {}".format(get_model_info(model, self.exp.test_size))
                               │              │      │    │   └ (640, 640)
                               │              │      │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                               │              │      └ <yolox.core.trainer.Trainer object at 0x000001405975DB80>
                               │              └ YOLOX(
                               │                  (backbone): YOLOPAFPN(
                               │                    (backbone): CSPDarknet(
                               │                      (stem): Focus(
                               │                        (conv): BaseConv(
                               │                          (conv): ...
                               └ <function get_model_info at 0x0000014055A39040>

  File "E:\code\pytorch-yolox-windows-main\yolox\utils\model_utils.py", line 23, in get_model_info
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
                    │       │        │               └ tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
                    │       │        │                           [0., 0., 0.,  ..., 0., 0., 0.],
                    │       │        │                           [0., 0., 0.,  ..., 0., 0., 0.],...
                    │       │        └ YOLOX(
                    │       │            (backbone): YOLOPAFPN(
                    │       │              (backbone): CSPDarknet(
                    │       │                (stem): Focus(
                    │       │                  (conv): BaseConv(
                    │       │                    (conv): ...
                    │       └ <function deepcopy at 0x000001404E748CA0>
                    └ <function profile at 0x0000014055A4CE50>

  File "D:\anaconda\envs\cuda102py38\lib\site-packages\thop-0.0.5.post2112212159-py3.8.egg\thop\profile.py", line 211, in profile

  File "D:\anaconda\envs\cuda102py38\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           │                         [0., 0., 0.,  ..., 0., 0., 0.],
           │                         [0., 0., 0.,  ..., 0., 0., 0.]...
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "E:\code\pytorch-yolox-windows-main\yolox\models\yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
               │             └ tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
               │                         [0., 0., 0.,  ..., 0., 0., 0.],
               │                         [0., 0., 0.,  ..., 0., 0., 0.],...
               └ YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                         (conv): BaseConv(
                           (conv): ...

  File "D:\anaconda\envs\cuda102py38\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           │                         [0., 0., 0.,  ..., 0., 0., 0.],
           │                         [0., 0., 0.,  ..., 0., 0., 0.]...
           └ <bound method YOLOPAFPN.forward of YOLOPAFPN(
               (backbone): CSPDarknet(
                 (stem): Focus(
                   (conv): BaseConv(
                     (c...

  File "E:\code\pytorch-yolox-windows-main\yolox\models\yolo_pafpn.py", line 99, in forward
    f_out0 = torch.cat([f_out0, x1], 1)  # 512->1024/16
             │     │    │       └ tensor([[[[0., 0., 0., 0.],
             │     │    │                   [0., 0., 0., 0.],
             │     │    │                   [0., 0., 0., 0.],
             │     │    │                   [0., 0., 0., 0.]],
             │     │    │         
             │     │    │                  [[...
             │     │    └ tensor([0.], dtype=torch.float64)
             │     └ <built-in method cat of type object at 0x00007FF8372B3590>
             └ <module 'torch' from 'D:\\anaconda\\envs\\cuda102py38\\lib\\site-packages\\torch\\__init__.py'>

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by FateScript** [comment]
I tried on torch 1.10.1 and I could not reproduce your error.

**Comment by Cofea** [comment]
Hello~ I have the same confusion, could you please solve it?

**Comment by Cofea** [comment]
> Hello~ I have the same confusion, could you please solve it?

 ..maybe it's because my GPU doesn't support it

**Comment by 1311523821** [comment]
Hello, I have the same problem. I want to ask, how did you solve it.

**Comment by 1311523821** [comment]
> Hello~ I have the same confusion, could you please solve it?

Hello, I also have the same problem. how did you solve it？

**Comment by Cofea** [comment]
> Hello, I have the same problem. I want to ask, how did you solve it.

hi,I ended up switching to a new GPU.

**Comment by xmayyy** [comment]
> > Hello~ I have the same confusion, could you please solve it?
> 
> Hello, I also have the same problem. how did you solve it？

 Hello, I also have the same problem. how did you solve it？
