### ISSUE TITLE
export_onnx.py + Custom Yolox Tiny -> Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by wawaderwaran** [Megvii-BaseDetection/YOLOX#1055]
Hi,

When trying to convert a custom Yolox Tiny to ONNX, the following error turns up.

Experiment config is:
```python
class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()

        self.data_dir = "datasets/COCO"

        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.num_classes = 1

        self.max_epoch = 275
        self.data_num_workers = 4
        self.eval_interval = 1

        self.depth = 0.33
        self.width = 0.375
        self.input_scale = (416, 416)
        self.mosaic_scale = (0.5, 1.5)
        self.random_size = (10, 20)
        self.test_size = (416, 416)
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]
        self.enable_mixup = False
```

```
python3 tools/export_onnx.py --output-name yolox_tiny.onnx --opset 10 -n yolox_tiny_cyclist -c yolox_tiny.pth -f exps/example/custom/yolox_tiny_cyclist.py
2022-01-06 12:22:00.520 | INFO     | __main__:main:59 - args value: Namespace(batch_size=1, ckpt='yolox_tiny.pth', dynamic=False, exp_file='exps/example/custom/yolox_tiny_cyclist.py', experiment_name=None, input='images', name='yolox_tiny_cyclist', no_onnxsim=False, opset=10, opts=[], output='output', output_name='yolox_tiny.onnx')
2022-01-06 12:22:00.907 | ERROR    | __main__:<module>:116 - An error has been caught in function '<module>', process 'MainProcess' (378), thread 'MainThread' (140533757298496):
Traceback (most recent call last):

> File "tools/export_onnx.py", line 116, in <module>
    main()
    └ <function main at 0x7fd0141fc8b0>

  File "tools/export_onnx.py", line 79, in main
    model.load_state_dict(ckpt)
    │     │               └ OrderedDict([('backbone.backbone.stem.conv.conv.weight', tensor([[[[ 1.8677e-02, -2.3245e-02,  6.6867e-02],
    │     │                           [-1.804...
    │     └ <function Module.load_state_dict at 0x7fd01d094f70>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

RuntimeError: Error(s) in loading state_dict for YOLOX:
        Unexpected key(s) in state_dict: "backbone.backbone.dark2.1.m.1.conv1.conv.weight", "backbone.backbone.dark2.1.m.1.conv1.bn.weight", "backbone.backbone.dark2.1.m.1.conv1.bn.bias", "backbone.backbone.dark2.1.m.1.conv1.bn.running_mean", "backbone.backbone.dark2.1.m.1.conv1.bn.running_var", "backbone.backbone.dark2.1.m.1.conv1.bn.num_batches_tracked", "backbone.backbone.dark2.1.m.1.conv2.conv.weight", "backbone.backbone.dark2.1.m.1.conv2.bn.weight", "backbone.backbone.dark2.1.m.1.conv2.bn.bias", "backbone.backbone.dark2.1.m.1.conv2.bn.running_mean", "backbone.backbone.dark2.1.m.1.conv2.bn.running_var", "backbone.backbone.dark2.1.m.1.conv2.bn.num_batches_tracked", "backbone.backbone.dark2.1.m.2.conv1.conv.weight", "backbone.backbone.dark2.1.m.2.conv1.bn.weight", "backbone.backbone.dark2.1.m.2.conv1.bn.bias", "backbone.backbone.dark2.1.m.2.conv1.bn.running_mean", "backbone.backbone.dark2.1.m.2.conv1.bn.running_var", "backbone.backbone.dark2.1.m.2.conv1.bn.num_batches_tracked", "backbone.backbone.dark2.1.m.2.conv2.conv.weight", "backbone.backbone.dark2.1.m.2.conv2.bn.weight", "backbone.backbone.dark2.1.m.2.conv2.bn.bias", "backbone.backbone.dark2.1.m.2.conv2.bn.running_mean", "backbone.backbone.dark2.1.m.2.conv2.bn.running_var", "backbone.backbone.dark2.1.m.2.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.3.conv1.conv.weight", "backbone.backbone.dark3.1.m.3.conv1.bn.weight", "backbone.backbone.dark3.1.m.3.conv1.bn.bias", "backbone.backbone.dark3.1.m.3.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.3.conv1.bn.running_var", "backbone.backbone.dark3.1.m.3.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.3.conv2.conv.weight", "backbone.backbone.dark3.1.m.3.conv2.bn.weight", "backbone.backbone.dark3.1.m.3.conv2.bn.bias", "backbone.backbone.dark3.1.m.3.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.3.conv2.bn.running_var", "backbone.backbone.dark3.1.m.3.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.4.conv1.conv.weight", "backbone.backbone.dark3.1.m.4.conv1.bn.weight", "backbone.backbone.dark3.1.m.4.conv1.bn.bias", "backbone.backbone.dark3.1.m.4.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.4.conv1.bn.running_var", "backbone.backbone.dark3.1.m.4.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.4.conv2.conv.weight", "backbone.backbone.dark3.1.m.4.conv2.bn.weight", "backbone.backbone.dark3.1.m.4.conv2.bn.bias", "backbone.backbone.dark3.1.m.4.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.4.conv2.bn.running_var", "backbone.backbone.dark3.1.m.4.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.5.conv1.conv.weight", "backbone.backbone.dark3.1.m.5.conv1.bn.weight", "backbone.backbone.dark3.1.m.5.conv1.bn.bias", "backbone.backbone.dark3.1.m.5.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.5.conv1.bn.running_var", "backbone.backbone.dark3.1.m.5.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.5.conv2.conv.weight", "backbone.backbone.dark3.1.m.5.conv2.bn.weight", "backbone.backbone.dark3.1.m.5.conv2.bn.bias", "backbone.backbone.dark3.1.m.5.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.5.conv2.bn.running_var", "backbone.backbone.dark3.1.m.5.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.6.conv1.conv.weight", "backbone.backbone.dark3.1.m.6.conv1.bn.weight", "backbone.backbone.dark3.1.m.6.conv1.bn.bias", "backbone.backbone.dark3.1.m.6.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.6.conv1.bn.running_var", "backbone.backbone.dark3.1.m.6.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.6.conv2.conv.weight", "backbone.backbone.dark3.1.m.6.conv2.bn.weight", "backbone.backbone.dark3.1.m.6.conv2.bn.bias", "backbone.backbone.dark3.1.m.6.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.6.conv2.bn.running_var", "backbone.backbone.dark3.1.m.6.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.7.conv1.conv.weight", "backbone.backbone.dark3.1.m.7.conv1.bn.weight", "backbone.backbone.dark3.1.m.7.conv1.bn.bias", "backbone.backbone.dark3.1.m.7.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.7.conv1.bn.running_var", "backbone.backbone.dark3.1.m.7.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.7.conv2.conv.weight", "backbone.backbone.dark3.1.m.7.conv2.bn.weight", "backbone.backbone.dark3.1.m.7.conv2.bn.bias", "backbone.backbone.dark3.1.m.7.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.7.conv2.bn.running_var", "backbone.backbone.dark3.1.m.7.conv2.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.8.conv1.conv.weight", "backbone.backbone.dark3.1.m.8.conv1.bn.weight", "backbone.backbone.dark3.1.m.8.conv1.bn.bias", "backbone.backbone.dark3.1.m.8.conv1.bn.running_mean", "backbone.backbone.dark3.1.m.8.conv1.bn.running_var", "backbone.backbone.dark3.1.m.8.conv1.bn.num_batches_tracked", "backbone.backbone.dark3.1.m.8.conv2.conv.weight", "backbone.backbone.dark3.1.m.8.conv2.bn.weight", "backbone.backbone.dark3.1.m.8.conv2.bn.bias", "backbone.backbone.dark3.1.m.8.conv2.bn.running_mean", "backbone.backbone.dark3.1.m.8.conv2.bn.running_var", "backbone.backbone.dark3.1.m.8.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.3.conv1.conv.weight", "backbone.backbone.dark4.1.m.3.conv1.bn.weight", "backbone.backbone.dark4.1.m.3.conv1.bn.bias", "backbone.backbone.dark4.1.m.3.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.3.conv1.bn.running_var", "backbone.backbone.dark4.1.m.3.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.3.conv2.conv.weight", "backbone.backbone.dark4.1.m.3.conv2.bn.weight", "backbone.backbone.dark4.1.m.3.conv2.bn.bias", "backbone.backbone.dark4.1.m.3.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.3.conv2.bn.running_var", "backbone.backbone.dark4.1.m.3.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.4.conv1.conv.weight", "backbone.backbone.dark4.1.m.4.conv1.bn.weight", "backbone.backbone.dark4.1.m.4.conv1.bn.bias", "backbone.backbone.dark4.1.m.4.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.4.conv1.bn.running_var", "backbone.backbone.dark4.1.m.4.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.4.conv2.conv.weight", "backbone.backbone.dark4.1.m.4.conv2.bn.weight", "backbone.backbone.dark4.1.m.4.conv2.bn.bias", "backbone.backbone.dark4.1.m.4.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.4.conv2.bn.running_var", "backbone.backbone.dark4.1.m.4.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.5.conv1.conv.weight", "backbone.backbone.dark4.1.m.5.conv1.bn.weight", "backbone.backbone.dark4.1.m.5.conv1.bn.bias", "backbone.backbone.dark4.1.m.5.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.5.conv1.bn.running_var", "backbone.backbone.dark4.1.m.5.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.5.conv2.conv.weight", "backbone.backbone.dark4.1.m.5.conv2.bn.weight", "backbone.backbone.dark4.1.m.5.conv2.bn.bias", "backbone.backbone.dark4.1.m.5.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.5.conv2.bn.running_var", "backbone.backbone.dark4.1.m.5.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.6.conv1.conv.weight", "backbone.backbone.dark4.1.m.6.conv1.bn.weight", "backbone.backbone.dark4.1.m.6.conv1.bn.bias", "backbone.backbone.dark4.1.m.6.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.6.conv1.bn.running_var", "backbone.backbone.dark4.1.m.6.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.6.conv2.conv.weight", "backbone.backbone.dark4.1.m.6.conv2.bn.weight", "backbone.backbone.dark4.1.m.6.conv2.bn.bias", "backbone.backbone.dark4.1.m.6.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.6.conv2.bn.running_var", "backbone.backbone.dark4.1.m.6.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.7.conv1.conv.weight", "backbone.backbone.dark4.1.m.7.conv1.bn.weight", "backbone.backbone.dark4.1.m.7.conv1.bn.bias", "backbone.backbone.dark4.1.m.7.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.7.conv1.bn.running_var", "backbone.backbone.dark4.1.m.7.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.7.conv2.conv.weight", "backbone.backbone.dark4.1.m.7.conv2.bn.weight", "backbone.backbone.dark4.1.m.7.conv2.bn.bias", "backbone.backbone.dark4.1.m.7.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.7.conv2.bn.running_var", "backbone.backbone.dark4.1.m.7.conv2.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.8.conv1.conv.weight", "backbone.backbone.dark4.1.m.8.conv1.bn.weight", "backbone.backbone.dark4.1.m.8.conv1.bn.bias", "backbone.backbone.dark4.1.m.8.conv1.bn.running_mean", "backbone.backbone.dark4.1.m.8.conv1.bn.running_var", "backbone.backbone.dark4.1.m.8.conv1.bn.num_batches_tracked", "backbone.backbone.dark4.1.m.8.conv2.conv.weight", "backbone.backbone.dark4.1.m.8.conv2.bn.weight", "backbone.backbone.dark4.1.m.8.conv2.bn.bias", "backbone.backbone.dark4.1.m.8.conv2.bn.running_mean", "backbone.backbone.dark4.1.m.8.conv2.bn.running_var", "backbone.backbone.dark4.1.m.8.conv2.bn.num_batches_tracked", "backbone.backbone.dark5.2.m.1.conv1.conv.weight", "backbone.backbone.dark5.2.m.1.conv1.bn.weight", "backbone.backbone.dark5.2.m.1.conv1.bn.bias", "backbone.backbone.dark5.2.m.1.conv1.bn.running_mean", "backbone.backbone.dark5.2.m.1.conv1.bn.running_var", "backbone.backbone.dark5.2.m.1.conv1.bn.num_batches_tracked", "backbone.backbone.dark5.2.m.1.conv2.conv.weight", "backbone.backbone.dark5.2.m.1.conv2.bn.weight", "backbone.backbone.dark5.2.m.1.conv2.bn.bias", "backbone.backbone.dark5.2.m.1.conv2.bn.running_mean", "backbone.backbone.dark5.2.m.1.conv2.bn.running_var", "backbone.backbone.dark5.2.m.1.conv2.bn.num_batches_tracked", "backbone.backbone.dark5.2.m.2.conv1.conv.weight", "backbone.backbone.dark5.2.m.2.conv1.bn.weight", "backbone.backbone.dark5.2.m.2.conv1.bn.bias", "backbone.backbone.dark5.2.m.2.conv1.bn.running_mean", "backbone.backbone.dark5.2.m.2.conv1.bn.running_var", "backbone.backbone.dark5.2.m.2.conv1.bn.num_batches_tracked", "backbone.backbone.dark5.2.m.2.conv2.conv.weight", "backbone.backbone.dark5.2.m.2.conv2.bn.weight", "backbone.backbone.dark5.2.m.2.conv2.bn.bias", "backbone.backbone.dark5.2.m.2.conv2.bn.running_mean", "backbone.backbone.dark5.2.m.2.conv2.bn.running_var", "backbone.backbone.dark5.2.m.2.conv2.bn.num_batches_tracked", "backbone.C3_p4.m.1.conv1.conv.weight", "backbone.C3_p4.m.1.conv1.bn.weight", "backbone.C3_p4.m.1.conv1.bn.bias", "backbone.C3_p4.m.1.conv1.bn.running_mean", "backbone.C3_p4.m.1.conv1.bn.running_var", "backbone.C3_p4.m.1.conv1.bn.num_batches_tracked", "backbone.C3_p4.m.1.conv2.conv.weight", "backbone.C3_p4.m.1.conv2.bn.weight", "backbone.C3_p4.m.1.conv2.bn.bias", "backbone.C3_p4.m.1.conv2.bn.running_mean", "backbone.C3_p4.m.1.conv2.bn.running_var", "backbone.C3_p4.m.1.conv2.bn.num_batches_tracked", "backbone.C3_p4.m.2.conv1.conv.weight", "backbone.C3_p4.m.2.conv1.bn.weight", "backbone.C3_p4.m.2.conv1.bn.bias", "backbone.C3_p4.m.2.conv1.bn.running_mean", "backbone.C3_p4.m.2.conv1.bn.running_var", "backbone.C3_p4.m.2.conv1.bn.num_batches_tracked", "backbone.C3_p4.m.2.conv2.conv.weight", "backbone.C3_p4.m.2.conv2.bn.weight", "backbone.C3_p4.m.2.conv2.bn.bias", "backbone.C3_p4.m.2.conv2.bn.running_mean", "backbone.C3_p4.m.2.conv2.bn.running_var", "backbone.C3_p4.m.2.conv2.bn.num_batches_tracked", "backbone.C3_p3.m.1.conv1.conv.weight", "backbone.C3_p3.m.1.conv1.bn.weight", "backbone.C3_p3.m.1.conv1.bn.bias", "backbone.C3_p3.m.1.conv1.bn.running_mean", "backbone.C3_p3.m.1.conv1.bn.running_var", "backbone.C3_p3.m.1.conv1.bn.num_batches_tracked", "backbone.C3_p3.m.1.conv2.conv.weight", "backbone.C3_p3.m.1.conv2.bn.weight", "backbone.C3_p3.m.1.conv2.bn.bias", "backbone.C3_p3.m.1.conv2.bn.running_mean", "backbone.C3_p3.m.1.conv2.bn.running_var", "backbone.C3_p3.m.1.conv2.bn.num_batches_tracked", "backbone.C3_p3.m.2.conv1.conv.weight", "backbone.C3_p3.m.2.conv1.bn.weight", "backbone.C3_p3.m.2.conv1.bn.bias", "backbone.C3_p3.m.2.conv1.bn.running_mean", "backbone.C3_p3.m.2.conv1.bn.running_var", "backbone.C3_p3.m.2.conv1.bn.num_batches_tracked", "backbone.C3_p3.m.2.conv2.conv.weight", "backbone.C3_p3.m.2.conv2.bn.weight", "backbone.C3_p3.m.2.conv2.bn.bias", "backbone.C3_p3.m.2.conv2.bn.running_mean", "backbone.C3_p3.m.2.conv2.bn.running_var", "backbone.C3_p3.m.2.conv2.bn.num_batches_tracked", "backbone.C3_n3.m.1.conv1.conv.weight", "backbone.C3_n3.m.1.conv1.bn.weight", "backbone.C3_n3.m.1.conv1.bn.bias", "backbone.C3_n3.m.1.conv1.bn.running_mean", "backbone.C3_n3.m.1.conv1.bn.running_var", "backbone.C3_n3.m.1.conv1.bn.num_batches_tracked", "backbone.C3_n3.m.1.conv2.conv.weight", "backbone.C3_n3.m.1.conv2.bn.weight", "backbone.C3_n3.m.1.conv2.bn.bias", "backbone.C3_n3.m.1.conv2.bn.running_mean", "backbone.C3_n3.m.1.conv2.bn.running_var", "backbone.C3_n3.m.1.conv2.bn.num_batches_tracked", "backbone.C3_n3.m.2.conv1.conv.weight", "backbone.C3_n3.m.2.conv1.bn.weight", "backbone.C3_n3.m.2.conv1.bn.bias", "backbone.C3_n3.m.2.conv1.bn.running_mean", "backbone.C3_n3.m.2.conv1.bn.running_var", "backbone.C3_n3.m.2.conv1.bn.num_batches_tracked", "backbone.C3_n3.m.2.conv2.conv.weight", "backbone.C3_n3.m.2.conv2.bn.weight", "backbone.C3_n3.m.2.conv2.bn.bias", "backbone.C3_n3.m.2.conv2.bn.running_mean", "backbone.C3_n3.m.2.conv2.bn.running_var", "backbone.C3_n3.m.2.conv2.bn.num_batches_tracked", "backbone.C3_n4.m.1.conv1.conv.weight", "backbone.C3_n4.m.1.conv1.bn.weight", "backbone.C3_n4.m.1.conv1.bn.bias", "backbone.C3_n4.m.1.conv1.bn.running_mean", "backbone.C3_n4.m.1.conv1.bn.running_var", "backbone.C3_n4.m.1.conv1.bn.num_batches_tracked", "backbone.C3_n4.m.1.conv2.conv.weight", "backbone.C3_n4.m.1.conv2.bn.weight", "backbone.C3_n4.m.1.conv2.bn.bias", "backbone.C3_n4.m.1.conv2.bn.running_mean", "backbone.C3_n4.m.1.conv2.bn.running_var", "backbone.C3_n4.m.1.conv2.bn.num_batches_tracked", "backbone.C3_n4.m.2.conv1.conv.weight", "backbone.C3_n4.m.2.conv1.bn.weight", "backbone.C3_n4.m.2.conv1.bn.bias", "backbone.C3_n4.m.2.conv1.bn.running_mean", "backbone.C3_n4.m.2.conv1.bn.running_var", "backbone.C3_n4.m.2.conv1.bn.num_batches_tracked", "backbone.C3_n4.m.2.conv2.conv.weight", "backbone.C3_n4.m.2.conv2.bn.weight", "backbone.C3_n4.m.2.conv2.bn.bias", "backbone.C3_n4.m.2.conv2.bn.running_mean", "backbone.C3_n4.m.2.conv2.bn.running_var", "backbone.C3_n4.m.2.conv2.bn.num_batches_tracked".
```

**Comment by FateScript** [comment]
Is `yolox_tiny.pth` in your cli trained by Exp you are using?

**Comment by wawaderwaran** [comment]
Yes, it is.

**Comment by FateScript** [comment]
Oh, I see, in your cli `-n yolox_tiny_cyclist -c yolox_tiny.pth -f exps/example/custom/yolox_tiny_cyclist.py` -n and -f are both used, please use only one of them. Unexpected key(s) in state_dict always means that your model and weight are not matched.
