### ISSUE TITLE
 TFLite YOLOX-Nano  int8 quantization error

### ISSUE THREAD

**Issue by Pillar1989** [Megvii-BaseDetection/YOLOX#1075]
Float16 quantization works, No test.

```bash
onnx-tf convert -i "yolox_nano.onnx" -o  nano
```
```bash
(base) se@stu:~/yolov5$ python  tf_testv2.py 
2022-01-15 08:23:02.309548: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-15 08:23:02.309583: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-15 08:23:03.956724: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956793: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956864: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956898: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956941: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.956975: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:23:03.957122: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-01-15 08:23:03.957408: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-15 08:23:05.187060: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2022-01-15 08:23:05.187116: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2022-01-15 08:23:05.187121: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:372] Ignored change_concat_input_ranges.
2022-01-15 08:23:05.188210: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: nano
2022-01-15 08:23:05.201529: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2022-01-15 08:23:05.201573: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: nano
2022-01-15 08:23:05.273244: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2022-01-15 08:23:05.527303: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: nano
2022-01-15 08:23:05.743009: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 554801 microseconds.
2022-01-15 08:23:05.982566: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-01-15 08:23:06.530075: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1962] Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs

Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs

(base) se@stu:~/yolov5$
(base) se@stu:~/yolov5$ cat tf_testv2.py 
import tensorflow as tf
import numpy as np

def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 244, 244, 3)
      yield [data.astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_saved_model("nano")
converter.target_spec.supported_types = [tf.float16]

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
#converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
#converter.inference_input_type = tf.int8  # or tf.unint8
#converter.inference_output_type = tf.int8  # or tf.uint8
converter.experimental_new_quantizer = False
tflite_quant_model = converter.convert()
open('yolox_nano.tflite', 'wb').write(tflite_quant_model)

```
But when I do int8 quantization, get an error.

```
(base) se@stu:~/yolov5$ python  tf_testv2.py 
2022-01-15 08:25:30.770253: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-15 08:25:30.770291: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-15 08:25:32.418275: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418330: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418363: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418403: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418436: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418471: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418503: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-01-15 08:25:32.418630: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-01-15 08:25:32.418864: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-15 08:25:33.335963: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2022-01-15 08:25:33.335995: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2022-01-15 08:25:33.335999: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:372] Ignored change_concat_input_ranges.
2022-01-15 08:25:33.336767: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: nano
2022-01-15 08:25:33.345063: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2022-01-15 08:25:33.345090: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: nano
2022-01-15 08:25:33.382117: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2022-01-15 08:25:33.558271: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: nano
2022-01-15 08:25:33.706672: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 369907 microseconds.
2022-01-15 08:25:33.863306: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2022-01-15 08:25:34.391789: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1962] Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs

Estimated count of arithmetic ops: 1.624 G  ops, equivalently 0.812 G  MACs
Traceback (most recent call last):
  File "/home/se/yolov5/tf_testv2.py", line 19, in <module>
    tflite_quant_model = converter.convert()
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 775, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 761, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1043, in convert
    return self._optimize_tflite_model(
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 226, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 721, in _optimize_tflite_model
    model = self._quantize(
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py", line 544, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 226, in wrapper
    raise error from None  # Re-throws the exception.
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 177, in calibrate_and_quantize
    self._feed_tensors(dataset_gen, resize_input)
  File "/home/se/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 133, in _feed_tensors
    self._calibrator.Prepare([list(s.shape) for s in input_array])
RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (1 != 2)Node number 6 (CONCATENATION) failed to prepare.

(base) se@stu:~/yolov5$ cat  tf_testv2.py 
import tensorflow as tf
import numpy as np

def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 244, 244, 3)
      yield [data.astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_saved_model("nano")
converter.target_spec.supported_types = [tf.int8]

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
#converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.inference_input_type = tf.int8  # or tf.unint8
converter.inference_output_type = tf.int8  # or tf.uint8
converter.experimental_new_quantizer = False
tflite_quant_model = converter.convert()
open('yolox_nano.tflite', 'wb').write(tflite_quant_model)

```

**Comment by Pillar1989** [comment]
Oh, my fault.

**Comment by mikel-brostrom** [comment]
I get the same error @Pillar1989. Did you manage to solve it?

**Comment by mikel-brostrom** [comment]
The input should be `(1, 3, 244, 244)`, not `(1, 244, 244, 3)`
