### ISSUE TITLE
转换为TensorRT格式时报错

### ISSUE THREAD

**Issue by zjnyly** [Megvii-BaseDetection/YOLOX#108]
```
zjnyly@zjnyly:~/Desktop/YOLOX$ python3 tools/trt.py -n yolox-s -c yolox_s.pth.tar
2021-07-23 15:59:51.812 | INFO     | __main__:main:52 - loaded checkpoint done.
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +299, GPU +0, now: CPU 2489, GPU 1770 (MiB)
/home/zjnyly/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
[TensorRT] WARNING: Tensor DataType is determined at build time for tensors not marked as input or output.
2021-07-23 16:00:10.717 | ERROR    | __main__:<module>:77 - An error has been caught in function '<module>', process 'MainProcess' (15076), thread 'MainThread' (140463830947648):
Traceback (most recent call last):

> File "tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7fbf93c30af0>

  File "tools/trt.py", line 57, in main
    model_trt = torch2trt(
                └ <function torch2trt at 0x7fbf9e129790>

  File "/usr/local/lib/python3.8/dist-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/torch2trt.py", line 558, in torch2trt
    builder.max_workspace_size = max_workspace_size
    │                            └ 4294967296
    └ <tensorrt.tensorrt.Builder object at 0x7fbf9195e7b0>

AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
```
请问这是出现了什么问题呢？

**Comment by ruinmessi** [comment]
TensorRT 的版本问题吧。。我用的 7.2.1.6

**Comment by nikhil031294** [comment]
https://github.com/NVIDIA-AI-IOT/torch2trt/issues/557#issuecomment-886428736
do this. works
