### ISSUE TITLE
CPU mode error

### ISSUE THREAD

**Issue by LLsmile** [Megvii-BaseDetection/YOLOX#1094]
max_epoch is 50. CPU mode in 46th epch get following error message.

`------------CPU Mode for This Batch-------------
2022-01-22 10:52:24 | ERROR    | yolox.models.yolo_head:332 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2022-01-22 10:52:24 | INFO     | yolox.core.trainer:186 - Training of experiment is done and the best AP is 89.09
2022-01-22 10:52:24 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1157387), thread 'MainThread' (140303677793088):
`

**Comment by FateScript** [comment]
This is not the real exception, plz provide the whole exception trace.

**Comment by LLsmile** [comment]
2022-01-24 04:06:00.773 | INFO     | yolox.core.trainer:save_ckpt:322 - Save weights to ./YOLOX_outputs/yolox_m
2022-01-24 04:06:01.415 | INFO     | yolox.core.trainer:before_epoch:193 - ---> start train epoch45
2022-01-24 04:06:01.416 | INFO     | yolox.core.trainer:before_epoch:196 - --->No mosaic aug now!
2022-01-24 04:06:01.417 | INFO     | yolox.core.trainer:before_epoch:198 - --->Add additional L1 loss now!
2022-01-24 04:06:01.418 | INFO     | yolox.core.trainer:save_ckpt:322 - Save weights to ./YOLOX_outputs/yolox_m
2022-01-24 04:06:08.858 | INFO     | yolox.core.trainer:after_iter:246 - epoch: 45/50, iter: 50/26433, mem: 3152Mb, iter_time: 0.136s, data_time: 0.000s, total_loss: 13.4, iou_loss: 3.9, l1_loss: 4.8, conf_loss: 3.6, cls_loss: 1.2, lr: 2.077e-12, size: 672, ETA: 6:02:25
2022-01-24 04:06:16.286 | INFO     | yolox.core.trainer:after_iter:246 - epoch: 45/50, iter: 100/26433, mem: 3152Mb, iter_time: 0.148s, data_time: 0.000s, total_loss: 15.5, iou_loss: 4.2, l1_loss: 4.3, conf_loss: 5.7, cls_loss: 1.3, lr: 2.069e-12, size: 672, ETA: 6:02:18
2022-01-24 04:06:16.635 | ERROR    | yolox.models.yolo_head:get_losses:332 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2022-01-24 04:06:16.646 | INFO     | yolox.core.trainer:after_train:186 - Training of experiment is done and the best AP is 82.46
2022-01-24 04:06:16.646 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1399850), thread 'MainThread' (139796703249216):
Traceback (most recent call last):

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 315, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7f246383c940>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(192, 192, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7f246383c8b0>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False], device='cuda:0')
        │    │                  │     │               │           └ 1
        │    │                  │     │               └ tensor([0.], device='cuda:0', dtype=torch.float16)
        │    │                  │     └ tensor([], device='cuda:0', size=(1, 0))
        │    │                  └ tensor([], device='cuda:0', size=(1, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7f246383ca60>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 620, in dynamic_k_matching
    topk_ious, _ = torch.topk(ious_in_boxes_matrix, n_candidate_k, dim=1)
                   │     │    │                     └ 10
                   │     │    └ tensor([], device='cuda:0', size=(1, 0))
                   │     └ <built-in method topk of type object at 0x7f24f23ff1c0>
                   └ <module 'torch' from '/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/__init__.py'>

RuntimeError: selected index k out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tools/train.py", line 118, in <module>
    launch(
    └ <function launch at 0x7f2466093dc0>

> File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f246388e0d0>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f2465f9d670>
    └ <yolox.core.trainer.Trainer object at 0x7f24638b2e20>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/core/trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f2465828790>
    └ <yolox.core.trainer.Trainer object at 0x7f24638b2e20>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/core/trainer.py", line 80, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f246387b790>
    └ <yolox.core.trainer.Trainer object at 0x7f24638b2e20>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/core/trainer.py", line 86, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f246388aa60>
    └ <yolox.core.trainer.Trainer object at 0x7f24638b2e20>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/core/trainer.py", line 98, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[   0., 1360., 1073.,  775.,  637.],
              │    │     │                [   0.,    0.,    0.,    0.,    0.],
              │    │     │                [   0.,    0.,    0.,   ...
              │    │     └ tensor([[[[-1.7412, -1.7578, -1.7578,  ..., -0.5425, -0.5596, -0.5596],
              │    │                 [-1.7236, -1.7236, -1.7412,  ..., -0.5254, ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x7f24638b2e20>

  File "/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[-1.7412, -1.7578, -1.7578,  ..., -0.5425, -0.5596, -0.5596],
           │                         [-1.7236, -1.7236, -1.7412,  ..., -0.5254,...
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
                                                           └ YOLOX(
                                                               (backbone): YOLOPAFPN(
                                                                 (backbone): CSPDarknet(
                                                                   (stem): Focus(
                                                                     (conv): BaseConv(
                                                                       (conv): ...

  File "/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ ((tensor([[[[ 0.4033,  0.4180,  0.5020,  ...,  0.4587, -0.1190, -0.0892],
           │                         [ 0.4639, -0.0953, -0.1370,  ..., -0.1318...
           └ <bound method YOLOXHead.forward of YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (c...

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 197, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x7f246383c790>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(192, 192, kernel_size=...

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 344, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7f246383c940>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(192, 192, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7f246383c8b0>

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False])
        │    │                  │     │               │           └ 1
        │    │                  │     │               └ tensor([0.])
        │    │                  │     └ tensor([], size=(1, 0))
        │    │                  └ tensor([], size=(1, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7f246383ca60>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "/home/xyz/workspace/06_study_materials/02_model/01_detection/YOLOX/yolox/models/yolo_head.py", line 620, in dynamic_k_matching
    topk_ious, _ = torch.topk(ious_in_boxes_matrix, n_candidate_k, dim=1)
                   │     │    │                     └ 10
                   │     │    └ tensor([], size=(1, 0))
                   │     └ <built-in method topk of type object at 0x7f24f23ff1c0>
                   └ <module 'torch' from '/home/xyz/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/__init__.py'>

RuntimeError: selected index k out of range

**Comment by FateScript** [comment]
Your  tensor named `ious_in_boxes_matrix` is empty. Plz check it carefully.

**Comment by FelixFu520** [comment]
> Your tensor named `ious_in_boxes_matrix` is empty. Plz check it carefully.

我看了下，ious_in_boxes_matrix是空的，怎么解决呢？

**Comment by FelixFu520** [comment]
> Your tensor named `ious_in_boxes_matrix` is empty. Plz check it carefully.

![image](https://user-images.githubusercontent.com/23306248/151305377-59c991ee-4c51-48b2-a191-8a37a48d39be.png)
我把random_resize注释掉，就可以了

**Comment by LLsmile** [comment]
> > Your tensor named `ious_in_boxes_matrix` is empty. Plz check it carefully.
> 
> ![image](https://user-images.githubusercontent.com/23306248/151305377-59c991ee-4c51-48b2-a191-8a37a48d39be.png) 我把random_resize注释掉，就可以了

How to do that? fix it to 14?

**Comment by LLsmile** [comment]
After resuming from the break point, it works well but never go into CPU mode. I don't know whether it's okay.
`2022-02-22 01:33:20 | INFO     | yolox.core.trainer:193 - ---> start train epoch45
2022-02-22 01:33:20 | INFO     | yolox.core.trainer:196 - --->No mosaic aug now!
2022-02-22 01:33:20 | INFO     | yolox.core.trainer:198 - --->Add additional L1 loss now!
2022-02-22 01:33:20 | INFO     | yolox.core.trainer:322 - Save weights to ./YOLOX_outputs/yolox_m
2022-02-22 01:33:26 | INFO     | apex.amp.handle:138 - Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0
2022-02-22 01:33:32 | INFO     | apex.amp.handle:138 - Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
2022-02-22 01:33:33 | INFO     | apex.amp.handle:138 - Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 2048.0
2022-02-22 01:33:34 | INFO     | apex.amp.handle:138 - Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 1024.0
2022-02-22 01:34:15 | INFO     | yolox.core.trainer:246 - epoch: 45/50, iter: 100/1652, mem: 8434Mb, iter_time: 0.537s, data_time: 0.001s, total_loss: 1.7, iou_loss: 0.5, l1_loss: 0.2, conf_loss: 0.8, cls_loss: 0.2, lr: 1.543e-06, size: 544, ETA: 1:27:49
`

**Comment by weipeng404** [comment]
I also met this error with `pair_wise_ious` as an empty tensor (`tensor([], device='cuda:0', size=(1, 0)`). It is the result from [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/7ee17936db849600817d7de05269bfdfb1a0eb48/yolox/models/yolo_head.py#L475) when the model predictions `bboxes_preds_per_image` is of shape `torch.Size([0, 4])`.

I guess it's because I'm using YOLOX-m to detect very small objects (around 0.01% of the input size) and the model predicts nothing at the beginning. So I cropped the input image and the training works fine so far.
