### ISSUE TITLE
单卡训练没问题，多卡训练出现如下问题

### ISSUE THREAD

**Issue by aiyodiulehuner** [Megvii-BaseDetection/YOLOX#1097]
2022-01-24 07:49:58 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 8.53M, Gflops: 23.98
2022-01-24 07:49:58 | INFO     | yolox.data.datasets.coco:63 - loading annotations into memory...
2022-01-24 07:50:17 | INFO     | yolox.data.datasets.coco:63 - Done (t=19.22s)
2022-01-24 07:50:17 | INFO     | pycocotools.coco:86 - creating index...
2022-01-24 07:50:19 | INFO     | pycocotools.coco:86 - index created!
2022-01-24 07:51:30 | INFO     | yolox.core.trainer:151 - init prefetcher, this might take one minute or less...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/opencodeset/YOLOX-0.2.0/tools/train.py", line 125, in <module>
    launch(
  File "/workspace/opencodeset/YOLOX-0.2.0/yolox/core/launch.py", line 82, in launch
    mp.start_processes(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
(base) root@2ffc03d84774:/workspace/opencodeset/YOLOX-0.2.0# /opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 42 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by FateScript** [comment]
reduce your dataloader num_worker and try again?

**Comment by aiyodiulehuner** [comment]
> 



> reduce your dataloader num_worker and try again?

yes it worked! thanks
