### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Baiyixuan1113** [Megvii-BaseDetection/YOLOX#1116]
Hi.
I'm trying to train with your code and I'm getting an AssertionError.
The training was fine when I ran train.py first, but for some reason the training was aborted, when I ran train.py again and loaded the latest_ckpt.pth that was saved at the filrst training, I got an error.

commond: ```python tools/train.py -f exps/example/custom/yolox_m_table.py -d 1 -b 2 --fp16 -o --resume YOLOX_outputs/yolox_m_table/latest_ckpt.pth```
error: ```Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    exp.merge(args.opts)
  File "/home/Data/Projects/YOLOX-main/yolox/exp/base_exp.py", line 64, in merge
    assert len(cfg_list) % 2 == 0
AssertionError```

and this is my config: 
```
class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        # ---------------- model config ---------------- #
        self.num_classes = 2
        self.depth = 0.67
        self.width = 0.75
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        # ---------------- dataloader config ---------------- #
        self.data_num_workers = 2
        self.input_size = (960, 960)  # (height, width)
        self.data_dir = "/home/Data/Datasets/Table_Detection/coco"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        # --------------  training config --------------------- #
        self.max_epoch = 100
        self.basic_lr_per_img = 0.01 / 2.0
        self.no_aug_epochs = 15

        # -----------------  testing config ------------------ #
        self.test_size = (960, 960)
```

hope for your reply.

**Comment by FateScript** [comment]
Plz try `python tools/train.py -f exps/example/custom/yolox_m_table.py -d 1 -b 2 --fp16 -o --resume` in your case.

**Comment by 1510386060** [comment]
"ython tools/train.py -f exps/example/custom/yolox_m_table.py -d 1 -b 2 --fp16 -o --resume -c YOLOX_outputs/yolox_m_table/latest_ckpt.pth"
missing parameter "-c", Try the command above

**Comment by 1510386060** [comment]
"python tools/train.py -f exps/example/custom/yolox_m_table.py -d 1 -b 2 --fp16 -o --resume -c YOLOX_outputs/yolox_m_table/latest_ckpt.pth"
missing parameter "-c", Try the command above
