### ISSUE TITLE
训练COCO格式数据集出现的报错

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#1179]
2022-03-12 10:24:23.747 | INFO     | yolox.core.trainer:before_epoch:202 - ---> start train epoch1
2022-03-12 10:24:26.179 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 10/133, mem: 1591Mb, iter_time: 0.242s, data_time: 0.002s, total_loss: 74.0, iou_loss: 4.9, l1_loss: 0.0, conf_loss: 68.6, cls_loss: 0.5, lr: 2.827e-07, size: 640, ETA: 2:41:03
2022-03-12 10:24:28.006 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 20/133, mem: 1591Mb, iter_time: 0.182s, data_time: 0.002s, total_loss: 58.1, iou_loss: 4.9, l1_loss: 0.0, conf_loss: 52.8, cls_loss: 0.4, lr: 1.131e-06, size: 480, ETA: 2:20:56
2022-03-12 10:24:29.570 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 30/133, mem: 1591Mb, iter_time: 0.156s, data_time: 0.002s, total_loss: 45.0, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 39.4, cls_loss: 0.8, lr: 2.544e-06, size: 480, ETA: 2:08:24
2022-03-12 10:24:31.332 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 40/133, mem: 1591Mb, iter_time: 0.175s, data_time: 0.002s, total_loss: 73.5, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 68.0, cls_loss: 0.7, lr: 4.523e-06, size: 640, ETA: 2:05:24
2022-03-12 10:24:33.801 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 50/133, mem: 1787Mb, iter_time: 0.246s, data_time: 0.002s, total_loss: 70.6, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 64.9, cls_loss: 1.1, lr: 7.067e-06, size: 768, ETA: 2:12:59
2022-03-12 10:24:35.372 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 60/133, mem: 1787Mb, iter_time: 0.156s, data_time: 0.002s, total_loss: 31.0, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 25.5, cls_loss: 0.7, lr: 1.018e-05, size: 480, ETA: 2:08:06
2022-03-12 10:24:36.931 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 70/133, mem: 1787Mb, iter_time: 0.155s, data_time: 0.002s, total_loss: 25.1, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 19.6, cls_loss: 0.9, lr: 1.385e-05, size: 480, ETA: 2:04:29
2022-03-12 10:24:39.171 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 80/133, mem: 1787Mb, iter_time: 0.223s, data_time: 0.002s, total_loss: 24.0, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 18.6, cls_loss: 0.7, lr: 1.809e-05, size: 576, ETA: 2:07:25
2022-03-12 10:24:41.014 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 90/133, mem: 1787Mb, iter_time: 0.183s, data_time: 0.002s, total_loss: 27.4, iou_loss: 4.9, l1_loss: 0.0, conf_loss: 21.9, cls_loss: 0.7, lr: 2.290e-05, size: 512, ETA: 2:06:45
2022-03-12 10:24:43.354 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 100/133, mem: 1787Mb, iter_time: 0.233s, data_time: 0.002s, total_loss: 33.2, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 27.7, cls_loss: 0.8, lr: 2.827e-05, size: 704, ETA: 2:09:31
2022-03-12 10:24:45.044 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 110/133, mem: 1787Mb, iter_time: 0.168s, data_time: 0.002s, total_loss: 36.7, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 31.0, cls_loss: 1.2, lr: 3.420e-05, size: 704, ETA: 2:07:51
2022-03-12 10:24:46.692 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 120/133, mem: 1787Mb, iter_time: 0.164s, data_time: 0.002s, total_loss: 18.2, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 12.6, cls_loss: 1.0, lr: 4.070e-05, size: 480, ETA: 2:06:14
2022-03-12 10:24:49.223 | INFO     | yolox.core.trainer:after_iter:260 - epoch: 1/300, iter: 130/133, mem: 1842Mb, iter_time: 0.252s, data_time: 0.002s, total_loss: 33.7, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 28.1, cls_loss: 0.8, lr: 4.777e-05, size: 800, ETA: 2:09:22
2022-03-12 10:24:49.747 | INFO     | yolox.core.trainer:save_ckpt:351 - Save weights to ./YOLOX_outputs/yolox_nano
2022-03-12 10:24:50.134 | INFO     | yolox.core.trainer:after_train:195 - Training of experiment is done and the best AP is 0.00
2022-03-12 10:24:50.137 | ERROR    | yolox.core.launch:launch:98 - An error has been caught in function 'launch', process 'MainProcess' (9699), thread 'MainThread' (140196663444032):
Traceback (most recent call last):

  File "/home/zhst/.conda/envs/yolox/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='yolox.tools.train', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8097090550>, origin='/...
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'yolox.tools', '__loader__': <_frozen_importlib_external.SourceFileL...
         └ <code object <module> at 0x7f80a342a660, file "/data_hdd/lixiang/person_detection/YOLOX/tools/train.py", line 4>

  File "/data_hdd/lixiang/person_detection/YOLOX/tools/train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file=None, experiment_name...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/data_hdd/lixiang/person_detection/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f81ae7d47b8>

  File "/data_hdd/lixiang/person_detection/YOLOX/tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f80968a78c8>
    └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/core/trainer.py", line 75, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f81aea50620>
    └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/core/trainer.py", line 85, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f81ae7d1840>
    └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/core/trainer.py", line 221, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f81ae7d1ae8>
    └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/core/trainer.py", line 325, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f80f4d55710>
    │          └ <yolox.core.trainer.Trainer object at 0x7f81ae7e8be0>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/exp/yolox_base.py", line 323, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7f81ae7cc6a8>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f80f4d55710>

  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/evaluators/coco_evaluator.py", line 162, in evaluate
    progress_bar(self.dataloader)
    │            │    └ <torch.utils.data.dataloader.DataLoader object at 0x7f81a62d15f8>
    │            └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f80f4d55710>
    └ <class 'tqdm.std.tqdm'>

  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7f81a62d15f8>
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f80a614e6a8>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f80f4e6ba20>
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f80f4e682e8>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f80a614e7b8>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f80f4e6ba20>
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f821305ec80>
    └ <torch._utils.ExceptionWrapper object at 0x7f80f4e682e8>
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhst/.conda/envs/yolox/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 110, in wrapper
    ret_val = getitem_fn(self, index)
  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/data/datasets/coco.py", line 230, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/data/datasets/coco.py", line 206, in pull_item
    img = self.load_resized_img(index)
  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/data/datasets/coco.py", line 179, in load_resized_img
    img = self.load_image(index)
  File "/data_hdd/lixiang/person_detection/YOLOX/yolox/data/datasets/coco.py", line 194, in load_image
    assert img is not None
AssertionError

**Comment by Superyanzhuang** [comment]
我也遇到这样的问题，这个问题解决了吗？

**Comment by tan90du-sx** [comment]
麻烦请问一下，coco2017数据集是不是存在一些问题，需要处理之后才能进行训练。因为我直接训练遇到了标签溢出，得到的解决方法多是转换成voc处理。期待大家的回复，谢谢。
