### ISSUE TITLE
training YOLOX-nano

### ISSUE THREAD

**Issue by ChangYaQi** [Megvii-BaseDetection/YOLOX#1183]
I have run into problem when training yolox-nano
I have used my own set to train yolox-s susscessfully earlier. But when I try to train yolox-nano, it always can't start successfully.
I saw an idea od not using my own VOC set but the formal one, so I did it.
However , the error still showed up.

*AttributeError: 'Exp' object has no attribute 'perspective'*

my cudatoolkit=10.2 Besides, I think  it is not about the env settings,  I can't even train yolox-s at all.
`
2022-03-17 01:59:25.160 | INFO     | yolox.core.trainer:before_train:126 - args: Namespace(batch_size=16, cache=False, ckpt='weights/yolox_nano.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/yolox_voc_nano.py', experiment_name='yolox_voc_nano', fp16=False, machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2022-03-17 01:59:25.164 | INFO     | yolox.core.trainer:before_train:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 20                         │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.25                       │
├──────────────────┼────────────────────────────┤
│ act              │ 'silu'                     │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ False                      │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 5                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_voc_nano'           │
├──────────────────┼────────────────────────────┤
│ test_size        │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
├──────────────────┼────────────────────────────┤
│ random_size      │ (10, 20)                   │
╘══════════════════╧════════════════════════════╛
2022-03-17 01:59:25.806 | INFO     | yolox.core.trainer:before_train:132 - Model Summary: Params: 0.90M, Gflops: 1.05
2022-03-17 01:59:28.318 | INFO     | yolox.core.trainer:resume_train:286 - loading checkpoint for fine tuning
2022-03-17 01:59:28.524 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([20, 64, 1, 1]).
2022-03-17 01:59:28.525 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([20]).
2022-03-17 01:59:28.526 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([20, 64, 1, 1]).
2022-03-17 01:59:28.526 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([20]).
2022-03-17 01:59:28.526 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([20, 64, 1, 1]).
2022-03-17 01:59:28.527 | WARNING  | yolox.utils.checkpoint:load_ckpt:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([20]).
2022-03-17 01:59:30.398 | ERROR    | yolox.core.launch:launch:98 - An error has been caught in function 'launch', process 'MainProcess' (46192), thread 'MainThread' (139836572541120):
Traceback (most recent call last):

  File "tools/train.py", line 157, in <module>
    launch(
    └ <function launch at 0x7f2d8cb6bf70>

> File "/root/autodl-tmp/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f2d8a99d1f0>

  File "tools/train.py", line 142, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f2d8c61ca60>
    └ <yolox.core.trainer.Trainer object at 0x7f2e3d2cc610>

  File "/root/autodl-tmp/YOLOX/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f2d8a97da60>
    └ <yolox.core.trainer.Trainer object at 0x7f2e3d2cc610>

  File "/root/autodl-tmp/YOLOX/yolox/core/trainer.py", line 145, in before_train
    self.train_loader = self.exp.get_data_loader(
    │                   │    │   └ <function Exp.get_data_loader at 0x7f2d8a8fc5e0>
    │                   │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │                   └ <yolox.core.trainer.Trainer object at 0x7f2e3d2cc610>
    └ <yolox.core.trainer.Trainer object at 0x7f2e3d2cc610>

  File "/root/autodl-tmp/YOLOX/exps/example/yolox_voc/yolox_voc_nano.py", line 93, in get_data_loader
    perspective=self.perspective,
                └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

AttributeError: 'Exp' object has no attribute 'perspective'
`

**Comment by ChangYaQi** [comment]
when I debug there is no bug
is it my training para;s problem?

**Comment by FateScript** [comment]
`AttributeError: 'Exp' object has no attribute 'perspective'` 
This bug is fixed in #791
