### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by Humairah1108** [Megvii-BaseDetection/YOLOX#1207]
2022-03-29 14:54:37 | INFO     | apex.amp.frontend:356 - patch_torch_functions  : True
2022-03-29 14:54:37 | INFO     | apex.amp.frontend:356 - keep_batchnorm_fp32    : None
2022-03-29 14:54:37 | INFO     | apex.amp.frontend:356 - master_weights         : None
2022-03-29 14:54:37 | INFO     | apex.amp.frontend:356 - loss_scale             : dynamic
2022-03-29 14:54:37 | INFO     | yolox.core.trainer:297 - loading checkpoint for fine tuning
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([3, 128, 1, 1]).
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([3]).
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([3, 128, 1, 1]).
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([3]).
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([3, 128, 1, 1]).
2022-03-29 14:54:37 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([3]).
2022-03-29 14:54:37 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1302), thread 'MainThread' (140426330253184):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, ckpt='/content/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/y...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/apex/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fb78b5c3170>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fb68a786c20>
    └ <yolox.core.trainer.Trainer object at 0x7fb689056dd0>

  File "/content/apex/YOLOX/yolox/core/trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fb684eba200>
    └ <yolox.core.trainer.Trainer object at 0x7fb689056dd0>

  File "/content/apex/YOLOX/yolox/core/trainer.py", line 150, in before_train
    no_aug=self.no_aug,
           │    └ False
           └ <yolox.core.trainer.Trainer object at 0x7fb689056dd0>

  File "exps/example/yolox_voc/yolox_voc_s.py", line 36, in get_data_loader
    max_labels=50,

  File "/content/apex/YOLOX/yolox/data/datasets/voc.py", line 115, in __init__
    os.path.join(rootpath, "ImageSets", "Main", name + ".txt")
    │  │    │    │                              └ 'trainval'
    │  │    │    └ '/content/apex/YOLOX/datasets/VOCdevkit/VOC2007'
    │  │    └ <function join at 0x7fb78b6647a0>
    │  └ <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
    └ <module 'os' from '/usr/lib/python3.7/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/content/apex/YOLOX/datasets/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'

**Comment by szgy66** [comment]
你好，请问你解决了嘛
