### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by GDbbq** [Megvii-BaseDetection/YOLOX#122]
![image](https://user-images.githubusercontent.com/86715812/126856737-ba1c9c2d-d83b-4107-b5bb-2c08b6942c18.png)
使用训练自己的数据集
python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 64 --fp16 -o -c /path/to/yolox_s.pth.tar

**Comment by 1VeniVediVeci1** [comment]
https://blog.csdn.net/qq_39056987/article/details/119002910?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162718419516780274142430%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=162718419516780274142430&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-1-119002910.first_rank_v2_pc_rank_v29&utm_term=yolox%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86%E8%AE%AD%E7%BB%83&spm=1018.2226.3001.4187

**Comment by wangyuan111** [comment]
请问这个问题你解决吗？我也遇到了同样的问题同样的问题
```
2021-07-27 09:14:39 | INFO     | yolox.core.trainer:307 - Save weights to /data/YOLOX_outputs/title_coco
2021-07-27 09:14:39 | INFO     | yolox.core.trainer:188 - ---> start train epoch2
2021-07-27 09:14:39 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 0.00
2021-07-27 09:14:39 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (88978), thread 'MainThread' (139691067311936):
Traceback (most recent call last):

  File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=64, ckpt='yolox_s.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "/coding/YOLOX/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f0bb95128c8>

  File "tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f0b11aebea0>
    └ <yolox.core.trainer.Trainer object at 0x7f0bb9520f60>

  File "/t/coding/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f0b11af4d08>
    └ <yolox.core.trainer.Trainer object at 0x7f0bb9520f60>

  File "/coding/YOLOX/yolox/core/trainer.py", line 79, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f0bbda0e620>
    └ <yolox.core.trainer.Trainer object at 0x7f0bb9520f60>

  File "/coding/YOLOX/yolox/core/trainer.py", line 85, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f0bbda0e6a8>
    └ <yolox.core.trainer.Trainer object at 0x7f0bb9520f60>

  File "/coding/YOLOX/yolox/core/trainer.py", line 92, in train_one_iter
    inps = inps.to(self.data_type)
           │       │    └ torch.float16
           │       └ <yolox.core.trainer.Trainer object at 0x7f0bb9520f60>
           └ None
AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by wangyuan111** [comment]
> https://blog.csdn.net/qq_39056987/article/details/119002910?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162718419516780274142430%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=162718419516780274142430&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-1-119002910.first_rank_v2_pc_rank_v29&utm_term=yolox%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86%E8%AE%AD%E7%BB%83&spm=1018.2226.3001.4187


用这篇博客里的方法解决了问题。
