### ISSUE TITLE
AssertionError: Caught AssertionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Sunzhanxin** [Megvii-BaseDetection/YOLOX#1231]

**Comment by FateScript** [comment]
Plz provide more information, thx

**Comment by whgsh** [comment]
Have same problem:
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 110, in wrapper
    ret_val = getitem_fn(self, index)
  File "/content/drive/MyDrive/YOLOX/yolox/data/datasets/mosaicdetection.py", line 93, in __getitem__
    img, _labels, _, img_id = self._dataset.pull_item(index)
  File "/content/drive/MyDrive/YOLOX/yolox/data/datasets/coco.py", line 206, in pull_item
    img = self.load_resized_img(index)
  File "/content/drive/MyDrive/YOLOX/yolox/data/datasets/coco.py", line 179, in load_resized_img
    img = self.load_image(index)
  File "/content/drive/MyDrive/YOLOX/yolox/data/datasets/coco.py", line 194, in load_image
    assert img is not None
AssertionError
