### ISSUE TITLE
Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by xmayyy** [Megvii-BaseDetection/YOLOX#1234]
PS F:\mubiaojiance\YOLOX-main> python tools/demo.py image -n yolox-s -c weights/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
2022-04-11 19:48:16.541 | INFO     | __main__:main:259 - Args: Namespace(camid=0, ckpt='weights/yolox_s.pth', conf=0.25, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.45, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)    
Traceback (most recent call last):
  File "tools/demo.py", line 320, in <module>
    main(exp, args)
  File "tools/demo.py", line 269, in main
    logger.info("Model Summary: {}".format(get_model_info(model, exp.test_size)))
  File "f:\mubiaojiance\yolox-main\yolox\utils\model_utils.py", line 26, in get_model_info
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
  File "F:\anaconda\Anaconda3\lib\site-packages\thop\profile.py", line 211, in profile
  File "F:\anaconda\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl       
    result = self.forward(*input, **kwargs)
  File "f:\mubiaojiance\yolox-main\yolox\models\yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
  File "F:\anaconda\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl       
    result = self.forward(*input, **kwargs)
  File "f:\mubiaojiance\yolox-main\yolox\models\yolo_pafpn.py", line 99, in forward
    f_out0 = torch.cat([f_out0, x1], 1)  # 512->1024/16
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
PS F:\mubiaojiance\YOLOX-main> python tools/demo.py image -n yolox-s -c weights/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
2022-04-11 19:48:29.208 | INFO     | __main__:main:259 - Args: Namespace(camid=0, ckpt='weights/yolox_s.pth', conf=0.25, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.45, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)    
Traceback (most recent call last):
  File "tools/demo.py", line 320, in <module>
    main(exp, args)
  File "tools/demo.py", line 269, in main
    logger.info("Model Summary: {}".format(get_model_info(model, exp.test_size)))
  File "f:\mubiaojiance\yolox-main\yolox\utils\model_utils.py", line 26, in get_model_info
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
  File "F:\anaconda\Anaconda3\lib\site-packages\thop\profile.py", line 211, in profile
    model(*inputs)
  File "F:\anaconda\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl        
    result = self.forward(*input, **kwargs)
  File "f:\mubiaojiance\yolox-main\yolox\models\yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
  File "F:\anaconda\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl        
    result = self.forward(*input, **kwargs)
  File "f:\mubiaojiance\yolox-main\yolox\models\yolo_pafpn.py", line 99, in forward
    f_out0 = torch.cat([f_out0, x1], 1)  # 512->1024/16
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by xmayyy** [comment]
重新安装thop就可以了
