### ISSUE TITLE
RuntimeError: Class values must be non-negative

### ISSUE THREAD

**Issue by AIgsl** [Megvii-BaseDetection/YOLOX#1243]
plz help me solve this which i hava no idea╯﹏╰
2022-04-14 11:57:19 | INFO     | yolox.core.trainer:202 - ---> start train epoch1
2022-04-14 11:57:20 | INFO     | yolox.core.trainer:195 - Training of experiment is done and the best AP is 0.00
2022-04-14 11:57:20 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (597), thread 'MainThread' (140031035574080):
Traceback (most recent call last):

  File "tools/train.py", line 139, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=32, cache=True, ckpt='weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exp...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/media/gzzn/Data/YOLOX-main/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f5b826f04d0>

  File "tools/train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f5b00d8e0e0>
    └ <yolox.core.trainer.Trainer object at 0x7f5afe0717d0>

  File "/media/gzzn/Data/YOLOX-main/yolox/core/trainer.py", line 75, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f5b00138050>
    └ <yolox.core.trainer.Trainer object at 0x7f5afe0717d0>

  File "/media/gzzn/Data/YOLOX-main/yolox/core/trainer.py", line 84, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f5afe2b0320>
    └ <yolox.core.trainer.Trainer object at 0x7f5afe0717d0>

  File "/media/gzzn/Data/YOLOX-main/yolox/core/trainer.py", line 90, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f5afe035170>
    └ <yolox.core.trainer.Trainer object at 0x7f5afe0717d0>

  File "/media/gzzn/Data/YOLOX-main/yolox/core/trainer.py", line 104, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[  0.0000, 639.0000, 363.7500,   1.9180,  70.9375],
              │    │     │                [  0.0000, 634.0000, 360.7500,  12.2734,  68.4375],
              │    │     │          ...
              │    │     └ tensor([[[[155., 155., 155.,  ..., 164., 164., 164.],
              │    │                 [156., 156., 156.,  ..., 165., 165., 165.],
              │    │                 [157., ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x7f5afe0717d0>

  File "/home/gzzn/anaconda3/envs/pytorch1.7.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[155., 155., 155.,  ..., 164., 164., 164.],
             │    │                    [156., 156., 156.,  ..., 165., 165., 165.],
             │    │                    [157.,...
             │    └ <function YOLOX.forward at 0x7f5b2ee04440>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "/media/gzzn/Data/YOLOX-main/yolox/models/yolox.py", line 35, in forward
    fpn_outs, targets, x
    │         │        └ tensor([[[[155., 155., 155.,  ..., 164., 164., 164.],
    │         │                    [156., 156., 156.,  ..., 165., 165., 165.],
    │         │                    [157., ...
    │         └ tensor([[[  0.0000, 639.0000, 363.7500,   1.9180,  70.9375],
    │                    [  0.0000, 634.0000, 360.7500,  12.2734,  68.4375],
    │              ...
    └ (tensor([[[[ 7.0557e-01,  8.2666e-01,  6.4844e-01,  ...,  1.0992e-01,
                  1.0394e-01,  2.8809e-01],
                [ 4.406...

  File "/home/gzzn/anaconda3/envs/pytorch1.7.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ((tensor([[[[ 7.0557e-01,  8.2666e-01,  6.4844e-01,  ...,  1.0992e-01,
             │    │                      1.0394e-01,  2.8809e-01],
             │    │                    [ 4.40...
             │    └ <function YOLOXHead.forward at 0x7f5b2ee008c0>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(128, 128, kernel_size=...

  File "/media/gzzn/Data/YOLOX-main/yolox/models/yolo_head.py", line 203, in forward
    dtype=xin[0].dtype,
          └ (tensor([[[[ 7.0557e-01,  8.2666e-01,  6.4844e-01,  ...,  1.0992e-01,
                        1.0394e-01,  2.8809e-01],
                      [ 4.406...

  File "/media/gzzn/Data/YOLOX-main/yolox/models/yolo_head.py", line 322, in get_losses
    imgs,
    └ tensor([[[[155., 155., 155.,  ..., 164., 164., 164.],
                [156., 156., 156.,  ..., 165., 165., 165.],
                [157., ...

  File "/home/gzzn/anaconda3/envs/pytorch1.7.0/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7f5b2ee00b90>

  File "/media/gzzn/Data/YOLOX-main/yolox/models/yolo_head.py", line 478, in get_assignments
    F.one_hot(gt_classes.to(torch.int64), self.num_classes)
    │ │       │          │  │     │       │    └ 6
    │ │       │          │  │     │       └ YOLOXHead(
    │ │       │          │  │     │           (cls_convs): ModuleList(
    │ │       │          │  │     │             (0): Sequential(
    │ │       │          │  │     │               (0): BaseConv(
    │ │       │          │  │     │                 (conv): Conv2d(128, 128, kernel_size=...
    │ │       │          │  │     └ torch.int64
    │ │       │          │  └ <module 'torch' from '/home/gzzn/anaconda3/envs/pytorch1.7.0/lib/python3.7/site-packages/torch/__init__.py'>
    │ │       │          └ <method 'to' of 'torch._C._TensorBase' objects>
    │ │       └ tensor([0., 0., 3., 5., 0., 0., 2., 1., nan, 3., 5., 0., 2., 3., nan, 1., 1., 3.,
    │ │                 nan], device='cuda:0', dtype=torch....
    │ └ <built-in function one_hot>
    └ <module 'torch.nn.functional' from '/home/gzzn/anaconda3/envs/pytorch1.7.0/lib/python3.7/site-packages/torch/nn/functional.py'>

RuntimeError: Class values must be non-negative

**Comment by FateScript** [comment]
Your class value contains nan value.

**Comment by AIgsl** [comment]
> Your class value contains nan value.

谢谢大佬，发现我的类名不小心写错了，出现了nan值，但是我改回来后，gt-classes的tensor没出现nan,但它报错仍然是“class values must be non-negative”
