### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by PhoenyHan** [Megvii-BaseDetection/YOLOX#1249]
create train job succee!2022-04-14 18:43:12.023 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 1 initialization finished.
2022-04-14 18:43:12.035 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 2 initialization finished.
2022-04-14 18:43:12.044 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 0 initialization finished.
2022-04-14 18:43:12.049 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 3 initialization finished.
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 3 using best-guess GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 2 using best-guess GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
2022-04-14 18:43:25.460 | INFO     | yolox.utils.setup_env:configure_omp:46 - 
***************************************************************
We set `OMP_NUM_THREADS` for each process to 1 to speed up.
please further tune the variable for optimal performance.
***************************************************************
2022-04-14 18:43:25 | INFO     | yolox.core.trainer:126 - args: Namespace(batch_size=64, cache=False, ckpt=None, devices=4, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=True, machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2022-04-14 18:43:25 | INFO     | yolox.core.trainer:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ '/project/train/models/'   │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 2                          │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 2                          │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 1                          │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ act              │ 'silu'                     │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ test_ann         │ 'instances_test2017.json'  │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 1                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 100                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 20                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_voc_s'              │
├──────────────────┼────────────────────────────┤
│ test_size        │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │

╘══════════════════╧════════════════════════════╛
2022-04-14 18:44:44 | INFO     | yolox.core.trainer:188 - ---> start train epoch1
2022-04-14 18:44:52 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 2/1313, mem: 6412Mb, iter_time: 4.021s, data_time: 0.004s, total_loss: 24.5, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 18.8, cls_loss: 0.9, lr: 2.320e-08, size: 640, ETA: 6 days, 2:39:44
2022-04-14 18:44:52 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 4/1313, mem: 6412Mb, iter_time: 0.410s, data_time: 0.002s, total_loss: 19.3, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 13.6, cls_loss: 1.0, lr: 9.281e-08, size: 640, ETA: 3 days, 8:48:40
2022-04-14 18:44:54 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 6/1313, mem: 6412Mb, iter_time: 0.567s, data_time: 0.002s, total_loss: 20.1, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 14.4, cls_loss: 0.9, lr: 2.088e-07, size: 640, ETA: 2 days, 12:45:55
2022-04-14 18:44:55 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 8/1313, mem: 6412Mb, iter_time: 0.649s, data_time: 0.002s, total_loss: 28.8, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 23.4, cls_loss: 0.6, lr: 3.712e-07, size: 640, ETA: 2 days, 3:29:20
2022-04-14 18:46:09 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 48/1313, mem: 6662Mb, iter_time: 2.439s, data_time: 0.033s, total_loss: 21.1, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 15.4, cls_loss: 1.0, lr: 1.336e-05, size: 672, ETA: 2 days, 16:06:27
2022-04-14 18:46:12 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 50/1313, mem: 6662Mb, iter_time: 1.740s, data_time: 0.958s, total_loss: 23.2, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 17.6, cls_loss: 0.9, lr: 1.450e-05, size: 672, ETA: 2 days, 16:04:49
2022-04-14 18:46:19 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 52/1313, mem: 7252Mb, iter_time: 3.645s, data_time: 0.035s, total_loss: 25.5, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 19.8, cls_loss: 0.9, lr: 1.568e-05, size: 768, ETA: 2 days, 18:43:34
2022-04-14 18:46:21 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 54/1313, mem: 7252Mb, iter_time: 0.792s, data_time: 0.002s, total_loss: 26.0, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 20.4, cls_loss: 0.9, lr: 1.691e-05, size: 768, ETA: 2 days, 17:19:22
2022-04-14 18:46:22 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 56/1313, mem: 7252Mb, iter_time: 0.743s, data_time: 0.002s, total_loss: 23.7, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 18.1, cls_loss: 0.8, lr: 1.819e-05, size: 768, ETA: 2 days, 15:57:21
2022-04-14 18:46:25 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 58/1313, mem: 7252Mb, iter_time: 1.504s, data_time: 0.164s, total_loss: 27.8, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 22.1, cls_loss: 0.9, lr: 1.951e-05, size: 768, ETA: 2 days, 15:38:24
2022-04-14 18:46:30 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 60/1313, mem: 7252Mb, iter_time: 2.197s, data_time: 0.093s, total_loss: 26.3, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 20.7, cls_loss: 0.8, lr: 2.088e-05, size: 768, ETA: 2 days, 16:11:16
2022-04-14 18:46:33 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 62/1313, mem: 7252Mb, iter_time: 1.360s, data_time: 0.035s, total_loss: 25.1, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 19.5, cls_loss: 0.9, lr: 2.230e-05, size: 672, ETA: 2 days, 15:42:56
2022-04-14 18:46:38 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 64/1313, mem: 7252Mb, iter_time: 2.784s, data_time: 0.251s, total_loss: 19.3, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 13.6, cls_loss: 1.0, lr: 2.376e-05, size: 672, ETA: 2 days, 16:53:43
2022-04-14 18:46:40 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 66/1313, mem: 7252Mb, iter_time: 0.796s, data_time: 0.002s, total_loss: 24.5, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 19.0, cls_loss: 0.8, lr: 2.527e-05, size: 672, ETA: 2 days, 15:48:26
2022-04-14 18:46:46 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 68/1313, mem: 7252Mb, iter_time: 3.102s, data_time: 0.036s, total_loss: 18.9, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 13.3, cls_loss: 0.9, lr: 2.682e-05, size: 672, ETA: 2 days, 17:15:18
2022-04-14 18:46:48 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 70/1313, mem: 7252Mb, iter_time: 0.892s, data_time: 
2022-04-14 18:47:46 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 96/1313, mem: 7458Mb, iter_time: 1.800s, data_time: 0.105s, total_loss: 22.5, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 17.0, cls_loss: 0.8, lr: 5.346e-05, size: 800, ETA: 2 days, 20:53:51
2022-04-14 18:47:49 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 98/1313, mem: 7458Mb, iter_time: 1.735s, data_time: 0.003s, total_loss: 26.7, iou_loss: 4.8, l1_loss: 0.0, conf_loss: 21.3, cls_loss: 0.7, lr: 5.571e-05, size: 800, ETA: 2 days, 20:46:53
2022-04-14 18:47:55 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 100/1313, mem: 7458Mb, iter_time: 2.782s, data_time: 0.003s, total_loss: 20.5, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 14.9, cls_loss: 1.0, lr: 7.538e-05, size: 768, ETA: 2 days, 21:17:00
2022-04-14 18:48:23 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 116/1313, mem: 7458Mb, iter_time: 0.726s, data_time: 0.003s, total_loss: 17.4, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 12.0, cls_loss: 0.9, lr: 1.042e-04, size: 800, ETA: 2 days, 20:34:00
2022-04-14 18:49:00 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 136/1313, mem: 7458Mb, iter_time: 1.297s, data_time: 0.450s, total_loss: 17.2, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 11.8, cls_loss: 0.9, lr: 1.073e-04, size: 800, ETA: 2 days, 20:15:08
2022-04-14 19:11:48 | INFO     | yolox.core.trainer:246 - epoch: 1/100, iter: 932/1313, mem: 7458Mb, iter_time: 1.207s, data_time: 0.032s, total_loss: 6.8, iou_loss: 3.0, l1_loss: 0.0, conf_loss: 3.1, cls_loss: 0.7, lr: 5.039e-03, size: 576, ETA: 2 days, 14:42:44
Process Process-4:3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process Process-1:3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process Process-2:3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 741, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process Process-2:2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Process Process-3:4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "tools/train.py", line 132, in <module>
    args=(exp, args),
  File "/project/train/src_repo/YOLOX/yolox/core/launch.py", line 95, in launch
    start_method=start_method,
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with signal SIGKILL
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 28 leaked semaphores to clean up at shutdown
  len(cache))
{"code":20000,"message":"执行成功","data":"成功"}{"code":20000,"message":"执行成功","data":"成功"}
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by FateScript** [comment]
What's your pytorch version and what if you set num_workers to 0 in torch dataloader?

**Comment by PhoenyHan** [comment]
@FateScript  pytorch version 1.9.0+cu111, haven't try for num_workers = 0, but previously tried num worker = 4 and batch size = 32 using 4 gpus, can run properly without this error

**Comment by lingdujunshang** [comment]
in English: and then?did u find reason?how ?
in Chinese:后来咋办了啊？楼主解决这个问题了吗？
