### ISSUE TITLE
ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1769), thread 'MainThread' (140583471122304):

### ISSUE THREAD

**Issue by jomanaakk** [Megvii-BaseDetection/YOLOX#1250]
i have faced this error when i tried to train my model i couldn't figure out why this happened. 
 
2022-04-16 06:01:36 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (1769), thread 'MainThread' (140583471122304):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, ckpt='/content/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/y...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fdc1fb56e60>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fdb20cc9170>
    └ <yolox.core.trainer.Trainer object at 0x7fdb1af60f10>

  File "/content/YOLOX/yolox/core/trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fdb1b42b200>
    └ <yolox.core.trainer.Trainer object at 0x7fdb1af60f10>

  File "/content/YOLOX/yolox/core/trainer.py", line 150, in before_train
    no_aug=self.no_aug,
           │    └ False
           └ <yolox.core.trainer.Trainer object at 0x7fdb1af60f10>

  File "exps/example/yolox_voc/yolox_voc_s.py", line 63, in get_data_loader
    len(self.dataset), seed=self.seed if self.seed else 0
        │    │              │    │       │    └ None
        │    │              │    │       └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
        │    │              │    └ None
        │    │              └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
        │    └ <yolox.data.datasets.mosaicdetection.MosaicDetection object at 0x7fdb1fafae10>
        └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/content/YOLOX/yolox/data/samplers.py", line 68, in __init__
    assert size > 0
           └ 0

AssertionError: assert size > 0

**Comment by 3083156185** [comment]
i meet this question

**Comment by FateScript** [comment]
Seems your dataset is None object. Did `get_dataloader` in your Exp object work well?

**Comment by hs-bh** [comment]
How did you solve this problem?
