### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by zsgqwer** [Megvii-BaseDetection/YOLOX#126]
python tools/train.py -f exps/my_exps/yolox_voc/yolox_voc_s.py  -d 1 -b 32 --fp16 -o -c model_data/yolox_s.pth.tar

This is my console output：

2021-07-25 08:32:45 | INFO     | yolox.core.trainer:124 - a - args: Namespace(batch_size=32, ckpt='model_data/yolox_s.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/my_exps/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=True, local_rank=0, machine_rank=0, name=None, num_machine=1, occumpy=True, opts=[], resume=False, start_epoch=None)

2021-07-25 08:32:45 | INFO     | yolox.core.trainer:125 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪═══════════════════════════
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤

I don’t have the above file. Is this the reason?

after There are some Warning

2021-07-25 08:32:48 | INFO     | apex.amp.scaler:69 - Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")

2021-07-25 08:32:49 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (7236), thread 'MainThread' (140300328642304):
Traceback (most recent call last):

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zsg/anaconda3/anaconda/envs/YoloX_torch1.7_python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zsg/anaconda3/anaconda/envs/YoloX_torch1.7_python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zsg/anaconda3/anaconda/envs/YoloX_torch1.7_python3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zsg/py/zyf/YOLOX-main/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/zsg/py/zyf/YOLOX-main/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/zsg/py/zyf/YOLOX-main/yolox/data/datasets/voc.py", line 145, in pull_item
    target = self.load_anno(index)
  File "/home/zsg/py/zyf/YOLOX-main/yolox/data/datasets/voc.py", line 126, in load_anno
    target = self.target_transform(target)
  File "/home/zsg/py/zyf/YOLOX-main/yolox/data/datasets/voc.py", line 64, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'mask'

mask is one of my dataset object name , I put VOCdevkit in ./datasets

**Comment by 1VeniVediVeci1** [comment]
I had this problem too, and I found out that I foget to add the "," after the object name in voc_classes.py, for example: "mask"**,**

**Comment by zsgqwer** [comment]
Thank you. I'll try.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月25日(星期天) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] KeyError: Caught KeyError in DataLoader worker process 0. (#126)

**Comment by sunfei007** [comment]
这个问题得到解决了吗，我也出现了这个问题

**Comment by Hymnhyz** [comment]
I have the same problem, how to solve it?

**Comment by Hymnhyz** [comment]
I solved it, and all categories in the custom VOC_CLASSES were lowercase. Because of this sentence name is obj.find ("name"). text.lower().strip().

**Comment by lyp-oss** [comment]
> I solved it, and all categories in the custom VOC_CLASSES were lowercase. Because of this sentence name is obj.find ("name"). text.lower().strip().

![image](https://user-images.githubusercontent.com/72694315/127082286-2d4ef52f-91ab-49d0-9337-aa1694b13bbb.png)
gai'cheng'zhe改成这样吗

**Comment by Hymnhyz** [comment]
> > I solved it, and all categories in the custom VOC_CLASSES were lowercase. Because of this sentence name is obj.find ("name"). text.lower().strip().
> 
> ![image](https://user-images.githubusercontent.com/72694315/127082286-2d4ef52f-91ab-49d0-9337-aa1694b13bbb.png)
> gai'cheng'zhe改成这样吗

你也可以直接把自定义的VOC_CLASSES里面的类别改成小写

**Comment by lyp-oss** [comment]
> > > I solved it, and all categories in the custom VOC_CLASSES were lowercase. Because of this sentence name is obj.find ("name"). text.lower().strip().
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/72694315/127082286-2d4ef52f-91ab-49d0-9337-aa1694b13bbb.png)
> > gai'cheng'zhe改成这样吗
> 
> 你也可以直接把自定义的VOC_CLASSES里面的类别改成小写

可是我数据集标注的标签首写字母是的大写。
