### ISSUE TITLE
求助：FileNotFoundError: [Errno 2] No such file or directory: 'D:/CODE/make_dataset_yolo/ImageSets\\Main\\a.txt'

### ISSUE THREAD

**Issue by Neural1996** [Megvii-BaseDetection/YOLOX#1264]
Writing Zn VOC results file
Writing We VOC results file
Writing Sk VOC results file
Writing Sc VOC results file
Eval IoU : 0.50
2022-04-22 10:57:37 | INFO     | yolox.core.trainer:195 - Training of experiment is done and the best AP is 0.00
2022-04-22 10:57:37 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (15996), thread 'MainThread' (3396):
Traceback (most recent call last):

  File "D:/WorkSpace/PythonProjects/YOLOX-main/tools\train.py", line 141, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, cache=False, ckpt='D:/WorkSpace/PythonProjects/YOLOX-main/yolox_s.pth', devices=0, dist_backend='nccl...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001C0EB8808C8>

  File "D:/WorkSpace/PythonProjects/YOLOX-main/tools\train.py", line 119, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001C0EB8309D8>
    └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 75, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001C0EB846950>
    └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 85, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000001C0EB87EB70>
    └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 221, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000001C0EB87EE18>
    └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 325, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>
    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C0F4BDDEF0>
    │          └ <yolox.core.trainer.Trainer object at 0x000001C0EB5734E0>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\exp\yolox_base.py", line 323, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x000001C0EB876D08>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C0F4BDDEF0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_evaluator.py", line 128, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([  5.3115,   0.3976, 108.0000], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 2.4047e+02,  1.9222e+00,  3.7863e+02,  1.8456e+02],
                   │    │                             [ 6.0772e+01,  2.5994e+00,  1.0871e+02,  3.6527e+0...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x000001C0EB876E18>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C0F4BDDEF0>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_evaluator.py", line 206, in evaluate_prediction
    all_boxes, tempdir
    │          └ 'C:\\Users\\liuming\\AppData\\Local\\Temp\\tmppr675g44'
    └ [[array([[ 2.40469055e+02,  1.92217863e+00,  3.78625244e+02,
               1.84562042e+02,  5.40169120e-01],
             [ 6.07719841e+...

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\data\datasets\voc.py", line 270, in evaluate_detections
    mAP = self._do_python_eval(output_dir, iou)
          │    │               │           └ 0.5
          │    │               └ 'C:\\Users\\liuming\\AppData\\Local\\Temp\\tmppr675g44'
          │    └ <function VOCDetection._do_python_eval at 0x000001C0EB87E840>
          └ <yolox.data.datasets.voc.VOCDetection object at 0x000001C08E586898>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\data\datasets\voc.py", line 341, in _do_python_eval
    use_07_metric=use_07_metric,
                  └ True

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_eval.py", line 85, in voc_eval
    with open(imagesetfile, "r") as f:
              └ 'D:/CODE/make_dataset_yolo/ImageSets\\Main\\a.txt'

FileNotFoundError: [Errno 2] No such file or directory: 'D:/CODE/make_dataset_yolo/ImageSets\\Main\\a.txt'

**Comment by Neural1996** [comment]
main下添加a.txt文件后，改报错为：

Writing Zn VOC results file
Writing We VOC results file
Writing Sk VOC results file
Writing Sc VOC results file
Eval IoU : 0.50
2022-04-22 11:32:55 | INFO     | yolox.core.trainer:195 - Training of experiment is done and the best AP is 0.00
2022-04-22 11:32:55 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (15980), thread 'MainThread' (11640):
Traceback (most recent call last):

  File "D:/WorkSpace/PythonProjects/YOLOX-main/tools\train.py", line 141, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, cache=False, ckpt='D:/WorkSpace/PythonProjects/YOLOX-main/yolox_s.pth', devices=0, dist_backend='nccl...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x00000164A56B18C8>

  File "D:/WorkSpace/PythonProjects/YOLOX-main/tools\train.py", line 119, in main
    trainer.train()
    │       └ <function Trainer.train at 0x00000164A56609D8>
    └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 75, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x00000164A5676950>
    └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 85, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x00000164A56AFB70>
    └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 221, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x00000164A56AFE18>
    └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\core\trainer.py", line 325, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>
    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x00000164A59F2940>
    │          └ <yolox.core.trainer.Trainer object at 0x00000164A56BFE10>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\exp\yolox_base.py", line 323, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x00000164A56A7D08>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x00000164A59F2940>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_evaluator.py", line 128, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([  5.3791,   0.4217, 108.0000], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 2.6824e+02,  9.3319e+01,  3.4385e+02,  1.6720e+02],
                   │    │                             [-3.3677e+00,  4.6044e+02,  7.8674e+01,  5.9028e+0...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x00000164A56A7E18>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x00000164A59F2940>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_evaluator.py", line 206, in evaluate_prediction
    all_boxes, tempdir
    │          └ 'C:\\Users\\liuming\\AppData\\Local\\Temp\\tmp9kyz166d'
    └ [[array([[ 2.68244385e+02,  9.33191299e+01,  3.43853333e+02,
               1.67197830e+02,  5.46744108e-01],
             [-3.36769748e+...

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\data\datasets\voc.py", line 270, in evaluate_detections
    mAP = self._do_python_eval(output_dir, iou)
          │    │               │           └ 0.5
          │    │               └ 'C:\\Users\\liuming\\AppData\\Local\\Temp\\tmp9kyz166d'
          │    └ <function VOCDetection._do_python_eval at 0x00000164A56AF840>
          └ <yolox.data.datasets.voc.VOCDetection object at 0x00000164B0C75B70>

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\data\datasets\voc.py", line 341, in _do_python_eval
    use_07_metric=use_07_metric,
                  └ True

  File "D:\WorkSpace\PythonProjects\YOLOX-main\yolox\evaluators\voc_eval.py", line 109, in voc_eval
    R = [obj for obj in recs[imagename] if obj["name"] == classname]
                        │    │                            └ 'Zn'
                        │    └ '2406'
                        └ {}

KeyError: '2406'

**Comment by Finorita** [comment]
HI,我昨天才搞懂，你是不是还修改了年份信息呀~修改年份信息后，记得把对应变量的数组改成一维数组呀~具体参考这个~https://zhuanlan.zhihu.com/p/397499216
不要只看人家红色框框框起来的，也要看看代码的上下文呀！

**Comment by Neural1996** [comment]
> HI,我昨天才搞懂，你是不是还修改了年份信息呀~修改年份信息后，记得把对应变量的数组改成一维数组呀~具体参考这个~https://zhuanlan.zhihu.com/p/397499216 不要只看人家红色框框框起来的，也要看看代码的上下文呀！

![image](https://user-images.githubusercontent.com/88218815/172145584-96c68c87-b761-4835-8c9e-90ae4575f66a.png)
是这个嘛，谢谢啦，我当时也找到了

**Comment by Neural1996** [comment]
> HI,我昨天才搞懂，你是不是还修改了年份信息呀~修改年份信息后，记得把对应变量的数组改成一维数组呀~具体参考这个~https://zhuanlan.zhihu.com/p/397499216 不要只看人家红色框框框起来的，也要看看代码的上下文呀！

![image](https://user-images.githubusercontent.com/88218815/172145584-96c68c87-b761-4835-8c9e-90ae4575f66a.png)
是这个嘛，谢谢啦，我当时也找到了

**Comment by Finorita** [comment]
你好，你的邮件我已收到。感谢你的来信。
