### ISSUE TITLE
python .\tools\trt.py  -n  yolox-s -c yolox_s.pth

### ISSUE THREAD

**Issue by gwq2018** [Megvii-BaseDetection/YOLOX#1267]
(tensorrt82) E:\py-pro\YOLOX-main>python .\tools\trt.py  -n  yolox-s -c yolox_s.pth
2022-04-22 13:28:44.097 | ERROR    | __main__:<module>:83 - An error has been caught in function '<module>', process 'MainProcess' (13260), thread 'MainThread' (8804):
Traceback (most recent call last):

> File ".\tools\trt.py", line 83, in <module>
    main()
    └ <function main at 0x000001F4C649D840>

  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ ()
           └ <function main at 0x000001F4C5C80598>

  File ".\tools\trt.py", line 56, in main
    model.load_state_dict(ckpt["model"])
    │     │               └ OrderedDict([('backbone.backbone.stem.conv.conv.weight', tensor([[[[ 1.7095e-02,  2.7756e-02, -4.5178e-02],
    │     │                           [ 1.655...
    │     └ <function Module.load_state_dict at 0x000001F4C4369D90>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

KeyError: 'model'

请问这是什么原因？

**Comment by FateScript** [comment]
duplicated with #1268
