### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Unspecified' when I start training 

### ISSUE THREAD

**Issue by Abdullamhd** [Megvii-BaseDetection/YOLOX#1280]
When I start training i got the following error 
`ValueError: invalid literal for int() with base 10: 'Unspecified'
Traceback (most recent call last):

  File "tools/train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='/content/YOLOX/weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=Non...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f7306fdd950>

  File "tools/train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f7237147e60>
    └ <yolox.core.trainer.Trainer object at 0x7f72362fbd90>

  File "/content/YOLOX/yolox/core/trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f72362ff5f0>
    └ <yolox.core.trainer.Trainer object at 0x7f72362fbd90>

  File "/content/YOLOX/yolox/core/trainer.py", line 153, in before_train
    cache_img=self.args.cache,
              │    │    └ False
              │    └ Namespace(batch_size=16, cache=False, ckpt='/content/YOLOX/weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=Non...
              └ <yolox.core.trainer.Trainer object at 0x7f72362fbd90>

  File "/content/YOLOX/exps/example/yolox_voc/yolox_voc_s.py", line 52, in get_data_loader
    cache=cache_img,
          └ False

  File "/content/YOLOX/yolox/data/datasets/voc.py", line 131, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function VOCDetection._load_coco_annotations at 0x7f72362e9200>
    │                  └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>
    └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>

  File "/content/YOLOX/yolox/data/datasets/voc.py", line 140, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in range(len(self.ids))]
            │    │                                              │    └ [('/content/YOLOX/datasets/VOCdevkit/VOC2007', '1'), ('/content/YOLOX/datasets/VOCdevkit/VOC2007', '10'), ('/content/YOLOX/da...
            │    │                                              └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>
            │    └ <function VOCDetection.load_anno_from_ids at 0x7f72362e9320>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>

  File "/content/YOLOX/yolox/data/datasets/voc.py", line 140, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in range(len(self.ids))]
            │    │                  │         │                 │    └ [('/content/YOLOX/datasets/VOCdevkit/VOC2007', '1'), ('/content/YOLOX/datasets/VOCdevkit/VOC2007', '10'), ('/content/YOLOX/da...
            │    │                  │         │                 └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>
            │    │                  │         └ 0
            │    │                  └ 0
            │    └ <function VOCDetection.load_anno_from_ids at 0x7f72362e9320>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>

  File "/content/YOLOX/yolox/data/datasets/voc.py", line 196, in load_anno_from_ids
    res, img_info = self.target_transform(target)
                    │    │                └ <Element 'annotation' at 0x7f721f4b8dd0>
                    │    └ <yolox.data.datasets.voc.AnnotationTransform object at 0x7f723634a050>
                    └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7240a78b90>

  File "/content/YOLOX/yolox/data/datasets/voc.py", line 56, in __call__
    difficult = int(difficult.text) == 1
                    │         └ <attribute 'text' of 'xml.etree.ElementTree.Element' objects>
                    └ <Element 'difficult' at 0x7f721f4b6f50>

ValueError: invalid literal for int() with base 10: 'Unspecified'

`

I configure Pascal VOC Datasets already

**Comment by LittleFoodie** [comment]
Show me the **def parse_rec** function in **voc_eval.py** file please(Screenshot),and can you speak Chinese?
