### ISSUE TITLE
RuntimeError: The size of tensor a (3549) must match the size of tensor b (8400) at non-singleton dimension 1

### ISSUE THREAD

**Issue by lyyiangang** [Megvii-BaseDetection/YOLOX#130]
when I run following commands,
```bash
model_path=model/yolox_nano.pth
model_name=yolox-nano
python tools/demo.py video -n $model_name -c $model_path --path data/cat.mp4 --conf 0.3 --nms 0.65 --tsize 640  --device gpu --save_result --trt
```

```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7_4g5yxg because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2021-07-25 06:36:32.688 | INFO     | __main__:main:229 - Args: Namespace(camid=0, ckpt='model/yolox_nano.pth', conf=0.3, demo='video', device='gpu', exp_file=None, experiment_name='nano', fp16=False, fuse=False, name='yolox-nano', nms=0.65, path='data/cat.mp4', save_result=True, show_result=True, trt=True, tsize=640)
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1153.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-07-25 06:36:32.837 | INFO     | __main__:main:239 - Model Summary: Params: 0.91M, Gflops: 2.55
2021-07-25 06:36:34.421 | INFO     | __main__:main:269 - Using TensorRT to inference
2021-07-25 06:36:34.561 | INFO     | __main__:__init__:100 - loading tensorrt file ./YOLOX_outputs/nano/model_trt.pth
2021-07-25 06:36:47.372 | INFO     | __main__:imageflow_demo:195 - video save_path is ./YOLOX_outputs/nano/vis_res/2021_07_25_06_36_47/cat.mp4
Traceback (most recent call last):
  File "tools/demo.py", line 286, in <module>
    main(exp, args)
  File "tools/demo.py", line 279, in main
    imageflow_demo(predictor, vis_folder, current_time, args)
  File "tools/demo.py", line 202, in imageflow_demo
    outputs, img_info = predictor.inference(frame)
  File "tools/demo.py", line 132, in inference
    outputs = self.decoder(outputs, dtype=outputs.type())
  File "/home/lyy/258G/code/YOLOX/yolox/models/yolo_head.py", line 231, in decode_outputs
    outputs[..., :2] = (outputs[..., :2] + grids) * strides
RuntimeError: The size of tensor a (3549) must match the size of tensor b (8400) at non-singleton dimension 1
```

**Comment by ruinmessi** [comment]
the default sizes of yolox-nano and its trt model are 416x416. So you may change `--tsize 640` to `--tsize 416`

**Comment by lyyiangang** [comment]
@ruinmessi  thanks for your reply. your comment works.
