### ISSUE TITLE
安装环境问题，运行pip3 install -v -e . 或python3 setup.py develop总是报错 无法安装onnx1.8.1

### ISSUE THREAD

**Issue by Astroooh** [Megvii-BaseDetection/YOLOX#1311]
部分报错如下
Searching for onnx==1.8.1
Reading https://pypi.org/simple/onnx/
/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/2b/8d/c924f54e19ec71543c18658d86e8337579d5a784bd524b7f18e2e2cd6f17/onnx-1.8.1.tar.gz#sha256=9d65c52009a90499f8c25fdfe5acda3ac88efe0788eb1d5f2575a989277145fb
Best match: onnx 1.8.1
Processing onnx-1.8.1.tar.gz
Writing /tmp/easy_install-um92dit4/onnx-1.8.1/setup.cfg
Running onnx-1.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-um92dit4/onnx-1.8.1/egg-dist-tmp-c40cebtc
fatal: 不是一个 git 仓库（或者任何父目录）：.git
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-um92dit4/onnx-1.8.1/setup.py", line 75, in <module>
    long_description_content_type="text/markdown",
AssertionError: Could not find "cmake" executable!

部分报错如下
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-um92dit4/onnx-1.8.1/setup.py", line 75, in <module>
    long_description_content_type="text/markdown",
AssertionError: Could not find "cmake" executable!
有同样问题的人吗？感谢帮助～

**Comment by Astroooh** [comment]
问题好像出在无法安装onnx==1.8.1 

$ pip install onnx==1.8.1

Collecting onnx==1.8.1
  Using cached onnx-1.8.1.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dell/anaconda3/envs/Meg_yolox/bin/python /home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_ns_rsj9
       cwd: /tmp/pip-install-hug_g7u2/onnx_b570d43109854fe5a20e7ece5f867518
  Complete output (19 lines):
  fatal: 不是一个 git 仓库（或者任何父目录）：.git
  Traceback (most recent call last):
    File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 75, in <module>
      assert CMAKE, 'Could not find "cmake" executable!'
  AssertionError: Could not find "cmake" executable!
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/8d/c924f54e19ec71543c18658d86e8337579d5a784bd524b7f18e2e2cd6f17/onnx-1.8.1.tar.gz#sha256=9d65c52009a90499f8c25fdfe5acda3ac88efe0788eb1d5f2575a989277145fb (from https://pypi.org/simple/onnx/). Command errored out with exit status 1: /home/dell/anaconda3/envs/Meg_yolox/bin/python /home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_ns_rsj9 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement onnx==1.8.1 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for onnx==1.8.1

该问题求助～

**Comment by Astroooh** [comment]
问题好像出在无法安装onnx==1.8.1

$ pip install onnx==1.8.1
Collecting onnx==1.8.1
Using cached onnx-1.8.1.tar.gz (5.2 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1:
command: /home/dell/anaconda3/envs/Meg_yolox/bin/python /home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_ns_rsj9
cwd: /tmp/pip-install-hug_g7u2/onnx_b570d43109854fe5a20e7ece5f867518
Complete output (19 lines):
fatal: 不是一个 git 仓库（或者任何父目录）：.git
Traceback (most recent call last):
File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in
main()
File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
return self._get_build_requires(
File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
self.run_setup()
File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
super(_BuildMetaLegacyBackend,
File "/tmp/pip-build-env-g5m8wl3y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
exec(compile(code, file, 'exec'), locals())
File "setup.py", line 75, in
assert CMAKE, 'Could not find "cmake" executable!'
AssertionError: Could not find "cmake" executable!

WARNING: Discarding https://files.pythonhosted.org/packages/2b/8d/c924f54e19ec71543c18658d86e8337579d5a784bd524b7f18e2e2cd6f17/onnx-1.8.1.tar.gz#sha256=9d65c52009a90499f8c25fdfe5acda3ac88efe0788eb1d5f2575a989277145fb (from https://pypi.org/simple/onnx/). Command errored out with exit status 1: /home/dell/anaconda3/envs/Meg_yolox/bin/python /home/dell/anaconda3/envs/Meg_yolox/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_ns_rsj9 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement onnx==1.8.1 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for onnx==1.8.1

该问题求助～

**Comment by rahuja23** [comment]
Any leads? I am facing the same issue when trying to run setup.py
