### ISSUE TITLE
cannot import name 'Trainer' from 'yolox.core.trainer'

### ISSUE THREAD

**Issue by ladyxuxu** [Megvii-BaseDetection/YOLOX#1398]
when train it happen , i try add  
import sys
sys.path.append(r"/script/videostructure_yolox/YOLOX") in train.py . but  problem  still alive

**Comment by ladyxuxu** [comment]
Traceback (most recent call last):
File "/script/videostructure_yolox/YOLOX/tools/train.py", line 21, in <module>
from yolox.core import launch
File "/opt/conda/lib/python3.8/site-packages/yolox-0.3.0-py3.8-linux-x86_64.egg/yolox/core/__init__.py", line 6, in <module>
from .trainer import Trainer
ImportError: cannot import name 'Trainer' from 'yolox.core.trainer' (/opt/conda/lib/python3.8/site-packages/yolox-0.3.0-py3.8-linux-x86_64.egg/yolox/core/trainer.py)

**Comment by FateScript** [comment]
Plz install through pip but not hack `sys.path`.
