### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by rubbish-qi** [Megvii-BaseDetection/YOLOX#1455]
PS D:\LearningRescourse\CODE\yolo\YOLOX\YOLOX-main>  python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 1 -c weights/yolox_s.pth
2022-07-31 18:51:10 | INFO     | yolox.core.trainer:126 - args: Namespace(experiment_name='yolox_voc_s', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, exp_file='exps/example/yolox_voc/yolox_voc_s.py', resume=False, ckpt='weights/yolox_s.pth', start_epoch=None, num_machines=1, machine_rank=0, fp16=False, cache=False, occupy=False, opts=[])
2022-07-31 18:51:10 | INFO     | yolox.core.trainer:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 21                         │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ act              │ 'silu'                     │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 0                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 1                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_voc_s'              │
├──────────────────┼────────────────────────────┤
│ test_size        │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
╘══════════════════╧════════════════════════════╛
2022-07-31 18:51:10 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 8.95M, Gflops: 26.80
2022-07-31 18:51:11 | INFO     | yolox.core.trainer:286 - loading checkpoint for fine tuning
2022-07-31 18:51:11 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (24936), thread 'MainThread' (26252):
Traceback (most recent call last):

  File "D:\LearningRescourse\CODE\yolo\YOLOX\YOLOX-main\tools\train.py", line 130, in <module>
    launch(
    └ <function launch at 0x000002777B434D30>

> File "D:\anaconda3\envs\pytorch\lib\site-packages\yolox-0.1.0-py3.9-win-amd64.egg\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...    
    └ <function main at 0x000002777A253A60>

  File "D:\LearningRescourse\CODE\yolo\YOLOX\YOLOX-main\tools\train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002777B6CF280>
    └ <yolox.core.trainer.Trainer object at 0x000002777A255F70>

  File "D:\anaconda3\envs\pytorch\lib\site-packages\yolox-0.1.0-py3.9-win-amd64.egg\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000002777A20B790>
    └ <yolox.core.trainer.Trainer object at 0x000002777A255F70>

  File "D:\anaconda3\envs\pytorch\lib\site-packages\yolox-0.1.0-py3.9-win-amd64.egg\yolox\core\trainer.py", line 141, in before_train
    model = self.resume_train(model)
            │    │            └ YOLOX(
            │    │                (backbone): YOLOPAFPN(
            │    │                  (backbone): CSPDarknet(
            │    │                    (stem): Focus(
            │    │                      (conv): BaseConv(
            │    │                        (conv): ...
            │    └ <function Trainer.resume_train at 0x000002777A20BB80>
            └ <yolox.core.trainer.Trainer object at 0x000002777A255F70>

  File "D:\anaconda3\envs\pytorch\lib\site-packages\yolox-0.1.0-py3.9-win-amd64.egg\yolox\core\trainer.py", line 288, in resume_train
    ckpt = torch.load(ckpt_file, map_location=self.device)["model"]
           │     │    │                       │    └ 'cuda:0'
           │     │    │                       └ <yolox.core.trainer.Trainer object at 0x000002777A255F70>
           │     │    └ 'weights/yolox_s.pth'
           │     └ <function load at 0x0000027778D87EE0>
           └ <module 'torch' from 'D:\\anaconda3\\envs\\pytorch\\lib\\site-packages\\torch\\__init__.py'>

KeyError: 'model'

**Comment by FateScript** [comment]
`-c weights/yolox_s.pth` is not needed here, and `yolox_s.pth` not a checkpoint file, it only contains model state.
