### ISSUE TITLE
RuntimeError: Error building extension 'fast_cocoeval'

### ISSUE THREAD

**Issue by yjcreation** [Megvii-BaseDetection/YOLOX#1459]
Using C:\Users\15496\AppData\Local\torch_extensions\torch_extensions\Cache\py37_cu113 as PyTorch extensions root...
Emitting ninja build file C:\Users\15496\AppData\Local\torch_extensions\torch_extensions\Cache\py37_cu113\fast_cocoeval\build.ninja...
Building extension module fast_cocoeval...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64/link.exe" cocoeval.o /nologo /DLL c10.lib torch_cpu.lib torch.lib /LIBPATH:D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\F\Anaconda3\envs\yolox\libs /out:fast_cocoeval.pyd
FAILED: fast_cocoeval.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64/link.exe" cocoeval.o /nologo /DLL c10.lib torch_cpu.lib torch.lib /LIBPATH:D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\F\Anaconda3\envs\yolox\libs /out:fast_cocoeval.pyd
LINK : fatal error LNK1104: 无法打开文件“fast_cocoeval.pyd”
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\utils\cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "D:\F\Anaconda3\envs\yolox\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pywork\3.debug\YOLOX\yolox\layers\__init__.py", line 11, in <module>
    from .fast_coco_eval_api import COCOeval_opt
  File "D:\pywork\3.debug\YOLOX\yolox\layers\fast_coco_eval_api.py", line 17, in <module>
    FastCOCOEvalOp().jit_load()
  File "D:\pywork\3.debug\YOLOX\yolox\layers\jit_ops.py", line 107, in jit_load
    verbose=verbose,
  File "D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\utils\cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "D:\F\Anaconda3\envs\yolox\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fast_cocoeval'

**Comment by nomurakeiya** [comment]
@yjcreation 
I have the similer error "Error building extension 'fast_cocoeval'"
This error occuers when I try to Training. (doesn't happen only detection with pretrained models.)

I need help. thanks.

**Comment by ComplateLin** [comment]
请问您解决了么

**Comment by bc-arl** [comment]
I also have this error. Any solution?
