### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox-m'

### ISSUE THREAD

**Issue by kadirnar** [Megvii-BaseDetection/YOLOX#1478]
Hi @FateScript ,

I am writing inference code using pip version.(custom model)
```
from yolox.exp import get_exp

exp_file = 'yolox-m'
get_exp(exp_file, None)
```
Error Message:
```
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox-m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/kadir/Desktop/github/sahi/yolox_pred.py", line 22, in <module>
    get_exp(exp_file, None)
  File "C:\Users\kadir\miniconda3\envs\sahi_gpu\lib\site-packages\yolox\exp\build.py", line 40, in get_exp
    return get_exp_by_file(exp_file)
  File "C:\Users\kadir\miniconda3\envs\sahi_gpu\lib\site-packages\yolox\exp\build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: yolox-m doesn't contains class named 'Exp'
```

**Comment by kadirnar** [comment]
```
from yolox.exp import get_exp

exp_file = 'yolox-m.py'
get_exp(exp_file, None)
```
