### ISSUE TITLE
我在进行TensorRT模型转换的时候遇到了以下问题

### ISSUE THREAD

**Issue by zjnyly** [Megvii-BaseDetection/YOLOX#148]
```
zjnyly@zjnyly:~/Downloads/YOLOX$ python3 tools/trt.py -n yolox-s -c yolox_s.pth.tar
Traceback (most recent call last):
  File "tools/trt.py", line 14, in <module>
    from yolox.exp import get_exp
  File "/home/zjnyly/Downloads/YOLOX/yolox/__init__.py", line 6, in <module>
    configure_module()
  File "/home/zjnyly/Downloads/YOLOX/yolox/utils/setup_env.py", line 39, in configure_module
    resource.setrlimit(resource.RLIMIT_NOFILE, (ulimit_value, rlimit[1]))
ValueError: current limit exceeds maximum limit
```
请问这是什么原因?我把ulimit_value设置到很大也不行

**Comment by zjnyly** [comment]
如果我注释掉出现问题的代码，程序运行以后会出现如下问题
```
zjnyly@zjnyly:~/Downloads/YOLOX$ python3 tools/trt.py -n yolox-s -c yolox_s.pth.tar
2021-07-26 14:15:26.427 | INFO     | __main__:main:52 - loaded checkpoint done.
/home/zjnyly/.local/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
[TensorRT] WARNING: Tensor DataType is determined at build time for tensors not marked as input or output.
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.3.0 but loaded cuBLAS/cuBLAS LT 11.2.1
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
2021-07-26 14:15:58.216 | ERROR    | __main__:<module>:77 - An error has been caught in function '<module>', process 'MainProcess' (19484), thread 'MainThread' (139834672400192):
Traceback (most recent call last):

> File "tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7f2ceff79840>

  File "tools/trt.py", line 64, in main
    torch.save(model_trt.state_dict(), os.path.join(file_name, 'model_trt.pth'))
    │     │    │         │             │  │    │    └ './YOLOX_outputs/yolox_s'
    │     │    │         │             │  │    └ <function join at 0x7f2dcbe81378>
    │     │    │         │             │  └ <module 'posixpath' from '/usr/lib/python3.6/posixpath.py'>
    │     │    │         │             └ <module 'os' from '/usr/lib/python3.6/os.py'>
    │     │    │         └ <function Module.state_dict at 0x7f2cfe46d510>
    │     │    └ TRTModule()
    │     └ <function save at 0x7f2d2db66048>
    └ <module 'torch' from '/home/zjnyly/.local/lib/python3.6/site-packages/torch/__init__.py'>

  File "/home/zjnyly/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1261, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
                  │    │     │            │       └ {'version': 1}
                  │    │     │            └ ''
                  │    │     └ OrderedDict()
                  │    └ TRTModule()
                  └ <function TRTModule._on_state_dict at 0x7f2cfdbc46a8>

  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 436, in _on_state_dict
    state_dict[prefix + "engine"] = bytearray(self.engine.serialize())
    │          │                              │    └ None
    │          │                              └ TRTModule()
    │          └ ''
    └ OrderedDict()

AttributeError: 'NoneType' object has no attribute 'serialize'

```

**Comment by ruinmessi** [comment]
#97

**Comment by FateScript** [comment]
Long time no update, close this issue.
