### ISSUE TITLE
How to train on windows10?

### ISSUE THREAD

**Issue by LLsmile** [Megvii-BaseDetection/YOLOX#1484]
Requirements cannot be installed on windows 10.

**Comment by LLsmile** [comment]
Not all dependencies can be installed rightly on Windows 10, such as apex and pycocotools. Apex for python is installed by official guideline, `pip install -v --no-cache-dir .`. And pycocotools is windows version in `https://github.com/philferriere/cocoapi`. Besides, yolox is not built perfectly with error message：
`Using pip 22.2.2 from C:\02_software\anaconda\lib\site-packages\pip (python 3.9)
Obtaining file:///C:/03_workspace/05_repo/xyz-object-detection-yolox
  Running command python setup.py egg_info
  running egg_info
  creating C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info
  writing C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\PKG-INFO
  writing dependency_links to C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\dependency_links.txt
  writing top-level names to C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\top_level.txt
  writing manifest file 'C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\liaolin\AppData\Local\Temp\pip-pip-egg-info-hd29bj3e\yolox.egg-info\SOURCES.txt'
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\02_software\anaconda\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  Preparing metadata (setup.py) ... done
Installing collected packages: yolox
  Attempting uninstall: yolox
    Found existing installation: yolox 0.1.0
    Uninstalling yolox-0.1.0:
      Removing file or directory c:\02_software\anaconda\lib\site-packages\yolox.egg-link
      Removing pth entries from c:\02_software\anaconda\lib\site-packages\easy-install.pth:
      Removing entry: c:\03_workspace\05_repo\xyz-object-detection-yolox
      Successfully uninstalled yolox-0.1.0
  Running setup.py develop for yolox
    Running command python setup.py develop
    running develop
    C:\02_software\anaconda\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    C:\02_software\anaconda\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing yolox.egg-info\PKG-INFO
    writing dependency_links to yolox.egg-info\dependency_links.txt
    writing top-level names to yolox.egg-info\top_level.txt
    reading manifest file 'yolox.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'yolox.egg-info\SOURCES.txt'
    running build_ext
    C:\02_software\anaconda\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'yolox._C' extension
    Emitting ninja build file C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\02_software\anaconda\lib\site-packages\torch\lib /LIBPATH:C:\02_software\anaconda\libs /LIBPATH:C:\02_software\anaconda /LIBPATH:C:\02_software\anaconda\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\03_workspace\05_repo\xyz-object-detection-yolox\yolox\layers\csrc\cocoeval\cocoeval.obj C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\03_workspace\05_repo\xyz-object-detection-yolox\yolox\layers\csrc\vision.obj /OUT:build\lib.win-amd64-3.9\yolox\_C.cp39-win_amd64.pyd /IMPLIB:C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\03_workspace\05_repo\xyz-object-detection-yolox\yolox\layers\csrc\cocoeval\_C.cp39-win_amd64.lib
       Creating library C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\03_workspace\05_repo\xyz-object-detection-yolox\yolox\layers\csrc\cocoeval\_C.cp39-win_amd64.lib and object C:\03_workspace\05_repo\xyz-object-detection-yolox\build\temp.win-amd64-3.9\Release\03_workspace\05_repo\xyz-object-detection-yolox\yolox\layers\csrc\cocoeval\_C.cp39-win_amd64.exp
    Generating code
    Finished generating code
    copying build\lib.win-amd64-3.9\yolox\_C.cp39-win_amd64.pyd -> yolox
    Creating c:\02_software\anaconda\lib\site-packages\yolox.egg-link (link to .)
    Adding yolox 0.1.0 to easy-install.pth file

    Installed c:\03_workspace\05_repo\xyz-object-detection-yolox
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\02_software\anaconda\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
Successfully installed yolox-0.1.0`

**Comment by FateScript** [comment]
Apex is not needed anymore. For pycocotools, how about [pycocotools windows](https://pypi.org/project/pycocotools-windows/) ?
