### ISSUE TITLE
No module named 'yolox_s'  and  exps/example/custom/yolox_s.py doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by flyingfish7777** [Megvii-BaseDetection/YOLOX#1536]
windows下使用pycharm，python解释器部署在SSH linux 服务器上， 运行train.py会出现以下错误
 
 **### **Traceback (most recent call last):
  File "/data3/xxx_dataset/YOLOX-main/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/home/xxx/anaconda3/envs/yolox/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data3/xxx_dataset/YOLOX-main/tools/train.py", line 125, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/data3/xxx_dataset/YOLOX-main/yolox/exp/build.py", line 40, in get_exp
    return get_exp_by_file(exp_file)
  File "/data3/xxx_dataset/YOLOX-main/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: exps/example/custom/yolox_s.py doesn't contains class named 'Exp'****

如果在linux服务器上通过命令行运行，则不会出现这个问题。

windows端以及linux端均已执行pip3 install -v -e . 并且成功。通过pych的linux解释器，运行其他网络比如yolov5等均正常运行。

**Comment by YinZhang98** [comment]
请问解决了吗

**Comment by flyingfish7777** [comment]
> 

很遗憾，这种部署的方法好像确实行不通。
所以我用pych  的远程开发模式连接这个项目了，这个问题就解决了

**Comment by xiaomaofeng** [comment]
try add `sys.path.append('/root/your code path')` in the train.py

**Comment by realfanyujun** [comment]
I also encountered this issue and here is how I solved:
comment this line in `train.py`:
https://github.com/Megvii-BaseDetection/YOLOX/blob/ac58e0a5e68e57454b7b9ac822aced493b553c53/tools/train.py#L124C5-L124C44
Simply copy the codes in `yolox/exp/build.py` to the place in `train.py` where the above code is commented:
https://github.com/Megvii-BaseDetection/YOLOX/blob/ac58e0a5e68e57454b7b9ac822aced493b553c53/yolox/exp/build.py#L12C1-L14C32

**Comment by MrGuess024** [comment]
I solved this issue by running the setup.py file once.
