### ISSUE TITLE
KeyError：‘label’

### ISSUE THREAD

**Issue by Zzzxi** [Megvii-BaseDetection/YOLOX#1551]
(yolox) E:\Deep learning\YOLOX-main>python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 1 -c weights/yolox_s.pth
2022-11-03 11:22:16 | INFO     | yolox.core.trainer:130 - args: Namespace(batch_size=1, cache=False, ckpt='weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='
exps/example/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=False, logger='tensorboard', machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, s
tart_epoch=None)
2022-11-03 11:22:16 | INFO     | yolox.core.trainer:131 - exp value:
╒═══════════════════╤════════════════════════════╕
│ keys              │ values                     │
╞═══════════════════╪════════════════════════════╡
│ seed              │ None                       │
├───────────────────┼────────────────────────────┤
│ output_dir        │ './YOLOX_outputs'          │
├───────────────────┼────────────────────────────┤
│ print_interval    │ 10                         │
├───────────────────┼────────────────────────────┤
│ eval_interval     │ 10                         │
├───────────────────┼────────────────────────────┤
│ num_classes       │ 1                          │
├───────────────────┼────────────────────────────┤
│ depth             │ 0.33                       │
├───────────────────┼────────────────────────────┤
│ width             │ 0.5                        │
├───────────────────┼────────────────────────────┤
│ act               │ 'silu'                     │
├───────────────────┼────────────────────────────┤
│ data_num_workers  │ 0                          │
├───────────────────┼────────────────────────────┤
│ input_size        │ (640, 640)                 │
├───────────────────┼────────────────────────────┤
│ multiscale_range  │ 5                          │
├───────────────────┼────────────────────────────┤
│ data_dir          │ None                       │
├───────────────────┼────────────────────────────┤
│ train_ann         │ 'instances_train2017.json' │
├───────────────────┼────────────────────────────┤
│ val_ann           │ 'instances_val2017.json'   │
├───────────────────┼────────────────────────────┤
│ test_ann          │ 'instances_test2017.json'  │
├───────────────────┼────────────────────────────┤
│ mosaic_prob       │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ mixup_prob        │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ hsv_prob          │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ flip_prob         │ 0.5                        │
├───────────────────┼────────────────────────────┤
│ degrees           │ 10.0                       │
├───────────────────┼────────────────────────────┤
│ translate         │ 0.1                        │
├───────────────────┼────────────────────────────┤
│ mosaic_scale      │ (0.1, 2)                   │
├───────────────────┼────────────────────────────┤
│ enable_mixup      │ True                       │
├───────────────────┼────────────────────────────┤
│ mixup_scale       │ (0.5, 1.5)                 │
├───────────────────┼────────────────────────────┤
│ shear             │ 2.0                        │
├───────────────────┼────────────────────────────┤
│ warmup_epochs     │ 1                          │
├───────────────────┼────────────────────────────┤
│ max_epoch         │ 300                        │
├───────────────────┼────────────────────────────┤
│ warmup_lr         │ 0                          │
├───────────────────┼────────────────────────────┤
│ min_lr_ratio      │ 0.05                       │
├───────────────────┼────────────────────────────┤
│ basic_lr_per_img  │ 0.00015625                 │
├───────────────────┼────────────────────────────┤
│ scheduler         │ 'yoloxwarmcos'             │
├───────────────────┼────────────────────────────┤
│ no_aug_epochs     │ 15                         │
├───────────────────┼────────────────────────────┤
│ ema               │ True                       │
├───────────────────┼────────────────────────────┤
│ weight_decay      │ 0.0005                     │
├───────────────────┼────────────────────────────┤
│ momentum          │ 0.9                        │
├───────────────────┼────────────────────────────┤
│ save_history_ckpt │ True                       │
├───────────────────┼────────────────────────────┤
│ exp_name          │ 'yolox_voc_s'              │
├───────────────────┼────────────────────────────┤
│ test_size         │ (640, 640)                 │
├───────────────────┼────────────────────────────┤
│ test_conf         │ 0.01                       │
├───────────────────┼────────────────────────────┤
│ nmsthre           │ 0.65                       │
╘═══════════════════╧════════════════════════════╛
2022-11-03 11:22:16 | INFO     | yolox.core.trainer:136 - Model Summary: Params: 8.94M, Gflops: 26.76
2022-11-03 11:22:16 | INFO     | yolox.core.trainer:311 - loading checkpoint for fine tuning
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.0.weight in mode
l is torch.Size([1, 128, 1, 1]).
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size
([1]).
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.1.weight in mode
l is torch.Size([1, 128, 1, 1]).
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size
([1]).
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.2.weight in mode
l is torch.Size([1, 128, 1, 1]).
2022-11-03 11:22:17 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size
([1]).
2022-11-03 11:22:18 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (6916), thread 'MainThread' (6672):
Traceback (most recent call last):

  File "tools\train.py", line 138, in <module>
    launch(
    └ <function launch at 0x00000283755809D0>

> File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000028373588310>

  File "tools\train.py", line 122, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000028376AE5310>
    └ <yolox.core.trainer.Trainer object at 0x0000028376AF2190>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x0000028376AE5AF0>
    └ <yolox.core.trainer.Trainer object at 0x0000028376AF2190>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\trainer.py", line 149, in before_train
    self.train_loader = self.exp.get_data_loader(
    │                   │    │   └ <function Exp.get_data_loader at 0x0000028376AEF820>
    │                   │    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │                   └ <yolox.core.trainer.Trainer object at 0x0000028376AF2190>
    └ <yolox.core.trainer.Trainer object at 0x0000028376AF2190>

  File "E:\Deep learning\YOLOX-main\exps/example/yolox_voc\yolox_voc_s.py", line 44, in get_data_loader
    dataset = VOCDetection(
              └ <class 'yolox.data.datasets.voc.VOCDetection'>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 131, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function VOCDetection._load_coco_annotations at 0x0000028376ADF3A0>
    │                  └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>
    └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 140, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in range(len(self.ids))]
            │    │                                              │    └ [('./datasets/VOCdevkit\\VOC2007', '1'), ('./datasets/VOCdevkit\\VOC2007', '10'), ('./datasets/VOCdevkit\\VOC2007',
 '100'), (...
            │    │                                              └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>
            │    └ <function VOCDetection.load_anno_from_ids at 0x0000028376ADF4C0>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 140, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in range(len(self.ids))]
            │    │                  │         │                 │    └ [('./datasets/VOCdevkit\\VOC2007', '1'), ('./datasets/VOCdevkit\\VOC2007', '10'), ('./datasets/VOCdevkit\\VOC2007',
 '100'), (...
            │    │                  │         │                 └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>
            │    │                  │         └ 0
            │    │                  └ 0
            │    └ <function VOCDetection.load_anno_from_ids at 0x0000028376ADF4C0>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 196, in load_anno_from_ids
    res, img_info = self.target_transform(target)
                    │    │                └ <Element 'annotation' at 0x000002837FD11C20>
                    │    └ <yolox.data.datasets.voc.AnnotationTransform object at 0x0000028376A21910>
                    └ <yolox.data.datasets.voc.VOCDetection object at 0x000002837FF2CFD0>

  File "E:\Environment\Anaconda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 71, in __call__
    label_idx = self.class_to_ind[name]
                │    │            └ 'buds'
                │    └ {'b': 0, 'u': 1, 'd': 2, 's': 3}
                └ <yolox.data.datasets.voc.AnnotationTransform object at 0x0000028376A21910>

KeyError: 'buds'

The tag name and the category name are the same, why is the error still wrong？

**Comment by Joker316701882** [comment]
This is caused by the inappropriate organization of your dataset. Please check your dataset carefully.
