### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable on PyTorch1.13

### ISSUE THREAD

**Issue by hlahkar** [Megvii-BaseDetection/YOLOX#1559]
Caught runtime error as below:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 100, in rebuild_tensor
    t = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 147, in _rebuild_tensor
    return t.set_(storage.untyped(), storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable

Note : issue is not reproducible on executing with Pytorch 1.12

**Comment by waragai-katsunori** [comment]
I got similar runtime error when I tried custom model training.
I'm still wondering why.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: Trying to resize storage that is not resizable

```

pytorch version
pytorch-quantization    2.1.2
torch                   1.14.0a0+410ce96
torch-tensorrt          1.3.0a0
torchtext               0.13.0a0+fae8e8c
torchvision             0.15.0a0

**Comment by StrugglingForBetter** [comment]
I got the same error. It looks really strange because it will report this error randomly. For the same dataset, it will sometimes throw this error but sometimes works fine

**Comment by balabooooo** [comment]
Same error in my 4090 with pytorch1.13.1+cuda11.6. But it works well with pytorch2.1.1+cuda11.8.
