### ISSUE TITLE
Mismatch of classes in example

### ISSUE THREAD

**Issue by VanIseghemThomas** [Megvii-BaseDetection/YOLOX#1603]
Using the [mini-coco128](https://drive.google.com/file/d/16N3u36ycNd70m23IM7vMuRQXejAJY9Fs/view?usp=sharing) dataset.

When trying to train a `yolox_s` model using `exps/example/custom/yolox_s.py` and the pretrained [`yolo_s`](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth) weights from this repository, you will get a mismatch in classes:

```
Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([71, 128, 1, 1]).
```

This means that the pretrained weights contain 80 classes and the example defines 71 if I understand correctly.

**Comment by VanIseghemThomas** [comment]
The documentation states the following: *(Don't worry for the different shape of detection head between the pretrained weights and your own model, we will handle it)*

But when running:

```
python tools/demo.py image -n yolox-s -c YOLOX_outputs/yolox_s/best_ckpt.pth --path assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result
```
It goes in error:

```console
2023-02-02 10:45:07.028 | INFO     | __main__:main:259 - Args: Namespace(camid=0, ckpt='YOLOX_outputs/yolox_s/best_ckpt.pth', conf=0.3, demo='image', device='cpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.65, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)
2023-02-02 10:45:07.205 | INFO     | __main__:main:269 - Model Summary: Params: 8.97M, Gflops: 26.93
2023-02-02 10:45:07.206 | INFO     | __main__:main:282 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo.py", line 320, in <module>
    main(exp, args)
  File "tools/demo.py", line 285, in main
    model.load_state_dict(ckpt["model"])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).
```

**Comment by VanIseghemThomas** [comment]
When creating a custom exp class that defines 71 classes:

```python
import os
from yolox.exp import Exp as MyExp

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.33
        self.width = 0.50
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        # Define yourself dataset path
        self.data_dir = "datasets/coco128"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.num_classes = 80

        self.max_epoch = 300
        self.data_num_workers = 4
        self.eval_interval = 1
```

I get the following when starting to train:

```
2023-02-02 11:05:07 | INFO     | yolox.core.trainer:204 - ---> start train epoch1
2023-02-02 11:05:14 | INFO     | yolox.core.trainer:359 - Save weights to ./YOLOX_outputs/yolox_mini-coco128
  0%|          | 0/1 [00:00<?, ?it/s]
2023-02-02 11:05:15 | INFO     | yolox.core.trainer:197 - Training of experiment is done and the best AP is 0.00
2023-02-02 11:05:15 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (120), thread 'MainThread' (139833743483072):
Traceback (most recent call last):

  File "tools/train.py", line 144, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=None, ckpt='weights/yolox_s.pth', devices=None, dist_backend='nccl', dist_url=None, exp_file='...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/workspace/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f2d938bb5f0>

  File "tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f2c6e4184d0>
    └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 77, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f2c6d6f7d40>
    └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 87, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f2c6d6ff170>
    └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 223, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f2c6d6ff440>
    └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 332, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed, return_outputs=True
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f2c9ddba290>
    │          └ <yolox.core.trainer.Trainer object at 0x7f2c6d6fe810>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/workspace/YOLOX/yolox/exp/yolox_base.py", line 351, in eval
    return evaluator.evaluate(model, is_distributed, half, return_outputs=return_outputs)
           │         │        │      │               │                    └ True
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7f2c6d774a70>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f2c9ddba290>

  File "/workspace/YOLOX/yolox/evaluators/coco_evaluator.py", line 185, in evaluate
    outputs, info_imgs, ids, return_outputs=True)
    │        │          └ tensor([[1],
    │        │                    [2],
    │        │                    [3],
    │        │                    [4],
    │        │                    [5]])
    │        └ [tensor([480, 426, 428, 425, 640]), tensor([640, 640, 640, 640, 481])]
    └ [tensor([[ 3.0547e+02, -1.2206e+00,  6.2913e+02,  2.4346e+02,  9.6804e-01,
                9.5160e-01,  4.5000e+01],
              [ 4.02...

  File "/workspace/YOLOX/yolox/evaluators/coco_evaluator.py", line 230, in convert_to_coco_format
    for ind in range(bboxes.shape[0])
        │            │      └ <attribute 'shape' of 'torch._C._TensorBase' objects>
        │            └ tensor([[ 2.4058e+02,  1.5456e+02,  4.0707e+02,  3.5266e+02],
        │                      [ 2.0448e+02,  2.9751e+01,  4.6065e+02,  3.4796e+02],
        │               ...
        └ 4

  File "/workspace/YOLOX/yolox/evaluators/coco_evaluator.py", line 230, in <listcomp>
    for ind in range(bboxes.shape[0])
        └ 0

IndexError: list index out of range
```

**Comment by FateScript** [comment]
@VanIseghemThomas `-n yolox-s` is only used for standard coco training. If you are using custom training, plz use `-f path/to/your/exp.py` instead.
Thanks for reminding, we should document it in our documentation.

**Comment by VanIseghemThomas** [comment]
Hi @FateScript, isn't the dataset I provided standard COCO training?

**Comment by FateScript** [comment]
mini coco 128 is not the standard coco dataset.

**Comment by mahnehsilla** [comment]
Same error here, I dont really know what is the right path, tried loading the custom, etc.

**Comment by VanIseghemThomas** [comment]
@mahnehsilla 

> Problem turned out to be the `-n yolox-s` flag. This should be `-f exps/example/custom/yolox_s.py `. This is an error in the documentation.

This is the solution.

**Comment by mahnehsilla** [comment]
Yes, i thought the problem was not using -f but also using the default path is. That was solved, idk why my data still wont run. I get the "object has no cache property"
