### ISSUE TITLE
Training and eval have the same error. Never had before

### ISSUE THREAD

**Issue by BWWwustl** [Megvii-BaseDetection/YOLOX#1610]
2023-02-17 05:47:39 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (10524), thread 'MainThread' (140690787772224):
Traceback (most recent call last):

  File "tools/train.py", line 137, in <module>
    launch(
    └ <function launch at 0x7ff49f6b5310>

> File "/content/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff4906bdc10>

  File "tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7ff48c2e5670>
    └ <yolox.core.trainer.Trainer object at 0x7ff48c2f0580>

  File "/content/YOLOX/yolox/core/trainer.py", line 75, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7ff48c2ee040>
    └ <yolox.core.trainer.Trainer object at 0x7ff48c2f0580>

  File "/content/YOLOX/yolox/core/trainer.py", line 157, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7ff46ed62d00>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7ff48c2f0580>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7ff48c2f0580>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7ff48fcf5790>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff46ed62df0>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff46ed62af0>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff46ed62df0>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff46ed62df0>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff46ed62df0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7ff49fd264c0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff46ed62af0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7ff480014e20>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7ff49fd265e0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff46ed62af0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7ff52010a040>
    └ <torch._utils.ExceptionWrapper object at 0x7ff480014e20>

  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
          └ TypeError('Caught TypeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/usr/local/...

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 120, in wrapper
    ret_val = getitem_fn(self, index)
  File "/content/YOLOX/yolox/data/datasets/mosaicdetection.py", line 93, in __getitem__
    img, _labels, _, img_id = self._dataset.pull_item(index)
  File "/content/YOLOX/yolox/data/datasets/voc.py", line 208, in pull_item
    img = self.read_img(index)
TypeError: decorator() takes 1 positional argument but 2 were given

**Comment by menglongyue** [comment]
i have the same problem, have you solved it?

**Comment by ianpundar** [comment]
We have fixed this bug in #1615, plz pull the latest code

**Comment by BWWwustl** [comment]
> i have the same problem, have you solved it?

They fixed the bug. I think we could try the latest version

**Comment by menglongyue** [comment]
ok，thanks for you guys
