### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Hahahdamowang** [Megvii-BaseDetection/YOLOX#1619]
请问大家这个应该怎么修改呀？
File "/home/ubuntu/Project/YOLOX-main/yolox/data/datasets/voc.py", line 140, in <listcomp>
    for i in range(self.num_imgs)
        │          │    └ 1620
        │          └ <yolox.data.datasets.voc.VOCDetection object at 0x7f8cd80be2b0>
        └ 0

IndexError: list index out of range
Exception ignored in: <bound method CacheDataset.__del__ of <yolox.data.datasets.voc.VOCDetection object at 0x7f8cd80be2b0>>
Traceback (most recent call last):
  File "/home/ubuntu/Project/YOLOX-main/yolox/data/datasets/datasets_wrapper.py", line 177, in __del__
    if self.cache and self.cache_type == "ram":
AttributeError: 'VOCDetection' object has no attribute 'cache'

**Comment by xiaohuhuhuhu-code** [comment]
我也遇到这个，不知道怎么改了
