### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jc000222** [Megvii-BaseDetection/YOLOX#1645]
Can anyone help me with this?
有人知道这是为什么吗TAT

Traceback (most recent call last):
  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\datasets_wrapper.py", line 177, in __del__
 | **E****RROR       if self.cache and self.cache_type == "ram":
 | AttributeError: 'VOCDetection' object has no attribute 'cache'
yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (34924), thread 'MainThread' (2904):**
Traceback (most recent call last):

  File "tools\train.py", line 137, in <module>
    launch(
    └ <function launch at 0x0000019BEE849280>

> File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000019BECFB9AF0>

  File "tools\train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000019BF5FC7B80>
    └ <yolox.core.trainer.Trainer object at 0x0000019BF5FCE2B0>

  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x0000019BF5FD0700>
    └ <yolox.core.trainer.Trainer object at 0x0000019BF5FCE2B0>

  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\core\trainer.py", line 149, in before_train
    self.train_loader = self.exp.get_data_loader(
    │                   │    │   └ <function Exp.get_data_loader at 0x0000019BF5FC7F70>
    │                   │    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │                   └ <yolox.core.trainer.Trainer object at 0x0000019BF5FCE2B0>
    └ <yolox.core.trainer.Trainer object at 0x0000019BF5FCE2B0>

  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\exp\yolox_base.py", line 180, in get_data_loader
    self.dataset = self.get_dataset(cache=False, cache_type=cache_img)
    │    │         │    │                                   └ None
    │    │         │    └ <function Exp.get_dataset at 0x0000019BF5FD4280>
    │    │         └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │    └ None
    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "exps/example/yolox_voc\yolox_voc_s.py", line 27, in get_dataset
    return VOCDetection(
           └ <class 'yolox.data.datasets.voc.VOCDetection'>

  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 137, in __init__
    path_filename = [

  File "D:\conda\envs\yolox\lib\site-packages\yolox-0.3.0-py3.8.egg\yolox\data\datasets\voc.py", line 138, in <listcomp>
    (self._imgpath % self.ids[i]).split(self.root + "/")[1]
     │    │          │    │   │         │    └ 'D:/lowlight/YOLOX-main/datasets/VOC/VOCdevkit'
     │    │          │    │   │         └ <yolox.data.datasets.voc.VOCDetection object at 0x0000019B89469F70>
     │    │          │    │   └ 0
     │    │          │    └ [('D:/lowlight/YOLOX-main/datasets/VOC/VOCdevkit\\VOC2007', '2015_00002'), ('D:/lowlight/YOLOX-main/datasets/VOC/VOCdevkit\\V...
     │    │          └ <yolox.data.datasets.voc.VOCDetection object at 0x0000019B89469F70>
     │    └ '%s\\JPEGImages\\%s.jpg'
     └ <yolox.data.datasets.voc.VOCDetection object at 0x0000019B89469F70>

**IndexError: list index out of range**

**Comment by lqqyyy** [comment]
将YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1]  修改为 (self._imgpath % self.ids[i]).split(self.root + "\\")[1]

**Comment by lqqyyy** [comment]
将 YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1] 修改为 (self._imgpath % self .ids[i]).split(self.root + "\\")[1]

**Comment by lqqyyy** [comment]
将 YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1] 修改为 (self._imgpath % self .ids[i]).split(self.root + "两个\")[1]

**Comment by lqqyyy** [comment]
将 YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1] 修改为 (self._imgpath % self .ids[i]).split(self.root + "两个\\")[1]

**Comment by lqqyyy** [comment]
将 YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1] 修改为 (self._imgpath % self .ids[i]).split(self.root + "\\\\")[1]

**Comment by jc000222** [comment]
> 

谢谢！就是这里的问题改完就没错了！！

**Comment by niceday-hh** [comment]
解决了我的问题，谢谢！

**Comment by PJPomPom** [comment]
太感谢了，困扰了我一天！

**Comment by CoffeeinTeaC** [comment]
> 将 YOLOX-main/yolox/data/datasets/voc.py 文件的 (self._imgpath % self.ids[i]).split(self.root + "/")[1] 修改为 (self._imgpath % self .ids[i]).split(self.root + "\\")[1]

但如果我用的是coco格式的训练，但是有时候会报错IndexError: list index out of range
有时候又不会，我的训练命令是python3 train.py --cache
