### ISSUE TITLE
YOLOX train error

### ISSUE THREAD

**Issue by SliverAward** [Megvii-BaseDetection/YOLOX#1660]
I'm getting an error during YOLOX training,
2023-05-05 13:10:48 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.stems.2.bn.running_var in checkpoint is torch.Size([64]), while shape of head.stems.2.bn.running_var in model is torch.Size([128]).
2023-05-05 13:10:49 | Exception ignored in: <function CacheDataset.__del__ at 0x000002027FE7C940>
Traceback (most recent call last):
ERROR     File "c:\yolox\yolox\data\datasets\datasets_wrapper.py", line 177, in __del__
 |     if self.cache and self.cache_type == "ram":
yolox.core.launchAttributeError: 'VOCDetection' object has no attribute 'cache'
:98 - An error has been caught in function 'launch', process 'MainProcess' (25748), thread 'MainThread' (348):
Traceback (most recent call last):

  File "C:\YOLOX\tools\train.py", line 138, in <module>
    launch(
    └ <function launch at 0x00000202749B9DC0>

> File "c:\yolox\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x00000202762C0820>

  File "C:\YOLOX\tools\train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002027FED05E0>
    └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>

  File "c:\yolox\yolox\core\trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000002027FED6040>
    └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>

  File "c:\yolox\yolox\core\trainer.py", line 149, in before_train
    self.train_loader = self.exp.get_data_loader(
    │                   │    │   └ <function Exp.get_data_loader at 0x000002027FED08B0>
    │                   │    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │                   └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>
    └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>

  File "c:\yolox\yolox\exp\yolox_base.py", line 181, in get_data_loader
    self.dataset = self.get_dataset(cache=False, cache_type=cache_img)
    │    │         │    │                                   └ None
    │    │         │    └ <function Exp.get_dataset at 0x000002027FED6B80>
    │    │         └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    │    └ None
    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "C:\YOLOX\exps/example/yolox_voc\yolox_voc_s.py", line 27, in get_dataset
    return VOCDetection(
           └ <class 'yolox.data.datasets.voc.VOCDetection'>

  File "c:\yolox\yolox\data\datasets\voc.py", line 135, in __init__
    self.annotations = self._load_coco_annotations()
    │                  │    └ <function VOCDetection._load_coco_annotations at 0x000002027FEC9700>
    │                  └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
    └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>

  File "c:\yolox\yolox\data\datasets\voc.py", line 155, in _load_coco_annotations
    return [self.load_anno_from_ids(_ids) for _ids in range(self.num_imgs)]
            │    │                                          │    └ 2160
            │    │                                          └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
            │    └ <function VOCDetection.load_anno_from_ids at 0x000002027FEC9790>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>

  File "c:\yolox\yolox\data\datasets\voc.py", line 155, in <listcomp>
    return [self.load_anno_from_ids(_ids) for _ids in range(self.num_imgs)]
            │    │                  │         │             │    └ 2160
            │    │                  │         │             └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
            │    │                  │         └ 1
            │    │                  └ 1
            │    └ <function VOCDetection.load_anno_from_ids at 0x000002027FEC9790>
            └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>

  File "c:\yolox\yolox\data\datasets\voc.py", line 159, in load_anno_from_ids
    target = ET.parse(self._annopath % img_id).getroot()
             │  │     │    │           └ ('c:\\yolox\\datasets\\VOCdevkit\\VOC2007', 'C:\\YOLOX\\datasets\\VOCdevkit\\VOC2007\\Annotations\\20230328_155554_jpg.rf.0f0...
             │  │     │    └ '%s\\Annotations\\%s.xml'
             │  │     └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
             │  └ <function parse at 0x0000020274A454C0>
             └ <module 'xml.etree.ElementTree' from 'C:\\ProgramData\\Anaconda3\\lib\\xml\\etree\\ElementTree.py'>

  File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
    │    │     │       └ None
    │    │     └ 'c:\\yolox\\datasets\\VOCdevkit\\VOC2007\\Annotations\\C:\\YOLOX\\datasets\\VOCdevkit\\VOC2007\\Annotations\\20230328_155554_...
    │    └ <function ElementTree.parse at 0x0000020274A42550>
    └ <xml.etree.ElementTree.ElementTree object at 0x0000020209C8FCD0>

  File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
                  └ 'c:\\yolox\\datasets\\VOCdevkit\\VOC2007\\Annotations\\C:\\YOLOX\\datasets\\VOCdevkit\\VOC2007\\Annotations\\20230328_155554_...

OSError: [Errno 22] Invalid argument: 'c:\\yolox\\datasets\\VOCdevkit\\VOC2007\\Annotations\\C:\\YOLOX\\datasets\\VOCdevkit\\VOC2007\\Annotations\\20230328_155554_jpg.rf.0f0f7b9835d0196f27072c5a890f476c.xml.xml'

and it seems to be related to a path issue.

Could you please help me with this?

**Comment by SliverAward** [comment]
> I'm getting an error during YOLOX training, 2023-05-05 13:10:48 | WARNING | yolox.utils.checkpoint:24 - Shape of head.stems.2.bn.running_var in checkpoint is torch.Size([64]), while shape of head.stems.2.bn.running_var in model is torch.Size([128]). 2023-05-05 13:10:49 | Exception ignored in: <function CacheDataset.**del** at 0x000002027FE7C940> Traceback (most recent call last): ERROR File "c:\yolox\yolox\data\datasets\datasets_wrapper.py", line 177, in **del** | if self.cache and self.cache_type == "ram": yolox.core.launchAttributeError: 'VOCDetection' object has no attribute 'cache' :98 - An error has been caught in function 'launch', process 'MainProcess' (25748), thread 'MainThread' (348): Traceback (most recent call last):
> 
> File "C:\YOLOX\tools\train.py", line 138, in launch( └ <function launch at 0x00000202749B9DC0>
> 
> > File "c:\yolox\yolox\core\launch.py", line 98, in launch
> > main_func(*args)
> > │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
> > └ <function main at 0x00000202762C0820>
> 
> File "C:\YOLOX\tools\train.py", line 118, in main trainer.train() │ └ <function Trainer.train at 0x000002027FED05E0> └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>
> 
> File "c:\yolox\yolox\core\trainer.py", line 74, in train self.before_train() │ └ <function Trainer.before_train at 0x000002027FED6040> └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>
> 
> File "c:\yolox\yolox\core\trainer.py", line 149, in before_train self.train_loader = self.exp.get_data_loader( │ │ │ └ <function Exp.get_data_loader at 0x000002027FED08B0> │ │ └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════... │ └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0> └ <yolox.core.trainer.Trainer object at 0x000002027FED97F0>
> 
> File "c:\yolox\yolox\exp\yolox_base.py", line 181, in get_data_loader self.dataset = self.get_dataset(cache=False, cache_type=cache_img) │ │ │ │ └ None │ │ │ └ <function Exp.get_dataset at 0x000002027FED6B80> │ │ └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════... │ └ None └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
> 
> File "C:\YOLOX\exps/example/yolox_voc\yolox_voc_s.py", line 27, in get_dataset return VOCDetection( └ <class 'yolox.data.datasets.voc.VOCDetection'>
> 
> File "c:\yolox\yolox\data\datasets\voc.py", line 135, in **init** self.annotations = self._load_coco_annotations() │ │ └ <function VOCDetection._load_coco_annotations at 0x000002027FEC9700> │ └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0> └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
> 
> File "c:\yolox\yolox\data\datasets\voc.py", line 155, in _load_coco_annotations return [self.load_anno_from_ids(_ids) for _ids in range(self.num_imgs)] │ │ │ └ 2160 │ │ └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0> │ └ <function VOCDetection.load_anno_from_ids at 0x000002027FEC9790> └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
> 
> File "c:\yolox\yolox\data\datasets\voc.py", line 155, in return [self.load_anno_from_ids(_ids) for _ids in range(self.num_imgs)] │ │ │ │ │ └ 2160 │ │ │ │ └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0> │ │ │ └ 1 │ │ └ 1 │ └ <function VOCDetection.load_anno_from_ids at 0x000002027FEC9790> └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0>
> 
> File "c:\yolox\yolox\data\datasets\voc.py", line 159, in load_anno_from_ids target = ET.parse(self._annopath % img_id).getroot() │ │ │ │ └ ('c:\yolox\datasets\VOCdevkit\VOC2007', 'C:\YOLOX\datasets\VOCdevkit\VOC2007\Annotations\20230328_155554_jpg.rf.0f0... │ │ │ └ '%s\Annotations\%s.xml' │ │ └ <yolox.data.datasets.voc.VOCDetection object at 0x000002020B8678B0> │ └ <function parse at 0x0000020274A454C0> └ <module 'xml.etree.ElementTree' from 'C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py'>
> 
> File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 1222, in parse tree.parse(source, parser) │ │ │ └ None │ │ └ 'c:\yolox\datasets\VOCdevkit\VOC2007\Annotations\C:\YOLOX\datasets\VOCdevkit\VOC2007\Annotations\20230328_155554_... │ └ <function ElementTree.parse at 0x0000020274A42550> └ <xml.etree.ElementTree.ElementTree object at 0x0000020209C8FCD0>
> 
> File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 569, in parse source = open(source, "rb") └ 'c:\yolox\datasets\VOCdevkit\VOC2007\Annotations\C:\YOLOX\datasets\VOCdevkit\VOC2007\Annotations\20230328_155554_...
> 
> OSError: [Errno 22] Invalid argument: 'c:\yolox\datasets\VOCdevkit\VOC2007\Annotations\C:\YOLOX\datasets\VOCdevkit\VOC2007\Annotations\20230328_155554_jpg.rf.0f0f7b9835d0196f27072c5a890f476c.xml.xml'
> 
> and it seems to be related to a path issue.
> 
> Could you please help me with this?

**Comment by SliverAward** [comment]
from glob import glob
import os
import random
import shutil

# Set up path
original_path = 'C:\\YOLOX\\datasets\\VOCdevkit'
img_files = glob(os.path.join(original_path, '*.jpg'))
ann_files = glob(os.path.join(original_path, '*.xml'))



# Set the directory path to copy and paste
img_save_path = os.path.join(original_path, 'VOC2007', 'JPEGImages')
ann_save_path = os.path.join(original_path, 'VOC2007', 'Annotations')

# Create a directory
os.makedirs(img_save_path, exist_ok=True)
os.makedirs(ann_save_path, exist_ok=True)

# Copy images and annotation files to the directory
for img_file in img_files:
    shutil.copy(img_file, img_save_path)

for ann_file in ann_files:
    shutil.copy(ann_file, ann_save_path)

#Set the file path to save the image file path
txt_save_path = os.path.join(original_path, 'VOC2007', 'ImageSets', 'Main')
os.makedirs(txt_save_path, exist_ok=True)

#Create index lists for train, val, trainval, and test datasets
total_xml = os.listdir(ann_save_path)
num = len(total_xml)
lst = range(num)
tv = int(num * 0.9)
tr = int(tv * 0.8)
trainval = random.sample(lst, tv)
train = random.sample(trainval, tr)

print("train and val size:", tv)
print("train size:", tr)

#Save the image file path and xml file path in the txt file
with open(os.path.join(txt_save_path, 'trainval.txt'), 'w') as ftrainval, \
     open(os.path.join(txt_save_path, 'train.txt'), 'w') as ftrain, \
     open(os.path.join(txt_save_path, 'val.txt'), 'w') as fval, \
     open(os.path.join(txt_save_path, 'test.txt'), 'w') as ftest:

    for i in lst:
        name = total_xml[i][:-4]
        if i in trainval:
            ftrainval.write(name + '\n')
            if i in train:
                ftrain.write(name + '\n')
            else:
                fval.write(name + '\n')
            fxml = os.path.join(ann_save_path, name + '.xml')
            ftrainval.write(fxml + '\n')
        else:
            ftest.write(name + '\n')
            fxml = os.path.join(ann_save_path, name + '.xml')
            ftest.write(fxml + '\n')
# Copy the contents of the VOC2007 directory to the VOC2012 folder
voc2007_path = os.path.join(original_path, 'VOC2007')
voc2012_path = os.path.join(original_path, 'VOC2012')
if os.path.exists(voc2012_path):# If it already exists, delete the folder and copy again.
    shutil.rmtree(voc2012_path) 
shutil.copytree(voc2007_path, voc2012_path)

 **You have used the code to copy and split the data**
**Is there any issue within this code? Sorry for using a translator.**
