### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by lsun325** [Megvii-BaseDetection/YOLOX#1701]
2023-08-10 08:54:40 | INFO     | yolox.core.trainer:203 - ---> start train epoch1
                                                        - epoch: 1/300, iter: 10/12, mem: 2956Mb, iter_time: 0.771s, data_time: 0.001s, total_loss: 5.5, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 2.0, cls_loss:
1.1, lr: 4.340e-04, size: 640, ETA: 0:46:06
2023-08-10 08:54:49 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:54:49 | INFO     | yolox.core.trainer:203 - ---> start train epoch2
2023-08-10 08:54:53 | INFO     | yolox.core.trainer:253 - epoch: 2/300, iter: 10/12, mem: 2956Mb, iter_time: 0.383s, data_time: 0.001s, total_loss: 4.8, iou_loss: 2.3, l1_loss: 0.0, conf_loss: 1.8, cls_loss:
0.7, lr: 6.250e-04, size: 576, ETA: 0:34:23
2023-08-10 08:54:53 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:54:53 | INFO     | yolox.core.trainer:203 - ---> start train epoch3
2023-08-10 08:54:58 | INFO     | yolox.core.trainer:253 - epoch: 3/300, iter: 10/12, mem: 3329Mb, iter_time: 0.470s, data_time: 0.002s, total_loss: 5.0, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 1.9, cls_loss:
0.6, lr: 6.249e-04, size: 768, ETA: 0:30:50
2023-08-10 08:54:59 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:54:59 | INFO     | yolox.core.trainer:203 - ---> start train epoch4
2023-08-10 08:55:03 | INFO     | yolox.core.trainer:253 - epoch: 4/300, iter: 10/12, mem: 3329Mb, iter_time: 0.448s, data_time: 0.003s, total_loss: 4.6, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 1.6, cls_loss:
0.6, lr: 6.249e-04, size: 608, ETA: 0:28:58
2023-08-10 08:55:03 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:04 | INFO     | yolox.core.trainer:203 - ---> start train epoch5
2023-08-10 08:55:05 | INFO     | yolox.core.trainer:253 - epoch: 5/300, iter: 10/12, mem: 3329Mb, iter_time: 0.194s, data_time: 0.006s, total_loss: 4.7, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 1.6, cls_loss:
0.6, lr: 6.247e-04, size: 768, ETA: 0:25:10
2023-08-10 08:55:06 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:06 | INFO     | yolox.core.trainer:203 - ---> start train epoch6
2023-08-10 08:55:08 | INFO     | yolox.core.trainer:253 - epoch: 6/300, iter: 10/12, mem: 3329Mb, iter_time: 0.156s, data_time: 0.001s, total_loss: 4.3, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 1.3, cls_loss:
0.6, lr: 6.246e-04, size: 640, ETA: 0:22:27
2023-08-10 08:55:08 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:08 | INFO     | yolox.core.trainer:203 - ---> start train epoch7
2023-08-10 08:55:10 | INFO     | yolox.core.trainer:253 - epoch: 7/300, iter: 10/12, mem: 3329Mb, iter_time: 0.194s, data_time: 0.001s, total_loss: 3.6, iou_loss: 2.0, l1_loss: 0.0, conf_loss: 1.1, cls_loss:
0.5, lr: 6.244e-04, size: 768, ETA: 0:20:46
2023-08-10 08:55:11 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:11 | INFO     | yolox.core.trainer:203 - ---> start train epoch8
2023-08-10 08:55:15 | INFO     | yolox.core.trainer:253 - epoch: 8/300, iter: 10/12, mem: 3329Mb, iter_time: 0.429s, data_time: 0.001s, total_loss: 5.1, iou_loss: 2.7, l1_loss: 0.0, conf_loss: 1.8, cls_loss:
0.6, lr: 6.242e-04, size: 544, ETA: 0:20:59
2023-08-10 08:55:15 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:15 | INFO     | yolox.core.trainer:203 - ---> start train epoch9
2023-08-10 08:55:20 | INFO     | yolox.core.trainer:253 - epoch: 9/300, iter: 10/12, mem: 3329Mb, iter_time: 0.433s, data_time: 0.001s, total_loss: 4.4, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 1.4, cls_loss:
0.6, lr: 6.239e-04, size: 672, ETA: 0:21:04
2023-08-10 08:55:20 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
2023-08-10 08:55:20 | INFO     | yolox.core.trainer:203 - ---> start train epoch10
2023-08-10 08:55:22 | INFO     | yolox.core.trainer:253 - epoch: 10/300, iter: 10/12, mem: 3329Mb, iter_time: 0.181s, data_time: 0.003s, total_loss: 3.4, iou_loss: 2.0, l1_loss: 0.0, conf_loss: 0.8, cls_loss:
 0.6, lr: 6.236e-04, size: 672, ETA: 0:19:55
2023-08-10 08:55:22 | INFO     | yolox.core.trainer:352 - Save weights to ./YOLOX_outputs\yolox_voc_s
100%|############################################################################################################################################################################| 3/3 [00:03<00:00,  1.32s/it]
2023-08-10 08:55:26 | INFO     | yolox.evaluators.voc_evaluator:160 - Evaluate in main process...
Writing defect VOC results file
2023-08-10 08:55:26 | INFO     | yolox.core.trainer:195 - Training of experiment is done and the best AP is 0.00
2023-08-10 08:55:26 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (10152), thread 'MainThread' (19384):
Traceback (most recent call last):

  File "C:\YOLOX-0.3.0\tools\train.py", line 134, in <module>
    launch(
    └ <function launch at 0x000001F78B0460D0>

> File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001F792D5B1F0>

  File "C:\YOLOX-0.3.0\tools\train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001F7931A0EE0>
    └ <yolox.core.trainer.Trainer object at 0x000001F792D36760>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\core\trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001F7931A75E0>
    └ <yolox.core.trainer.Trainer object at 0x000001F792D36760>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\core\trainer.py", line 86, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000001F7931A7940>
    └ <yolox.core.trainer.Trainer object at 0x000001F792D36760>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\core\trainer.py", line 222, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000001F7931A7C10>
    └ <yolox.core.trainer.Trainer object at 0x000001F792D36760>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\core\trainer.py", line 325, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x000001F7931A7550>
                             │    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x000001F792D36760>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\exp\yolox_base.py", line 322, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x000001F793198940>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001F796DBDEE0>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\evaluators\voc_evaluator.py", line 128, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([1.2701, 0.0080, 2.0000], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 629.6754,  368.1148,  858.0634,  579.1842],
                   │    │                             [1442.0361,  432.8301, 1494.7188,  451.6152],
                   │    │                             [108...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x000001F793198A60>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001F796DBDEE0>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\evaluators\voc_evaluator.py", line 205, in evaluate_prediction
    mAP50, mAP70 = self.dataloader.dataset.evaluate_detections(
                   │    │          │       └ <function VOCDetection.evaluate_detections at 0x000001F7931A03A0>
                   │    │          └ <yolox.data.datasets.voc.VOCDetection object at 0x000001F796DA0280>
                   │    └ <torch.utils.data.dataloader.DataLoader object at 0x000001F7965AEC40>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001F796DBDEE0>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\data\datasets\voc.py", line 265, in evaluate_detections
    self._write_voc_results_file(all_boxes)
    │    │                       └ [[array([[6.29675354e+02, 3.68114777e+02, 8.58063354e+02, 5.79184204e+02,
    │    │                                 9.08658028e-01],
    │    │                                [1.44203613e+03, 4....
    │    └ <function VOCDetection._write_voc_results_file at 0x000001F7931A04C0>
    └ <yolox.data.datasets.voc.VOCDetection object at 0x000001F796DA0280>

  File "C:\Anaconda\envs\env1\lib\site-packages\yolox-0.3.0-py3.9.egg\yolox\data\datasets\voc.py", line 299, in _write_voc_results_file
    if dets == []:
       └ array([[6.29675354e+02, 3.68114777e+02, 8.58063354e+02, 5.79184204e+02,
                 9.08658028e-01],
                [1.44203613e+03, 4.32...

ValueError: operands could not be broadcast together with shapes (24,5) (0,)

**Comment by wangtuo111** [comment]
me too

**Comment by liubalabala** [comment]
Did you work it out?

**Comment by seval124** [comment]
Same issue any update>?
