### ISSUE TITLE
AssertionError: Caught AssertionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Kangzf1996** [Megvii-BaseDetection/YOLOX#177]
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/coco.py", line 100, in pull_item
    assert img is not None
AssertionError

I've met this error when I run the train.py. Could you help me solve it? Thank you!

**Comment by matankley** [comment]
You have a problem with your data loader which is responsible for reading the images and labels.
The dataloader doesn't find your images.
Can you please attach your experiment.py file + train_log.txt + data structure folder?

**Comment by Kangzf1996** [comment]
> You have a problem with your data loader which is responsible for reading the images and labels.
> The dataloader doesn't find your images.
> Can you please attach your experiment.py file + train_log.txt + data structure folder?

Thank you!
The train_log is following:
2021-07-26 21:35:02.528 | INFO     | yolox.core.trainer:before_train:124 - args: Namespace(batch_size=64, ckpt=None, devices=None, dist_backend='nccl', dist_url=None, exp_file=None, experiment_name='yolox_x', fp16=True, local_rank=0, machine_rank=0, name='yolox-x', num_machine=1, occupy=False, opts=[], resume=False, start_epoch=None)
2021-07-26 21:35:02.533 | INFO     | yolox.core.trainer:before_train:125 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 28                         │
├──────────────────┼────────────────────────────┤
│ depth            │ 1.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 1.25                       │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ random_size      │ (14, 26)                   │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ scale            │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mscale           │ (0.8, 1.6)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ perspective      │ 0.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 5                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_x'                  │
├──────────────────┼────────────────────────────┤
│ test_size        │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
╘══════════════════╧════════════════════════════╛
2021-07-26 21:35:03.250 | INFO     | yolox.core.trainer:before_train:130 - Model Summary: Params: 99.02M, Gflops: 281.65
2021-07-26 21:35:05.073 | INFO     | apex.amp.frontend:initialize:328 - Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.
2021-07-26 21:35:05.074 | INFO     | apex.amp.frontend:initialize:329 - Defaults for this optimization level are:
2021-07-26 21:35:05.074 | INFO     | apex.amp.frontend:initialize:331 - enabled                : True
2021-07-26 21:35:05.074 | INFO     | apex.amp.frontend:initialize:331 - opt_level              : O1
2021-07-26 21:35:05.075 | INFO     | apex.amp.frontend:initialize:331 - cast_model_type        : None
2021-07-26 21:35:05.075 | INFO     | apex.amp.frontend:initialize:331 - patch_torch_functions  : True
2021-07-26 21:35:05.075 | INFO     | apex.amp.frontend:initialize:331 - keep_batchnorm_fp32    : None
2021-07-26 21:35:05.075 | INFO     | apex.amp.frontend:initialize:331 - master_weights         : None
2021-07-26 21:35:05.075 | INFO     | apex.amp.frontend:initialize:331 - loss_scale             : dynamic
2021-07-26 21:35:05.076 | INFO     | apex.amp.frontend:initialize:336 - Processing user overrides (additional kwargs that are not None)...
2021-07-26 21:35:05.076 | INFO     | apex.amp.frontend:initialize:354 - After processing overrides, optimization options are:
2021-07-26 21:35:05.076 | INFO     | apex.amp.frontend:initialize:356 - enabled                : True
2021-07-26 21:35:05.076 | INFO     | apex.amp.frontend:initialize:356 - opt_level              : O1
2021-07-26 21:35:05.077 | INFO     | apex.amp.frontend:initialize:356 - cast_model_type        : None
2021-07-26 21:35:05.077 | INFO     | apex.amp.frontend:initialize:356 - patch_torch_functions  : True
2021-07-26 21:35:05.077 | INFO     | apex.amp.frontend:initialize:356 - keep_batchnorm_fp32    : None
2021-07-26 21:35:05.077 | INFO     | apex.amp.frontend:initialize:356 - master_weights         : None
2021-07-26 21:35:05.077 | INFO     | apex.amp.frontend:initialize:356 - loss_scale             : dynamic
2021-07-26 21:35:05.083 | INFO     | apex.amp.scaler:__init__:69 - Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
2021-07-26 21:35:05.085 | INFO     | yolox.data.datasets.coco:__init__:44 - loading annotations into memory...
2021-07-26 21:35:05.154 | INFO     | yolox.data.datasets.coco:__init__:44 - Done (t=0.07s)
2021-07-26 21:35:05.155 | INFO     | pycocotools.coco:__init__:88 - creating index...
2021-07-26 21:35:05.157 | INFO     | pycocotools.coco:__init__:88 - index created!
2021-07-26 21:35:05.157 | INFO     | yolox.core.trainer:before_train:149 - init prefetcher, this might take one minute or less...
2021-07-26 21:35:05.430 | ERROR    | yolox.core.launch:launch:70 - An error has been caught in function 'launch', process 'MainProcess' (19811), thread 'MainThread' (139732919001280):
Traceback (most recent call last):

  File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=64, ckpt=None, devices=None, dist_backend='nccl', dist_url=None, exp_file=None, experiment_name='yolox_x...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "/home/zhkan/workspace/code/YOLOX-main/yolox/core/launch.py", line 70, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f14e1164320>

  File "tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f14e104a3b0>
    └ <yolox.core.trainer.Trainer object at 0x7f14dfd8d750>

  File "/home/zhkan/workspace/code/YOLOX-main/yolox/core/trainer.py", line 68, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f14dc1fe320>
    └ <yolox.core.trainer.Trainer object at 0x7f14dfd8d750>

  File "/home/zhkan/workspace/code/YOLOX-main/yolox/core/trainer.py", line 150, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7f148b93c2d0>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7f14dfd8d750>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7f14dfd8d750>

  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/data_prefetcher.py", line 26, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7f14e0a885f0>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f148b93c5d0>

  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/data_prefetcher.py", line 30, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f148b93c310>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f148b93c5d0>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f148b93c5d0>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f148b93c5d0>

  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f14eba78440>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f148b93c310>
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f14d98c5950>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f14eba78560>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f148b93c310>
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f1619370d40>
    └ <torch._utils.ExceptionWrapper object at 0x7f14d98c5950>
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/home/zhkan/anac...
          │    └ <class 'AssertionError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f14d98c5950>

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/zhkan/workspace/code/YOLOX-main/yolox/data/datasets/coco.py", line 100, in pull_item
    assert img is not None
AssertionError

And I didn't change anything in the experiment.py. And for the data structure folder, I set it as the COCO datasets. 
Thank you!

**Comment by Kangzf1996** [comment]
> You have a problem with your data loader which is responsible for reading the images and labels.
> The dataloader doesn't find your images.
> Can you please attach your experiment.py file + train_log.txt + data structure folder?

Hi, I've solve the problem. I've used my own datasets in the coco file. and the format is different.

**Comment by 18789447455** [comment]
> > 您的数据加载器有问题，它负责读取图像和标签。
> > 数据加载器找不到您的图像。
> > 你能附上你的experiment.py文件+train_log.txt+数据结构文件夹吗？
> 
> 你好，我已经解决了这个问题。我在 coco 文件中使用了我自己的数据集。而且格式不一样。

请问你是怎么解决这个问题的

**Comment by 18789447455** [comment]
> > 你的数据加载器有问题，它负责读取图像和标签。
> > 数据加载器找不到你的图像。
> > 你能附上你的实验。py文件+train_log.txt+数据结构文件夹吗？
> 
> 你好，我已经解决了这个问题。我在可可文件中使用了我自己的数据集。而且格式不一样。

请问你是怎么解决这个问题的

**Comment by jiwei0731** [comment]
> > > 你的数据加载器有问题，它负责读取图像和标签。
> > > 数据加载器找不到你的图像。
> > > 你能附上你的实验。py文件+train_log.txt+数据结构文件夹吗？
> > 
> > 
> > 你好，我已经解决了这个问题。我在可可文件中使用了我自己的数据集。而且格式不一样。
> 
> 请问你是怎么解决这个问题的

数据集路径有问题，debug一下看哪里出现的问题   我的是./yolox/datasets/coco.py 里面 COCODataset类里面name变量问题
