### ISSUE TITLE
UnicodeDecodeError: 'utf-8' when running setup.py

### ISSUE THREAD

**Issue by gboeer** [Megvii-BaseDetection/YOLOX#1815]
I tried running `python setup.py develop` to install the package in development mode, however I get the error:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 25: invalid start byte in scripts/ninja file at path: /home/appuser/.local/venv/lib/python3.10/site-packages/ninja-1.11.1.2-py3.10-linux-x86_64.egg/EGG-INFO/scripts/ninja

I am on the most recent commit:
https://github.com/Megvii-BaseDetection/YOLOX/commit/d872c71bf63e1906ef7b7bb5a9d7a529c7a59e6a

My python version is:
    
    python --version
    Python 3.10.15

My OS is:
Ubuntu 20.04.6 LTS (Focal Fossa)

This is the complete error trace:

```
/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
WARNING: The wheel package is not available.
running develop
/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing yolox.egg-info/PKG-INFO
writing dependency_links to yolox.egg-info/dependency_links.txt
writing requirements to yolox.egg-info/requires.txt
writing top-level names to yolox.egg-info/top_level.txt
/home/appuser/.local/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cu' under directory 'yolox'
warning: no files found matching '*.cuh' under directory 'yolox'
warning: no files found matching '*.cc' under directory 'yolox'
adding license file 'LICENSE'
writing manifest file 'yolox.egg-info/SOURCES.txt'
running build_ext
Creating /home/appuser/.local/venv/lib/python3.10/site-packages/yolox.egg-link (link to .)
yolox 0.3.0 is already the active version in easy-install.pth

Installed /develop/YOLOX
Processing dependencies for yolox==0.3.0
Searching for onnx-simplifier==0.4.10
Best match: onnx-simplifier 0.4.10
Processing onnx_simplifier-0.4.10-py3.10-linux-x86_64.egg
onnx-simplifier 0.4.10 is already the active version in easy-install.pth
Installing onnxsim script to /home/appuser/.local/venv/bin

Using /home/appuser/.local/venv/lib/python3.10/site-packages/onnx_simplifier-0.4.10-py3.10-linux-x86_64.egg
Searching for onnx==1.17.0
Best match: onnx 1.17.0
Processing onnx-1.17.0-py3.10-linux-x86_64.egg
onnx 1.17.0 is already the active version in easy-install.pth
Installing backend-test-tools script to /home/appuser/.local/venv/bin
Installing check-model script to /home/appuser/.local/venv/bin
Installing check-node script to /home/appuser/.local/venv/bin

Using /home/appuser/.local/venv/lib/python3.10/site-packages/onnx-1.17.0-py3.10-linux-x86_64.egg
Searching for pycocotools==2.0.8
Best match: pycocotools 2.0.8
Processing pycocotools-2.0.8-py3.10-linux-x86_64.egg
pycocotools 2.0.8 is already the active version in easy-install.pth

Using /home/appuser/.local/venv/lib/python3.10/site-packages/pycocotools-2.0.8-py3.10-linux-x86_64.egg
Searching for tensorboard==2.18.0
Best match: tensorboard 2.18.0
Processing tensorboard-2.18.0-py3.10.egg
tensorboard 2.18.0 is already the active version in easy-install.pth
Installing tensorboard script to /home/appuser/.local/venv/bin

Using /home/appuser/.local/venv/lib/python3.10/site-packages/tensorboard-2.18.0-py3.10.egg
Searching for psutil==6.1.0
Best match: psutil 6.1.0
Processing psutil-6.1.0-py3.10-linux-x86_64.egg
psutil 6.1.0 is already the active version in easy-install.pth

Using /home/appuser/.local/venv/lib/python3.10/site-packages/psutil-6.1.0-py3.10-linux-x86_64.egg
Searching for tabulate==0.9.0
Best match: tabulate 0.9.0
Processing tabulate-0.9.0-py3.10.egg
tabulate 0.9.0 is already the active version in easy-install.pth
Installing tabulate script to /home/appuser/.local/venv/bin

Using /home/appuser/.local/venv/lib/python3.10/site-packages/tabulate-0.9.0-py3.10.egg
Searching for ninja==1.11.1.2
Best match: ninja 1.11.1.2
Processing ninja-1.11.1.2-py3.10-linux-x86_64.egg
ninja 1.11.1.2 is already the active version in easy-install.pth
Traceback (most recent call last):
  File "/develop/YOLOX/setup.py", line 64, in <module>
    setuptools.setup(
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 765, in process_distribution
    self.easy_install(dist.as_requirement())
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 735, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/develop.py", line 151, in install_egg_scripts
    return easy_install.install_egg_scripts(self, dist)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 611, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/home/appuser/.local/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1433, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 25: invalid start byte in scripts/ninja file at path: /home/appuser/.local/venv/lib/python3.10/site-packages/ninja-1.11.1.2-py3.10-linux-x86_64.egg/EGG-INFO/scripts/ninja
```

**Comment by hitbuyi** [comment]
I have same issue
