### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'tensor_as'

### ISSUE THREAD

**Issue by Iipython** [Megvii-BaseDetection/YOLOX#184]
when I finished the first epoch, I find this fatal error.

AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/lustre/liyihao/.conda/envs/YOLOX/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/liyihao/.conda/envs/YOLOX/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/liyihao/.conda/envs/YOLOX/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/liyihao/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/mnt/lustre/liyihao/YOLOX/yolox/data/datasets/coco.py", line 132, in __getitem__
    img, target = self.preproc(img, res, self.input_dim)
  File "/mnt/lustre/liyihao/YOLOX/yolox/data/data_augment.py", line 269, in __call__
    return torch.tensor_as(img), torch.zeros(1, 5)
AttributeError: module 'torch' has no attribute 'tensor_as'

I tried to verify whether the attribute "tensor_as" exits:
>>> import torch
>>> torch.tensor_as()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'tensor_as'
>>> torch.__version__
'1.7.1'
And I also looked it up in pytorch official ducument .It seems  there is no attribute named "tesnor_as" but "as_tensor"?
So is that a mistake or I did not run it in a correct environment?

**Comment by ruinmessi** [comment]
sorry, it's a typo in some version of our code. Plz update to the newest version and try again.
