### ISSUE TITLE
训练的时候，在不定的opech的时候，会出现错误ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by xiaomujiang** [Megvii-BaseDetection/YOLOX#188]
今天上午pull最新的代码
训练命令 python3 -u tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 8 --fp16 -o -c ./yolox_s.pth.tar
训练数据VOC格式，这是为啥？

2021-07-27 11:46:04 | INFO     | yolox.core.trainer:307 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-07-27 11:46:04 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 52.84
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by ruinmessi** [comment]
已知的pytorch dataloader内存泄漏的bug。 参见 #103 ，还在一行一行定位中。。。开大内存或者减小worker能暂时缓解，

**Comment by lingdujunshang** [comment]
我也遇到了这个问题啊，求解决方案

**Comment by lingdujunshang** [comment]
data_num_workers = 0 也不管用啊
