### ISSUE TITLE
test error torch1.7

### ISSUE THREAD

**Issue by gentlebreeze1** [Megvii-BaseDetection/YOLOX#191]
run demo.py in torch1.9 is ok?but in torch1.7,i get error as follows?
`Traceback (most recent call last):
  File "/data/zhangyong/mypytoch/xyb/inference_x2.py", line 332, in <module>
    run()
  File "/data/zhangyong/mypytoch/xyb/inference_x2.py", line 236, in run
    outputs, img_info = predictor.inference(pic_path)
  File "/data/zhangyong/mypytoch/xyb/inference_x2.py", line 88, in inference
    outputs = self.model(img)
  File "/root/anaconda3/envs/game3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zhangyong/mypytoch/xyb/model/yolox/models/yolox.py", line 46, in forward
    outputs = self.head(fpn_outs)
  File "/root/anaconda3/envs/game3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zhangyong/mypytoch/xyb/model/yolox/models/yolo_head.py", line 194, in forward
    return self.decode_outputs(outputs, dtype=torch.cuda.FloatTensor)
  File "/data/zhangyong/mypytoch/xyb/model/yolox/models/yolo_head.py", line 228, in decode_outputs
    strides.append(torch.full((*shape, 1), stride))
RuntimeError: Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported. In PyTorch 1.7, when `dtype` and `out` are not set a bool fill value will return a tensor of torch.bool dtype, and an integral fill value will return a tensor of torch.long dtype.
`

**Comment by jiejie1993** [comment]
I met the same problem,have you solved it ?
