### ISSUE TITLE
problem about COCOdatasets2017 

### ISSUE THREAD

**Issue by MrSuen** [Megvii-BaseDetection/YOLOX#192]
after python tools/train.py -n yolox-s -d 1 -b 8 --fp16 -o
the problem:
2021-07-27 15:07:27 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (688), thread 'MainThread' (140405170800448):
Traceback (most recent call last):

  File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=8, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file=None, experiment_name='yolox_s', f...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "/root/YOLOX/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fb1a691d378>

  File "tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fb1adaea048>
    └ <yolox.core.trainer.Trainer object at 0x7fb1a6931780>

  File "/root/YOLOX/yolox/core/trainer.py", line 68, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fb1a6ba46a8>
    └ <yolox.core.trainer.Trainer object at 0x7fb1a6931780>

  File "/root/YOLOX/yolox/core/trainer.py", line 147, in before_train
    no_aug=self.no_aug
           │    └ False
           └ <yolox.core.trainer.Trainer object at 0x7fb1a6931780>

  File "/root/YOLOX/yolox/exp/yolox_base.py", line 99, in get_data_loader
    max_labels=50,

  File "/root/YOLOX/yolox/data/datasets/coco.py", line 43, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'instances_train2017.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.coco.COCODataset object at 0x7fb1f94b24e0>
    │           │    │  │    │    │    └ '/root/YOLOX/datasets/COCO'
    │           │    │  │    │    └ <yolox.data.datasets.coco.COCODataset object at 0x7fb1f94b24e0>
    │           │    │  │    └ <function join at 0x7fb29f2692f0>
    │           │    │  └ <module 'posixpath' from '/root/anaconda3/lib/python3.6/posixpath.py'>
    │           │    └ <module 'os' from '/root/anaconda3/lib/python3.6/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.coco.COCODataset object at 0x7fb1f94b24e0>

  File "/root/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
              │    │         └ '/root/YOLOX/datasets/COCO/annotations/instances_train2017.json'
              │    └ <function load at 0x7fb29ee97378>
              └ <module 'json' from '/root/anaconda3/lib/python3.6/json/__init__.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/root/YOLOX/datasets/COCO/annotations/instances_train2017.json'
How would you get over that problem...thx!

**Comment by MrSuen** [comment]
![捕获](https://user-images.githubusercontent.com/69710217/127112519-e820a73c-bd13-4d34-9783-260d2f14f359.PNG)
![捕获2](https://user-images.githubusercontent.com/69710217/127112532-1eb46723-0666-4c20-9665-f8dea17b7e7e.PNG)
![捕获3](https://user-images.githubusercontent.com/69710217/127112539-7751f72e-0b14-4aa1-af94-678e4afcd4d5.PNG)

**Comment by RUIXUEZHAOFENGNIAN** [comment]
how to fix the bug?

**Comment by KangChou** [comment]
my use coco2014:
ubuntu16.04
python3.6
cuda11
torch1.8


`2021-08-14 12:20:02 | INFO     | yolox.core.trainer:133 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:328 - Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:329 - Defaults for this optimization level are:
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - enabled                : True
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - opt_level              : O1
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - cast_model_type        : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - patch_torch_functions  : True
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - keep_batchnorm_fp32    : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - master_weights         : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:331 - loss_scale             : dynamic
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:336 - Processing user overrides (additional kwargs that are not None)...
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:354 - After processing overrides, optimization options are:
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - enabled                : True
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - opt_level              : O1
path_coco---------------- /data/my_project/YOLOX/COCO/COCO
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - cast_model_type        : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - patch_torch_functions  : True
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - keep_batchnorm_fp32    : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - master_weights         : None
2021-08-14 12:20:04 | INFO     | apex.amp.frontend:356 - loss_scale             : dynamic
2021-08-14 12:20:04 | INFO     | yolox.data.datasets.coco:44 - loading annotations into memory...
2021-08-14 12:20:04 | ERROR    | yolox.core.launch:78 - An error has been caught in function 'launch', process 'MainProcess' (3484), thread 'MainThread' (140363684980480):
Traceback (most recent call last):

  File "tools/train.py", line 126, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, ckpt=None, devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/default/yolox_s.py', experim...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/data/my_project/YOLOX/yolox/core/launch.py", line 78, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fa805313378>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fa78963d840>
    └ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

  File "/data/my_project/YOLOX/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fa805368510>
    └ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

  File "/data/my_project/YOLOX/yolox/core/trainer.py", line 151, in before_train
    no_aug=self.no_aug,
           │    └ False
           └ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

  File "/data/my_project/YOLOX/yolox/exp/yolox_base.py", line 100, in get_data_loader
    max_labels=50,

  File "/data/my_project/YOLOX/yolox/data/datasets/coco.py", line 44, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'instances_train2017.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>
    │           │    │  │    │    │    └ '/data/my_project/YOLOX/COCO/COCO'
    │           │    │  │    │    └ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>
    │           │    │  │    └ <function join at 0x7fa8f782f2f0>
    │           │    │  └ <module 'posixpath' from '/opt/conda/lib/python3.6/posixpath.py'>
    │           │    └ <module 'os' from '/opt/conda/lib/python3.6/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>

  File "/opt/conda/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
              │    │         └ '/data/my_project/YOLOX/COCO/COCO/annotations/instances_train2017.json'
              │    └ <function load at 0x7fa8f57d3730>
              └ <module 'json' from '/opt/conda/lib/python3.6/json/__init__.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/data/my_project/YOLOX/COCO/COCO/annotations/instances_train2017.json'
root@ovo:/data/my_project/YOLOX# vim /etc/default/locale 

[2]+  Stopped                 vim /etc/default/locale
`

**Comment by YUANMU227** [comment]
怎么解决的啊
