### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Yan-jiarun** [Megvii-BaseDetection/YOLOX#229]
when I try to train,run this
'''
python3 tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 0 -b 2 --fp16  -c yolox_s.pth
'''
it was wrong when there occurs 2021-07-28 19:50:56 | INFO     | yolox.core.trainer:245 - epoch: 1/300, iter: 240/405, mem: 2898Mb, iter_time: 0.104s, data_time: 0.000s, total_loss: 4.7, iou_loss: 1.6, l1_loss: 0.0, conf_loss: 2.3, cls_loss: 0.8, lr: 4.390e-06, size: 608, ETA: 7:17:45

here are the details:
2021-07-28 19:50:55 | INFO     | yolox.core.trainer:245 - epoch: 1/300, iter: 230/405, mem: 2898Mb, iter_time: 0.104s, data_time: 0.000s, total_loss: 4.8, iou_loss: 2.0, l1_loss: 0.0, conf_loss: 1.5, cls_loss: 1.3, lr: 4.031e-06, size: 544, ETA: 7:27:43
2021-07-28 19:50:56 | INFO     | yolox.core.trainer:245 - epoch: 1/300, iter: 240/405, mem: 2898Mb, iter_time: 0.104s, data_time: 0.000s, total_loss: 4.7, iou_loss: 1.6, l1_loss: 0.0, conf_loss: 2.3, cls_loss: 0.8, lr: 4.390e-06, size: 608, ETA: 7:17:45
2021-07-28 19:50:57 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 0.00
2021-07-28 19:50:57 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (3173), thread 'MainThread' (140583223760704):
Traceback (most recent call last):

  File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=2, ckpt='yolox_s.pth', devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/y...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "/home/yan/YOLOX/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fdb434ab598>

  File "tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fdb55bb3400>
    └ <yolox.core.trainer.Trainer object at 0x7fdc11a8fda0>

  File "/home/yan/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fdbaa11d620>
    └ <yolox.core.trainer.Trainer object at 0x7fdc11a8fda0>

  File "/home/yan/YOLOX/yolox/core/trainer.py", line 79, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7fdbaa1249d8>
    └ <yolox.core.trainer.Trainer object at 0x7fdc11a8fda0>

  File "/home/yan/YOLOX/yolox/core/trainer.py", line 85, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7fdbaa124a60>
    └ <yolox.core.trainer.Trainer object at 0x7fdc11a8fda0>

  File "/home/yan/YOLOX/yolox/core/trainer.py", line 91, in train_one_iter
    inps, targets = self.prefetcher.next()
                    │    │          └ <function DataPrefetcher.next at 0x7fdb480e4b70>
                    │    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fdb390250f0>
                    └ <yolox.core.trainer.Trainer object at 0x7fdc11a8fda0>

  File "/home/yan/YOLOX/yolox/data/data_prefetcher.py", line 48, in next
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7fdb480e46a8>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fdb390250f0>

  File "/home/yan/YOLOX/yolox/data/data_prefetcher.py", line 30, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │    │           │    │                        │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fdb55564a20>
    │    │           │    │                        └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fdb390250f0>
    │    │           │    └ tensor([[[0., 0., 0., 0., 0.],
    │    │           │               [0., 0., 0., 0., 0.],
    │    │           │               [0., 0., 0., 0., 0.],
    │    │           │               ...,
    │    │           │               [0., 0., ...
    │    │           └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fdb390250f0>
    │    └ tensor([[[[-0.1657, -0.1657, -0.1657,  ..., -0.1657, -0.1657, -0.1657],
    │                [-0.1657, -0.1657, -0.1657,  ..., -0.1657, ...
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fdb390250f0>

  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7fdb555a5268>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fdb55564a20>
  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7fdb3af557b8>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7fdb555a5378>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fdb55564a20>
  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fdc10ccad90>
    └ <torch._utils.ExceptionWrapper object at 0x7fdb3af557b8>
  File "/home/yan/.local/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
          │    │        └ Caught KeyError in DataLoader worker process 0.
          │    │          Original Traceback (most recent call last):
          │    │            File "/home/yan/.local/lib/pyth...
          │    └ <class 'KeyError'>
          └ <torch._utils.ExceptionWrapper object at 0x7fdb3af557b8>

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yan/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/yan/YOLOX/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/yan/YOLOX/yolox/data/datasets/voc.py", line 145, in pull_item
    target = self.load_anno(index)
  File "/home/yan/YOLOX/yolox/data/datasets/voc.py", line 126, in load_anno
    target = self.target_transform(target)
  File "/home/yan/YOLOX/yolox/data/datasets/voc.py", line 64, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'dw'

**Comment by 1VeniVediVeci1** [comment]
Check if your classes are all lowercase, and are followed by a "," in voc_classes.

**Comment by Yan-jiarun** [comment]
yes,the voc_classes.py is:

#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

# VOC_CLASSES = ( '__background__', # always index 0
VOC_CLASSES = (
    "bridge",
    "car",
    # "aeroplane",
    # "bicycle",
    # "bird",
    # "boat",
    # "bottle",
    # "bus",
    # "car",
    # "cat",
    # "chair",
    # "cow",
    # "diningtable",
    # "dog",
    # "horse",
    # "motorbike",
    # "person",
    # "pottedplant",
    # "sheep",
    # "sofa",
    # "train",
    # "tvmonitor",
)

**Comment by Yan-jiarun** [comment]
> s

yes,the voc_classes.py is:

#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

# VOC_CLASSES = ( '__background__', # always index 0
VOC_CLASSES = (
    "bridge",
    "car",
    # "aeroplane",
    # "bicycle",
    # "bird",
    # "boat",
    # "bottle",
    # "bus",
    # "car",
    # "cat",
    # "chair",
    # "cow",
    # "diningtable",
    # "dog",
    # "horse",
    # "motorbike",
    # "person",
    # "pottedplant",
    # "sheep",
    # "sofa",
    # "train",
    # "tvmonitor",
)

**Comment by Yan-jiarun** [comment]
> Check if your classes are all lowercase, and are followed by a "," in voc_classes.

yes,the voc_classes.py is:

#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

# VOC_CLASSES = ( '__background__', # always index 0
VOC_CLASSES = (
    "bridge",
    "car",
    # "aeroplane",
    # "bicycle",
    # "bird",
    # "boat",
    # "bottle",
    # "bus",
    # "car",
    # "cat",
    # "chair",
    # "cow",
    # "diningtable",
    # "dog",
    # "horse",
    # "motorbike",
    # "person",
    # "pottedplant",
    # "sheep",
    # "sofa",
    # "train",
    # "tvmonitor",
)

**Comment by 1VeniVediVeci1** [comment]
Maybe your classes in .py don't cover all the classes in your dataset?

**Comment by Yan-jiarun** [comment]
> Maybe your classes in .py don't cover all the classes in your dataset?

My dataset only two  classes，and I use my own dataset which is the voc format by this cmd:
ln -s /path/to/your/VOCdevkit ./datasets/VOCdevkit
and the dir-level like this:
/path/to/your/VOCdevkit/VOC2007/ImageSets/Main
is the format wrong?

**Comment by Yan-jiarun** [comment]
And I have a problem that it is show it begin to run in epoch,why classes still can influence?

**Comment by Yan-jiarun** [comment]
And I have a problem that it is show it begin to run in epoch,why classes still can influence?

**Comment by 1VeniVediVeci1** [comment]
> > Maybe your classes in .py don't cover all the classes in your dataset?
> 
> My dataset only two classes，and I use my own dataset which is the voc format by this cmd:
> ln -s /path/to/your/VOCdevkit ./datasets/VOCdevkit
> and the dir-level like this:
> /path/to/your/VOCdevkit/VOC2007/ImageSets/Main
> is the format wrong?

The /path/to/your/VOCdevkit/ is actually not the path, but the content you should replace with your own path. To be specific, don't create folder named "path", "to", "your"

**Comment by Yan-jiarun** [comment]
yes,it is actually that I used my own path.As my path is:
/home/yan/YOLOX/datasets/VOCdevkit
I replace with that.

**Comment by Yan-jiarun** [comment]
> The /path/to/your/VOCdevkit/ is actually not the path, but the content you should replace with your own path. To be specific, don't create folder named "path", "to", "your"

So,I think my setting is right.But where it is wrong?

**Comment by huangxiaohuangi** [comment]
是你自定义数据的标记类别名的问题，和你VOC_CLASSES = (
"bridge",
"car",
# "aeroplane",
# "bicycle",
# "bird",
# "boat",
# "bottle",
# "bus",
# "car",
# "cat",
# "chair",
# "cow",
# "diningtable",
# "dog",
# "horse",
# "motorbike",
# "person",
# "pottedplant",
# "sheep",
# "sofa",
# "train",
# "tvmonitor",
)
中的前两个不一致

**Comment by huangxiaohuangi** [comment]
是你自定义数据的标记类别名的问题，和你VOC_CLASSES = (
"bridge",
"car",
)
中的两个类别名不一致

**Comment by Yan-jiarun** [comment]
> 是你自定义数据的标记类别名的问题，你标记数据的xml中的类别名和你VOC_CLASSES = (
> "bridge",
> "car",
> )
> 中的两个类别名不一致

是一樣的呀，我檢查過了。.xml是這樣寫的：
<annotation>
<folder>car06</folder>
<filename>00804.jpg</filename>
<path>/home/without/datasImg/car_videos/output/car06/00804.jpg</path>
<source>
<database>Unknown</database>
</source>
<size>
<width>1920</width>
<height>1080</height>
<depth>3</depth>
</size>
<segmented>0</segmented>
<object>
<name>car</name>
<pose>Unspecified</pose>
<truncated>0</truncated>
<difficult>0</difficult>
<bndbox>
<xmin>701</xmin>
<ymin>45</ymin>
<xmax>908</xmax>
<ymax>285</ymax>
</bndbox>
</object>
</annotation>

**Comment by Yan-jiarun** [comment]
或者說，能提供一个voc数据集给我试一下么？官网的下不到

**Comment by Yan-jiarun** [comment]
> 是你自定义数据的标记类别名的问题，你标记数据的xml中的类别名和你VOC_CLASSES = (
> "bridge",
> "car",
> )
> 中的两个类别名不一致

是一致的，我的.xml是 这样写的：

<annotation>
	<folder>car06</folder>
	<filename>00804.jpg</filename>
	<path>/home/without/datasImg/car_videos/output/car06/00804.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>1920</width>
		<height>1080</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>car</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>701</xmin>
			<ymin>45</ymin>
			<xmax>908</xmax>
			<ymax>285</ymax>
		</bndbox>
	</object>
</annotation>

不知道对不对

**Comment by Yan-jiarun** [comment]
> 是你自定义数据的标记类别名的问题，你标记数据的xml中的类别名和你VOC_CLASSES = (
> "bridge",
> "car",
> )
> 中的两个类别名不一致

是一致的，我的.xml是这样写的，您看对不对：

<annotation>
	<folder>car06</folder>
	<filename>00804.jpg</filename>
	<path>/home/without/datasImg/car_videos/output/car06/00804.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>1920</width>
		<height>1080</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>car</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>701</xmin>
			<ymin>45</ymin>
			<xmax>908</xmax>
			<ymax>285</ymax>
		</bndbox>
	</object>
</annotation>

**Comment by Yan-jiarun** [comment]
> 是你自定义数据的标记类别名的问题，你标记数据的xml中的类别名和你VOC_CLASSES = (
> "bridge",
> "car",
> )
> 中的两个类别名不一致

是一致的

**Comment by Yan-jiarun** [comment]
> 是你自定义数据的标记类别名的问题，你标记数据的xml中的类别名和你VOC_CLASSES = (
> "bridge",
> "car",
> )
> 中的两个类别名不一致

或许是我的数据集的问题，我再看看，因为我用VOC2007的数据集已经可以跑了，感谢！

**Comment by liuwei3612** [comment]
2021-07-30 16:27:00 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 5.04M, Gflops: 6.41
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:328 - Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:329 - Defaults for this optimization level are:
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - enabled                : True
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - opt_level              : O1
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - cast_model_type        : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - patch_torch_functions  : True
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - keep_batchnorm_fp32    : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - master_weights         : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:331 - loss_scale             : dynamic
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:336 - Processing user overrides (additional kwargs that are not None)...
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:354 - After processing overrides, optimization options are:
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - enabled                : True
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - opt_level              : O1
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - cast_model_type        : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - patch_torch_functions  : True
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - keep_batchnorm_fp32    : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - master_weights         : None
2021-07-30 16:27:03 | INFO     | apex.amp.frontend:356 - loss_scale             : dynamic
2021-07-30 16:27:03 | INFO     | apex.amp.scaler:69 - Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
2021-07-30 16:27:03 | INFO     | yolox.core.trainer:296 - loading checkpoint for fine tuning
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([15, 96, 1, 1]).
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([15]).
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([15, 96, 1, 1]).
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([15]).
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([15, 96, 1, 1]).
2021-07-30 16:27:03 | WARNING  | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([15]).
2021-07-30 16:27:03 | INFO     | yolox.core.trainer:152 - init prefetcher, this might take one minute or less...
2021-07-30 16:27:15 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (27263), thread 'MainThread' (140593167947520):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=64, ckpt='pth/yolox_tiny.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/yolox_t...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/home/lw/work/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fde649d2a70>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fdddb054a70>
    └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>

  File "/home/lw/work/YOLOX/yolox/core/trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fddd8832560>
    └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>

  File "/home/lw/work/YOLOX/yolox/core/trainer.py", line 176, in before_train
    batch_size=self.args.batch_size, is_distributed=self.is_distributed
               │    │    │                          │    └ False
               │    │    │                          └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>
               │    │    └ 64
               │    └ Namespace(batch_size=64, ckpt='pth/yolox_tiny.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/yolox_t...
               └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>

  File "exps/yolox_tiny/yolox_tiny.py", line 117, in get_evaluator
    val_loader = self.get_eval_loader(batch_size, is_distributed, testdev=testdev)
                 │    │               │           │                       └ False
                 │    │               │           └ False
                 │    │               └ 64
                 │    └ <function Exp.get_eval_loader at 0x7fddd87c5cb0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "exps/yolox_tiny/yolox_tiny.py", line 102, in get_eval_loader
    sampler = torch.utils.data.SequentialSampler(valdataset)
                                                 └ <yolox.data.datasets.voc.VOCDetection object at 0x7fddb5fe0c50>

NameError: name 'torch' is not defined
训练时遇到这样的问题，怎么解决啊

**Comment by Yan-jiarun** [comment]
> 2021-07-30 16:27:00 | INFO | yolox.core.trainer:132 - Model Summary: Params: 5.04M, Gflops: 6.41
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:328 - Selected optimization level O1: Insert automatic casts around Pytorch functions and Tensor methods.
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:329 - Defaults for this optimization level are:
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - enabled : True
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - opt_level : O1
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - cast_model_type : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - patch_torch_functions : True
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - keep_batchnorm_fp32 : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - master_weights : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:331 - loss_scale : dynamic
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:336 - Processing user overrides (additional kwargs that are not None)...
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:354 - After processing overrides, optimization options are:
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - enabled : True
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - opt_level : O1
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - cast_model_type : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - patch_torch_functions : True
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - keep_batchnorm_fp32 : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - master_weights : None
> 2021-07-30 16:27:03 | INFO | apex.amp.frontend:356 - loss_scale : dynamic
> 2021-07-30 16:27:03 | INFO | apex.amp.scaler:69 - Warning: multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback. Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
> 2021-07-30 16:27:03 | INFO | yolox.core.trainer:296 - loading checkpoint for fine tuning
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([15, 96, 1, 1]).
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([15]).
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([15, 96, 1, 1]).
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([15]).
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([15, 96, 1, 1]).
> 2021-07-30 16:27:03 | WARNING | yolox.utils.checkpoint:27 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([15]).
> 2021-07-30 16:27:03 | INFO | yolox.core.trainer:152 - init prefetcher, this might take one minute or less...
> 2021-07-30 16:27:15 | ERROR | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (27263), thread 'MainThread' (140593167947520):
> Traceback (most recent call last):
> 
> File "tools/train.py", line 125, in
> args=(exp, args),
> │ └ Namespace(batch_size=64, ckpt='pth/yolox_tiny.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/yolox_t...
> └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
> 
> > File "/home/lw/work/YOLOX/yolox/core/launch.py", line 90, in launch
> > main_func(*args)
> > │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
> > └ <function main at 0x7fde649d2a70>
> 
> File "tools/train.py", line 104, in main
> trainer.train()
> │ └ <function Trainer.train at 0x7fdddb054a70>
> └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>
> 
> File "/home/lw/work/YOLOX/yolox/core/trainer.py", line 69, in train
> self.before_train()
> │ └ <function Trainer.before_train at 0x7fddd8832560>
> └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>
> 
> File "/home/lw/work/YOLOX/yolox/core/trainer.py", line 176, in before_train
> batch_size=self.args.batch_size, is_distributed=self.is_distributed
> │ │ │ │ └ False
> │ │ │ └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>
> │ │ └ 64
> │ └ Namespace(batch_size=64, ckpt='pth/yolox_tiny.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/yolox_t...
> └ <yolox.core.trainer.Trainer object at 0x7fddd87c7f50>
> 
> File "exps/yolox_tiny/yolox_tiny.py", line 117, in get_evaluator
> val_loader = self.get_eval_loader(batch_size, is_distributed, testdev=testdev)
> │ │ │ │ └ False
> │ │ │ └ False
> │ │ └ 64
> │ └ <function Exp.get_eval_loader at 0x7fddd87c5cb0>
> └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
> 
> File "exps/yolox_tiny/yolox_tiny.py", line 102, in get_eval_loader
> sampler = torch.utils.data.SequentialSampler(valdataset)
> └ <yolox.data.datasets.voc.VOCDetection object at 0x7fddb5fe0c50>
> 
> NameError: name 'torch' is not defined
> 训练时遇到这样的问题，怎么解决啊

torch没定义是没有装好吗

**Comment by 0nethought** [comment]
自定义数据集就会出问题，看了另一个blog说是数据集缓存出问题了，我先去试试。

**Comment by Double-zh** [comment]
> 自定义数据集就会出问题，看了另一个blog说是数据集缓存出问题了，我先去试试。

应该怎么解决
