### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by Abandon-ht** [Megvii-BaseDetection/YOLOX#23]
(YOLOX) ncy@Lenovo:~/PycharmProjects/YOLOX$ python tools/demo.py image -n yolox-s -c yolox_s.pth.tar --path assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result
Traceback (most recent call last):
  File "/home/ncy/PycharmProjects/YOLOX/tools/demo.py", line 277, in <module>
    main(exp, args)
  File "/home/ncy/PycharmProjects/YOLOX/tools/demo.py", line 210, in main
    os.makedirs(file_name, exist_ok=True)
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

**Comment by Joker316701882** [comment]
@Abandon-ht Hi. This issue has been fixed. Please pull the latest branch and try again.
