### ISSUE TITLE
TensorRT convertion error

### ISSUE THREAD

**Issue by zzzfo** [Megvii-BaseDetection/YOLOX#232]
使用trt.py将模型转化成tenso时报了这个错：

2021-07-28 22:53:35.575 | ERROR    | __main__:<module>:79 - An error has been caught in function '<module>', process 'MainProcess' (6088), thread 'MainThread' (139764452450496):
Traceback (most recent call last):

> File "trt.py", line 79, in <module>
    main()
    └ <function main at 0x7f1c0cdad790>

  File "trt.py", line 58, in main
    model_trt = torch2trt(
                └ <function torch2trt at 0x7f1c1a1424c0>

  File "/home/wumei/.local/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/torch2trt.py", line 578, in torch2trt
    engine = builder.build_cuda_engine(network)
             │       │                 └ <tensorrt.tensorrt.INetworkDefinition object at 0x7f1c0cdd07f0>
             │       └ <instancemethod build_cuda_engine at 0x7f1d2f773ee0>
             └ <tensorrt.tensorrt.Builder object at 0x7f1c0cae23b0>

RuntimeError: Driver error:

**Comment by ruinmessi** [comment]
Plz check your installation of cuda, TensorRT, and torch2trt

**Comment by zzzfo** [comment]
> Plz check your installation of cuda, TensorRT, and torch2trt
cuda version：11.1 
cudnn : 8.1.0
TensorRT : 7.2.3.4
已经安装了torch2trt
>>> import torch2trt没有报错

**Comment by zzzfo** [comment]
cuda version：11.1 
cudnn : 8.1.0
TensorRT : 7.2.3.4
已经安装了torch2trt
>>> import torch2trt没有报错
