### ISSUE TITLE
修改win10的hostname bug后，出现如下错误。

### ISSUE THREAD

**Issue by lavender-ling** [Megvii-BaseDetection/YOLOX#244]
E:\yuyang\YOLOX-main>python tools/train.py
2021-07-29 14:28:15.306 | INFO     | yolox.core.launch:launch_by_subprocess:142 -
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 123, in <module>
    launch(
  File "e:\yuyang\yolox-main\yolox\core\launch.py", line 80, in launch
    launch_by_subprocess(
  File "e:\yuyang\yolox-main\yolox\core\launch.py", line 163, in launch_by_subprocess
    process = subprocess.Popen(cmd, env=current_env)
  File "D:\Anaconda3\envs\CNet2\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda3\envs\CNet2\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by ruinmessi** [comment]
see #240
