### ISSUE TITLE
error in training VOC

### ISSUE THREAD

**Issue by fxt960803** [Megvii-BaseDetection/YOLOX#268]
2021-07-30 14:45:51 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (16280), thread 'MainThread' (4236):
Traceback (most recent call last):

  File "train.py", line 113, in <module>
    launch(
    └ <function launch at 0x000001D9E0F45040>

> File "D:\YOLOX-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001D9E34DECA0>

  File "train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001D9E26F1C10>
    └ <yolox.core.trainer.Trainer object at 0x000001D9E34E5FD0>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001D9E34BD4C0>
    └ <yolox.core.trainer.Trainer object at 0x000001D9E34E5FD0>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 161, in before_train
    occupy_mem(self.local_rank)
    │          │    └ 0
    │          └ <yolox.core.trainer.Trainer object at 0x000001D9E34E5FD0>
    └ <function occupy_mem at 0x000001D9E13043A0>

  File "D:\YOLOX-main\yolox\utils\metric.py", line 35, in occupy_mem
    total, used = get_total_and_free_memory_in_Mb(cuda_device)
                  │                               └ 0
                  └ <function get_total_and_free_memory_in_Mb at 0x000001D9E1304310>

  File "D:\YOLOX-main\yolox\utils\metric.py", line 27, in get_total_and_free_memory_in_Mb
    total, used = devices_info[int(cuda_device)].split(",")
                  │                └ 0
                  └ ['']

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by ruinmessi** [comment]
plz remove `-o` in the training command and try again.

**Comment by fxt960803** [comment]
> 请在训练命令中删除并重试。`-o`

解决问题了，感谢
