### ISSUE TITLE
KeyError: "filename 'storages' not found"

### ISSUE THREAD

**Issue by MinsuKim3095** [Megvii-BaseDetection/YOLOX#279]
Thanks for your work.

I tried to execute demo with this command

python3 tools/demo.py image -n yolox-s -c weights/yolox_s.pth.tar --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu

but error is 

Traceback (most recent call last):
  File "tools/demo.py", line 296, in <module>
    main(exp, args)
  File "tools/demo.py", line 262, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 762, in _legacy_load
    return legacy_load(f)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 687, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/usr/lib/python3.8/tarfile.py", line 2060, in extract
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.8/tarfile.py", line 1782, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

what should I do?

**Comment by MinsuKim3095** [comment]
I solved it. just remove .tar

python3 tools/demo.py image -n yolox-s -c weights/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
