### ISSUE TITLE
Multi GPU Error

### ISSUE THREAD

**Issue by qq995431104** [Megvii-BaseDetection/YOLOX#286]
训练时, 使用单个GPU 不会报错,但指定多个GPU,就会报错:
使用的命令: `CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python tools/train.py -f exps/example/yolox_voc/yolox_myvoc_s.py -d 6 -b 96 -o -c /path/to/the/pretrained/weights`
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/data4/wensongli/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data4/wensongli/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data4/wensongli/projects/YOLOX_train/yolox/models/yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
  File "/data4/wensongli/anaconda3/envs/torch1.7/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data4/wensongli/projects/YOLOX_train/yolox/models/yolo_head.py", line 168, in forward
    output, grid = self.get_output_and_grid(
  File "/data4/wensongli/projects/YOLOX_train/yolox/models/yolo_head.py", line 234, in get_output_and_grid
    output[..., :2] = (output[..., :2] + grid) * stride
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by luoqiang10605** [comment]
are you slove the problem?

**Comment by xarauzo** [comment]
What was the solution?
