### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by sunmooncode** [Megvii-BaseDetection/YOLOX#308]
2021-08-02 15:19:10 | INFO     | yolox.core.trainer:193 - ---> start train epoch1
2021-08-02 15:19:14 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 10/161, mem: 8760Mb, iter_time: 0.349s, data_time: 0.001s, total_loss: 26.6, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 20.8, cls_loss: 1.1, lr: 7.716e-07, size: 640, ETA: 4:40:37
2021-08-02 15:19:19 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 20/161, mem: 8760Mb, iter_time: 0.472s, data_time: 0.160s, total_loss: 19.0, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 13.2, cls_loss: 1.1, lr: 3.086e-06, size: 448, ETA: 5:30:20
2021-08-02 15:19:24 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 30/161, mem: 8760Mb, iter_time: 0.518s, data_time: 0.263s, total_loss: 26.1, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 20.3, cls_loss: 1.1, lr: 6.944e-06, size: 608, ETA: 5:58:59
2021-08-02 15:19:28 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 40/161, mem: 8760Mb, iter_time: 0.408s, data_time: 0.132s, total_loss: 16.4, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 10.6, cls_loss: 1.2, lr: 1.235e-05, size: 384, ETA: 5:51:14
2021-08-02 15:19:32 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 50/161, mem: 8760Mb, iter_time: 0.403s, data_time: 0.237s, total_loss: 19.2, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 13.4, cls_loss: 1.2, lr: 1.929e-05, size: 448, ETA: 5:45:45
2021-08-02 15:19:36 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 60/161, mem: 8760Mb, iter_time: 0.391s, data_time: 0.177s, total_loss: 17.3, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 11.5, cls_loss: 1.3, lr: 2.778e-05, size: 416, ETA: 5:40:26
2021-08-02 15:19:40 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 70/161, mem: 8760Mb, iter_time: 0.404s, data_time: 0.221s, total_loss: 15.2, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 9.4, cls_loss: 1.3, lr: 3.781e-05, size: 320, ETA: 5:38:09
2021-08-02 15:19:43 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 80/161, mem: 8760Mb, iter_time: 0.309s, data_time: 0.162s, total_loss: 15.8, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 10.0, cls_loss: 1.2, lr: 4.938e-05, size: 384, ETA: 5:26:54
2021-08-02 15:19:48 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 90/161, mem: 8760Mb, iter_time: 0.520s, data_time: 0.295s, total_loss: 19.1, iou_loss: 4.7, l1_loss: 0.0, conf_loss: 13.4, cls_loss: 1.1, lr: 6.250e-05, size: 544, ETA: 5:36:54
2021-08-02 15:19:52 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 100/161, mem: 8760Mb, iter_time: 0.361s, data_time: 0.127s, total_loss: 17.0, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 11.2, cls_loss: 1.2, lr: 7.716e-05, size: 448, ETA: 5:32:10
2021-08-02 15:19:57 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 110/161, mem: 8760Mb, iter_time: 0.498s, data_time: 0.272s, total_loss: 18.5, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 12.6, cls_loss: 1.2, lr: 9.336e-05, size: 512, ETA: 5:38:14
2021-08-02 15:20:01 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 120/161, mem: 8760Mb, iter_time: 0.382s, data_time: 0.156s, total_loss: 18.5, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 12.7, cls_loss: 1.2, lr: 1.111e-04, size: 544, ETA: 5:35:31
2021-08-02 15:20:05 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 130/161, mem: 8760Mb, iter_time: 0.465s, data_time: 0.233s, total_loss: 15.0, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 9.2, cls_loss: 1.3, lr: 1.304e-04, size: 384, ETA: 5:38:22
2021-08-02 15:20:09 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 140/161, mem: 8760Mb, iter_time: 0.356s, data_time: 0.177s, total_loss: 16.2, iou_loss: 4.5, l1_loss: 0.0, conf_loss: 10.3, cls_loss: 1.3, lr: 1.512e-04, size: 544, ETA: 5:34:34
2021-08-02 15:20:14 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 150/161, mem: 8760Mb, iter_time: 0.553s, data_time: 0.306s, total_loss: 17.2, iou_loss: 4.6, l1_loss: 0.0, conf_loss: 11.4, cls_loss: 1.2, lr: 1.736e-04, size: 608, ETA: 5:41:46
2021-08-02 15:20:19 | INFO     | yolox.core.trainer:254 - epoch: 1/300, iter: 160/161, mem: 8760Mb, iter_time: 0.487s, data_time: 0.196s, total_loss: 16.3, iou_loss: 4.4, l1_loss: 0.0, conf_loss: 10.5, cls_loss: 1.4, lr: 1.975e-04, size: 480, ETA: 5:44:46
2021-08-02 15:20:20 | INFO     | yolox.core.trainer:322 - Save weights to ./YOLOX_outputs/nano
  0%|          | 0/41 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|##########| 41/41 [00:06<00:00,  6.50it/s]
2021-08-02 15:20:26 | INFO     | yolox.evaluators.coco_evaluator:172 - Evaluate in main process...
2021-08-02 15:20:26 | INFO     | yolox.evaluators.coco_evaluator:205 - Loading and preparing results...
2021-08-02 15:20:26 | INFO     | yolox.evaluators.coco_evaluator:205 - DONE (t=0.00s)
2021-08-02 15:20:26 | INFO     | pycocotools.coco:363 - creating index...
2021-08-02 15:20:26 | INFO     | pycocotools.coco:363 - index created!
2021-08-02 15:20:26 | WARNING  | yolox.evaluators.coco_evaluator:211 - Use standard COCOeval.
2021-08-02 15:20:26 | INFO     | yolox.core.trainer:188 - Training of experiment is done and the best AP is 0.00
2021-08-02 15:20:26 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (23124), thread 'MainThread' (140386689697536):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=32, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/default/nano.py', experimen...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/home/zt/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fae518e6c20>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fadb5747680>
    └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>

  File "/home/zt/YOLOX/yolox/core/trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fadb486f710>
    └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>

  File "/home/zt/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7fadb2d42050>
    └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>

  File "/home/zt/YOLOX/yolox/core/trainer.py", line 215, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7fadb2d42320>
    └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>

  File "/home/zt/YOLOX/yolox/core/trainer.py", line 307, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fada860fc90>
    │          └ <yolox.core.trainer.Trainer object at 0x7fadb2fd7310>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/home/zt/YOLOX/yolox/exp/yolox_base.py", line 251, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7fadb2d2aa70>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fada860fc90>

  File "/home/zt/YOLOX/yolox/evaluators/coco_evaluator.py", line 132, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 0.7957,  0.1979, 40.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 20190000071, 'category_id': 5, 'bbox': [-491.8992004394531, -221.0110321044922, 609.7808837890625, 213.33943176...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x7fadb2d2ab90>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fada860fc90>

  File "/home/zt/YOLOX/yolox/evaluators/coco_evaluator.py", line 213, in evaluate_prediction
    cocoEval = COCOeval(cocoGt, cocoDt, annType[1])
               │        │       │       └ ['segm', 'bbox', 'keypoints']
               │        │       └ <pycocotools.coco.COCO object at 0x7fada8503a90>
               │        └ <pycocotools.coco.COCO object at 0x7fada8458e90>
               └ <module 'pycocotools.cocoeval' from '/home/zt/anaconda3/envs/yolox/lib/python3.7/site-packages/pycocotools/cocoeval.py'>

TypeError: 'module' object is not callable

**Comment by hehu56** [comment]
更新了最新的模型以后我也出现了这个问题

**Comment by sunmooncode** [comment]
@hehu56  解决了吗？

**Comment by ruinmessi** [comment]
Plz reinstall yolox:
```
pip3 install -v -e .
```
