### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox.data.datasets.voc'

### ISSUE THREAD

**Issue by haomayang1126** [Megvii-BaseDetection/YOLOX#311]
使用VOC数据集训练出现这个错误，如何构建呢

**Comment by sunmooncode** [comment]
看看完整的错误！

**Comment by haomayang1126** [comment]
(Swin) G:\Pythonproject\YOLOX-main_VOC>python tools/train.py -f g:\Pythonproject\YOLOX-main_VOC\exps\example\yolo_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "g:\pythonproject\yolox-main\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 15, in <module>
    from yolox.data import DataPrefetcher
  File "g:\pythonproject\yolox-main\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "g:\pythonproject\yolox-main\yolox\data\datasets\__init__.py", line 11, in <module>
    from .voc import VOCDetection
ModuleNotFoundError: No module named 'yolox.data.datasets.voc'

(Swin) G:\Pythonproject\YOLOX-main_VOC>python tools/train.py -f g:\Pythonproject\YOLOX-main_VOC\exps\example\yolo_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "g:\pythonproject\yolox-main\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 15, in <module>
    from yolox.data import DataPrefetcher
  File "g:\pythonproject\yolox-main\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "g:\pythonproject\yolox-main\yolox\data\datasets\__init__.py", line 11, in <module>
    from .voc import VOCDetection
ModuleNotFoundError: No module named 'yolox.data.datasets.voc'

**Comment by haomayang1126** [comment]
> 看看完整的错误！

Microsoft Windows [版本 10.0.17763.2061]
(c) 2018 Microsoft Corporation。保留所有权利。

(Swin) G:\Pythonproject\YOLOX-main_VOC>python tools/train.py -f g:\Pythonproject\YOLOX-main_VOC\exps\example\yolo_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "g:\pythonproject\yolox-main\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 15, in <module>
    from yolox.data import DataPrefetcher
  File "g:\pythonproject\yolox-main\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "g:\pythonproject\yolox-main\yolox\data\datasets\__init__.py", line 11, in <module>
    from .voc import VOCDetection
ModuleNotFoundError: No module named 'yolox.data.datasets.voc'

(Swin) G:\Pythonproject\YOLOX-main_VOC>python tools/train.py -f g:\Pythonproject\YOLOX-main_VOC\exps\example\yolo_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "g:\pythonproject\yolox-main\yolox\core\__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 15, in <module>
    from yolox.data import DataPrefetcher
  File "g:\pythonproject\yolox-main\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "g:\pythonproject\yolox-main\yolox\data\datasets\__init__.py", line 11, in <module>
    from .voc import VOCDetection
ModuleNotFoundError: No module named 'yolox.data.datasets.voc'

**Comment by haomayang1126** [comment]
![LUS`GWGXWD9%9 }SZSL$AGA](https://user-images.githubusercontent.com/87519787/127844922-55a9975c-3d2a-499e-83e5-8bf15703b705.png)

**Comment by haomayang1126** [comment]
检查了下，这个文件标红了

**Comment by sunmooncode** [comment]
检查yolox/data/dataset/__int__.py里面有没有from .voc import VOCDetection

**Comment by sunmooncode** [comment]
最好的办法就是直接pull

**Comment by sunmooncode** [comment]
你也可以看看这一篇博客：https://blog.csdn.net/qq_39056987/article/details/119002910?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162790005716780261914945%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=162790005716780261914945&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-119002910.first_rank_v2_pc_rank_v29&utm_term=yolox%E8%AE%AD%E7%BB%83%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86&spm=1018.2226.3001.4187

**Comment by haomayang1126** [comment]
> 你也可以看看这一篇博客：https://blog.csdn.net/qq_39056987/article/details/119002910?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162790005716780261914945%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=162790005716780261914945&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-119002910.first_rank_v2_pc_rank_v29&utm_term=yolox%E8%AE%AD%E7%BB%83%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86&spm=1018.2226.3001.4187
谢谢，我重新pull一下可以了
