### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by AIXiaoBaiDemon** [Megvii-BaseDetection/YOLOX#314]
I Can run demo.py with GPU,but when train ,But when I train, it will report the following error.
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by FateScript** [comment]
Please provide more infos like your pytorch version, cuda version, GPU type etc.

**Comment by biel-wangdf3** [comment]
I met the same  error，
python tools/train.py -n yolox-s -d 1 -b 64 --fp16 -o

2021-08-10 10:09:55 | INFO     | yolox.core.trainer:192 - ---> start train epoch1
2021-08-10 10:09:58 | INFO     | yolox.core.trainer:185 - Training of experiment is done and the best AP is 0.00
2021-08-10 10:09:58 | ERROR    | yolox.core.launch:91 - An error has been caught in function 'launch', process 'MainProcess' (13153), thread 'MainThread' (139745820276544):
Traceback (most recent call last):

  File "tools/train.py", line 117, in <module>
    launch(
    └ <function launch at 0x7f16e9bf01f0>

> File "/home/***/workspace/YOLOX/yolox/core/launch.py", line 91, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f16d8db83a0>

  File "tools/train.py", line 103, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f16dac02ee0>
    └ <yolox.core.trainer.Trainer object at 0x7f16d8db7460>

  File "/home/***/workspace/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f16d8e89ee0>
    └ <yolox.core.trainer.Trainer object at 0x7f16d8db7460>

  File "/home/***/workspace/YOLOX/yolox/core/trainer.py", line 79, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f16d8e70160>
    └ <yolox.core.trainer.Trainer object at 0x7f16d8db7460>

  File "/home/***/workspace/YOLOX/yolox/core/trainer.py", line 85, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f16d8e701f0>
    └ <yolox.core.trainer.Trainer object at 0x7f16d8db7460>

  File "/home/***/workspace/YOLOX/yolox/core/trainer.py", line 103, in train_one_iter
    scaled_loss.backward()
    │           └ <function Tensor.backward at 0x7f16ea4dd9d0>
    └ tensor(1047539.4375, device='cuda:0', grad_fn=<MulBackward0>)

  File "/home/***/anaconda3/envs/torch/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
         │    └ <generator object scale_loss at 0x7f1878c3df90>
         └ <contextlib._GeneratorContextManager object at 0x7f187934d340>
  File "/home/***/anaconda3/envs/torch/lib/python3.8/site-packages/apex/amp/handle.py", line 123, in scale_loss
    optimizer._post_amp_backward(loss_scaler)
    │         │                  └ <apex.amp.scaler.LossScaler object at 0x7f16d8dd8d30>
    │         └ <bound method post_backward_no_master_weights of SGD (
    │           Parameter Group 0
    │               dampening: 0
    │               lr: 0
    │               momentum: 0.9
    │               nes...
    └ SGD (
      Parameter Group 0
          dampening: 0
          lr: 0
          momentum: 0.9
          nesterov: True
          weight_decay: 0
      
      Parameter Group ...
  File "/home/***/anaconda3/envs/torch/lib/python3.8/site-packages/apex/amp/_process_optimizer.py", line 249, in post_backward_no_master_weights
    post_backward_models_are_masters(scaler, params, stashed_grads)
    │                                │       │       └ [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None...
    │                                │       └ [Parameter containing:
    │                                │         tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
    │                                │                 1., 1., 1., 1....
    │                                └ <apex.amp.scaler.LossScaler object at 0x7f16d8dd8d30>
    └ <function post_backward_models_are_masters at 0x7f16db707820>
  File "/home/***/anaconda3/envs/torch/lib/python3.8/site-packages/apex/amp/_process_optimizer.py", line 123, in post_backward_models_are_masters
    scaler.unscale(
    │      └ <function LossScaler.unscale at 0x7f16db6db700>
    └ <apex.amp.scaler.LossScaler object at 0x7f16d8dd8d30>
  File "/home/***/anaconda3/envs/torch/lib/python3.8/site-packages/apex/amp/scaler.py", line 114, in unscale
    multi_tensor_applier(LossScaler.multi_tensor_scale_cuda,
    │                    │          └ <built-in method multi_tensor_scale of PyCapsule object at 0x7f16db6b4840>
    │                    └ <class 'apex.amp.scaler.LossScaler'>
    └ <apex.multi_tensor_apply.multi_tensor_apply.MultiTensorApply object at 0x7f16db6b44c0>
  File "/home/***/anaconda3/envs/torch/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
           │  │    └ 65536
           │  └ <apex.multi_tensor_apply.multi_tensor_apply.MultiTensorApply object at 0x7f16db6b44c0>
           └ <built-in method multi_tensor_scale of PyCapsule object at 0x7f16db6b4840>

RuntimeError: CUDA error: no kernel image is available for execution on the device

my environment:
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.20.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.7.1+cu110
[pip3] torch-optimizer==0.1.0
[pip3] torch-tb-profiler==0.1.0
[pip3] torchaudio==0.7.2
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.2+cu110
[conda] efficientnet-pytorch      0.7.0                    pypi_0    pypi
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     1.7.1+cu110              pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torch-tb-profiler         0.1.0                    pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.8.2+cu110              pypi_0    pypi
Pillow (6.2.1)
@FateScript
