### ISSUE TITLE
 AssertionError: Caught AssertionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by kdpan** [Megvii-BaseDetection/YOLOX#345]
Original Traceback (most recent call last):
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/panfulu/anaconda3/envs/atom3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/panfulu/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/panfulu/YOLOX/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/panfulu/YOLOX/yolox/data/datasets/coco.py", line 105, in pull_item
    assert img is not None
AssertionError

**Comment by ruinmessi** [comment]
Img is not read correctly. Plz check your dataset

**Comment by WANGCHAO1996** [comment]
> 
> 
> Img is not read correctly. Plz check your dataset

how to solve it
