### ISSUE TITLE
Openvino inference 

### ISSUE THREAD

**Issue by zhaoxuejun1234** [Megvii-BaseDetection/YOLOX#347]
When I use opencvino demo with yolox_s, it throws 
**_ImportError: /opt/intel/openvino_2021.2.185/deployment_tools/inference_engine/lib/intel64/libinference_engine.so: undefined symbol: _ZN3tbb8internal13numa_topology4fillEPi_**
Is there any idea to solve this problem?

**Comment by Joker316701882** [comment]
@zhaoxuejun1234 Try to upgrade your OpenVINO to the latest version. i.e.,2021.4.xxx

**Comment by zhaoxuejun1234** [comment]
Thank you for your reply.
The reported error shows that I can't import the cv2, is this related to the version issue?

> @zhaoxuejun1234 Try to upgrade your OpenVINO to the latest version. i.e.,2021.4.xxx

**Comment by Joker316701882** [comment]
@zhaoxuejun1234 I'm not sure. We don't have to much experience on OpenVINO.

**Comment by XQF-FOREVER** [comment]
我在使用openvino推理遇到了这个问题
C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\demo\test_yolox>python openvino_inference.py -m D:\Google\模型部署\Raspberrypi+NCS_yolox\yolox_tiny_openvino\yolox_tiny\yolox_10.xml -i D:\Google\模型部署\Raspberrypi+NCS_yolox\YOLOX-main\YOLOX-main\assets\dog.jpg
[ INFO ] Creating Inference Engine
[ INFO ] Reading the network: D:\Google\模型部署\Raspberrypi+NCS_yolox\yolox_tiny_openvino\yolox_tiny\yolox_10.xml
Traceback (most recent call last):
  File "openvino_inference.py", line 158, in <module>
    sys.exit(main())
  File "openvino_inference.py", line 89, in main
    net = ie.read_network(model=args.model)
  File "ie_api.pyx", line 262, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 287, in openvino.inference_engine.ie_api.IECore.read_network
Exception: Path to the weights  doesn't exist or it's a directory
哪位知道这怎么解决，谢谢

**Comment by zhaoxuejun1234** [comment]
路径里尽量不要用中文名，函数可能识别不了路径

**Comment by zhaoxuejun1234** [comment]
> 我在使用openvino推理遇到了这个问题
> C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\demo\test_yolox>python openvino_inference.py -m D:\Google\模型部署\Raspberrypi+NCS_yolox\yolox_tiny_openvino\yolox_tiny\yolox_10.xml -i D:\Google\模型部署\Raspberrypi+NCS_yolox\YOLOX-main\YOLOX-main\assets\dog.jpg
> [ INFO ] Creating Inference Engine
> [ INFO ] Reading the network: D:\Google\模型部署\Raspberrypi+NCS_yolox\yolox_tiny_openvino\yolox_tiny\yolox_10.xml
> Traceback (most recent call last):
> File "openvino_inference.py", line 158, in
> sys.exit(main())
> File "openvino_inference.py", line 89, in main
> net = ie.read_network(model=args.model)
> File "ie_api.pyx", line 262, in openvino.inference_engine.ie_api.IECore.read_network
> File "ie_api.pyx", line 287, in openvino.inference_engine.ie_api.IECore.read_network
> Exception: Path to the weights doesn't exist or it's a directory
> 哪位知道这怎么解决，谢谢

路径里尽量不要用中文名，函数可能识别不了路径
