### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox.evaluators.cocoeval_mr'

### ISSUE THREAD

**Issue by guochunhe** [Megvii-BaseDetection/YOLOX#360]
2021-08-04 09:31:38 | INFO     | yolox.evaluators.coco_evaluator:171 - Evaluate in main process...
2021-08-04 09:31:39 | INFO     | yolox.evaluators.coco_evaluator:204 - Loading and preparing results...
2021-08-04 09:31:39 | INFO     | yolox.evaluators.coco_evaluator:204 - DONE (t=0.13s)
2021-08-04 09:31:39 | INFO     | pycocotools.coco:375 - creating index...
2021-08-04 09:31:39 | INFO     | pycocotools.coco:375 - index created!
2021-08-04 09:31:40 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (8107), thread 'MainThread' (140501385012992):
Traceback (most recent call last):

  File "/data/Projects/py/object_detection/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 206, in evaluate_prediction
    from yolox.layers import COCOeval_opt as COCOeval

  File "/data/Projects/py/object_detection/YOLOX-main/yolox/layers/__init__.py", line 5, in <module>
    from .fast_coco_eval_api import COCOeval_opt

  File "/data/Projects/py/object_detection/YOLOX-main/yolox/layers/fast_coco_eval_api.py", line 16, in <module>
    from yolox import _C

ImportError: cannot import name '_C' from 'yolox' (/data/Projects/py/object_detection/YOLOX-main/yolox/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/data/Projects/py/object_detection/YOLOX-main/tools/eval.py", line 196, in <module>
    launch(
    └ <function launch at 0x7fc805d910d0>

> File "/data/Projects/py/object_detection/YOLOX-main/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7fc7fd2d5b80>

  File "/data/Projects/py/object_detection/YOLOX-main/tools/eval.py", line 181, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function COCOEvaluator.evaluate at 0x7fc7fd53cca0>
                  └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fc7b312b2e0>

  File "/data/Projects/py/object_detection/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 131, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 13.2625,   0.7067, 441.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 1, 'category_id': 8, 'bbox': [573.375, 120.9375, 286.875, 213.0], 'score': 0.9406216144561768, 'segmentation': ...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x7fc7fd53cdc0>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fc7b312b2e0>

  File "/data/Projects/py/object_detection/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 208, in evaluate_prediction
    from .cocoeval_mr import COCOeval

ModuleNotFoundError: No module named 'yolox.evaluators.cocoeval_mr'

**Comment by guochunhe** [comment]
解决了

**Comment by hwangyl** [comment]
大佬怎么解决的，求一波指导
