### ISSUE TITLE
Stuck at Yolox core launch

### ISSUE THREAD

**Issue by awl-anht-nguyen** [Megvii-BaseDetection/YOLOX#372]
Hello, thank you for your excellent work.
But I have trained my own dataset with your repository, I have stuck in Yolox core launch as bellow image
<img width="1425" alt="Screen Shot 2021-08-05 at 11 11 03" src="https://user-images.githubusercontent.com/84887915/128290483-64ddc780-aa9f-4b08-b0c4-d7bb6f1d9c17.png">
I reproduced my own dataset to COCO format dataset, and used your coco.py default, but it used low GPUs and didn't log anything.
Could you help me to investigate what I was wrong? Thank you.

**Comment by awl-anht-nguyen** [comment]
```
2021-08-05 11:26:31.511 | ERROR    | yolox.core.launch:_distributed_worker:193 - Process group URL: tcp://******:49046
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    launch(
  File "/home/anhtn/DomainAdaptation/SynthDataset/YOLOX/yolox/core/launch.py", line 68, in launch
    _distributed_worker(
  File "/home/anhtn/DomainAdaptation/SynthDataset/YOLOX/yolox/core/launch.py", line 186, in _distributed_worker
    dist.init_process_group(
  File "/home/anhtn/miniconda3/envs/yolox/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/anhtn/miniconda3/envs/yolox/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: Socket Timeout
```
And about 20 minutes after, I got this message.

**Comment by ruinmessi** [comment]
Pull the updates first. If it is still stuck, you may try one GPU training and check your  NCCL driver and configuration.
