### ISSUE TITLE
Got TypeError: can't convert np.ndarray of type numpy.ulonglong.

### ISSUE THREAD

**Issue by herunyu** [Megvii-BaseDetection/YOLOX#388]
I am trying to train on custom data, everything works fine until evaluation. Got this weird TypeError. Could someone please take a look?

```
2021-08-05 19:28:37 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (559), thread 'MainThread' (140623185839936):
Traceback (most recent call last):

  File "tools/train.py", line 118, in <module>
    launch(
    └ <function launch at 0x7fe4f90b8d30>

> File "/workspace/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fe50ca4ad30>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fe4eaf8a820>
    └ <yolox.core.trainer.Trainer object at 0x7fe50ca54790>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fe50cf62310>
    └ <yolox.core.trainer.Trainer object at 0x7fe50ca54790>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7fe50cf69670>
    └ <yolox.core.trainer.Trainer object at 0x7fe50ca54790>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 215, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7fe50cf69940>
    └ <yolox.core.trainer.Trainer object at 0x7fe50ca54790>

  File "/workspace/YOLOX/yolox/core/trainer.py", line 306, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x7fe50ca4b310>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x7fe50ca54790>

  File "/workspace/YOLOX/yolox/exp/yolox_base.py", line 251, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7fe50cf5fee0>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fe4e8ccffd0>

  File "/workspace/YOLOX/yolox/evaluators/coco_evaluator.py", line 98, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7fe50ca149a0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7fe4f90a45e0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe4e82a4fa0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7fe4e84225e0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7fe4f90a4700>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe4e82a4fa0>

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fe561ad1b80>
    └ <torch._utils.ExceptionWrapper object at 0x7fe4e84225e0>

  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught TypeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/usr/local/lib/python...
          │    └ <class 'TypeError'>
          └ <torch._utils.ExceptionWrapper object at 0x7fe4e84225e0>

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/collate.py", line 63, in <listcomp>
    return default_collate([torch.as_tensor(b) for b in batch])
TypeError: can't convert np.ndarray of type numpy.ulonglong. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

Here is my [train_log.txt](https://github.com/Megvii-BaseDetection/YOLOX/files/6942405/train_log.txt)
And [test.json.txt](https://github.com/Megvii-BaseDetection/YOLOX/files/6942408/test.json.txt)

**Comment by ruinmessi** [comment]
you may have to manually cast your data type from numpy.ulonglong to uint8 or float. Check your image and labels in your evaldataset first.

**Comment by herunyu** [comment]
> you may have to manually cast your data type from numpy.ulonglong to uint8 or float. Check your image and labels in your evaldataset first.

Thanks for the quick reply. Just want to be clear. Do you mean I need to cast the data type in class COCODataset or during get_data_loader?

**Comment by ruinmessi** [comment]
In your dataset file is better

**Comment by herunyu** [comment]
> In your dataset file is better

Since the annotation is json file, do you mean I need to load the json file convert them to float16 and then dump back to a new json file? Or are you referring to the image dataset? I  not quite sure how to do this with dataset file.
