### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice

### ISSUE THREAD

**Issue by FXY0117** [Megvii-BaseDetection/YOLOX#393]
This is my training commands:
python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py --fp16 -o -c weights/yolox_s.pth.tar
training log:
2021-08-04 14:30:09.288 | INFO     | yolox.core.trainer:before_train:125 - args: Namespace(batch_size=64, ckpt='weights/yolox_s.pth.tar', devices=None, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=False, local_rank=0, machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2021-08-04 14:30:09.291 | INFO     | yolox.core.trainer:before_train:126 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 8                          │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ random_size      │ (14, 26)                   │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ scale            │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mscale           │ (0.8, 1.6)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ perspective      │ 0.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 5                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 10                         │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_voc_s'              │
├──────────────────┼────────────────────────────┤
│ test_size        │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
╘══════════════════╧════════════════════════════╛
2021-08-04 14:30:09.295 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (14416), thread 'MainThread' (23260):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=64, ckpt='weights/yolox_s.pth.tar', devices=None, dist_backend='nccl', dist_url=None, exp_file='exps/exa...
          └ ╒══════════════════╤════════════════════════════╕
            │ keys             │ values                     │
            ╞══════════════════╪═════...

> File "d:\mmdetection\yolox-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════╕
    │            │ keys             │ values                     │
    │            ╞══════════════════╪════...
    └ <function main at 0x0000019D0818A558>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000019D093823A8>
    └ <yolox.core.trainer.Trainer object at 0x0000019D0A907E48>

  File "d:\mmdetection\yolox-main\yolox\core\trainer.py", line 69, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x0000019D0A8AD8B8>
    └ <yolox.core.trainer.Trainer object at 0x0000019D0A907E48>

  File "d:\mmdetection\yolox-main\yolox\core\trainer.py", line 129, in before_train
    torch.cuda.set_device(self.local_rank)
    │     │    │          │    └ 0
    │     │    │          └ <yolox.core.trainer.Trainer object at 0x0000019D0A907E48>
    │     │    └ <function set_device at 0x0000019D78EFCCA8>
    │     └ <module 'torch.cuda' from 'D:\\Anaconda\\envs\\yolox\\lib\\site-packages\\torch\\cuda\\__init__.py'>
    └ <module 'torch' from 'D:\\Anaconda\\envs\\yolox\\lib\\site-packages\\torch\\__init__.py'>

  File "D:\Anaconda\envs\yolox\lib\site-packages\torch\cuda\__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
    │     │                  └ 0
    │     └ <module 'torch._C' from 'D:\\Anaconda\\envs\\yolox\\lib\\site-packages\\torch\\_C.cp37-win_amd64.pyd'>
    └ <module 'torch' from 'D:\\Anaconda\\envs\\yolox\\lib\\site-packages\\torch\\__init__.py'>

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
I don't know how to solve it.

**Comment by zhangming8** [comment]
did you install gpu pytorch?

**Comment by FXY0117** [comment]
是的

**Comment by FXY0117** [comment]
> 是的

windows上装有cuda

**Comment by FXY0117** [comment]
> 你安装了GPU pytorch吗？
是的，windows上装了cuda

**Comment by FXY0117** [comment]
是的

**Comment by FateScript** [comment]
What if you run:
```python3
import torch
torch.cuda.set_device(0)
```
on your device?

It seems that your torch is not install in the right way,  maybe [tutorial](https://pytorch.org/get-started/locally/) is all your need.

**Comment by FXY0117** [comment]
> What if you run
> 
> ```python
> import torch
> torch.cuda.set_device(0)
> ```
> 
> on your device?
> 
> It seems that your torch is not installed in the right way, maybe [tutorial](https://pytorch.org/get-started/locally/) is all your need.
OK, I'll try on this way, thank you for your help.

**Comment by zhangming8** [comment]
try this command:
import torch
torch.rand([2]).cuda()

make sure it works.

**Comment by FXY0117** [comment]
> try this command:
> import torch
> torch.rand([2]).cuda()
> 
> make sure it works.
Excuse me , this command should add whether in train.py or not ?

**Comment by zhangming8** [comment]
> > try this command:
> > import torch
> > torch.rand([2]).cuda()
> > make sure it works.
> > Excuse me , this command should add whether in train.py or not ?

Not, that just tests whether your gpu-pytorch is OK.

**Comment by FXY0117** [comment]
> > > 试试这个命令：
> > > import torch 
> > > torch.rand([2]).cuda()
> > > 确保它有效。
> > > 请问，这个命令是否应该添加在train.py中？
> 
> 不是，那只是测试您的 gpu-pytorch 是否正常。

ok, I have tryied it, it shows that:
>>> import torch
>>> torch.rand([2]).cuda()
tensor([0.1837, 0.0133], device='cuda:0')
it seems ok.

**Comment by FXY0117** [comment]
> What if you run
> 
> ```python
> import torch
> torch.cuda.set_device(0)
> ```
> 
> on your device?
> 
> It seems that your torch is not installed in the right way, maybe [tutorial](https://pytorch.org/get-started/locally/) is all your need.

Excuse me , this command should add whether in train.py or not ?

**Comment by ttxlla** [comment]
How to deal with this please？
2022-03-26 10:36:18 | INFO     | yolox.core.trainer:129 - args: Namespace(batch_size=16, cache=False, ckpt='weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=False, logger='tensorboard', machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2022-03-26 10:36:18 | INFO     | yolox.core.trainer:130 - exp value:
╒═══════════════════╤════════════════════════════╕
│ keys              │ values                     │
╞═══════════════════╪════════════════════════════╡
│ seed              │ None                       │
├───────────────────┼────────────────────────────┤
│ output_dir        │ './YOLOX_outputs'          │
├───────────────────┼────────────────────────────┤
│ print_interval    │ 10                         │
├───────────────────┼────────────────────────────┤
│ eval_interval     │ 10                         │
├───────────────────┼────────────────────────────┤
│ num_classes       │ 1                          │
├───────────────────┼────────────────────────────┤
│ depth             │ 0.33                       │
├───────────────────┼────────────────────────────┤
│ width             │ 0.5                        │
├───────────────────┼────────────────────────────┤
│ act               │ 'silu'                     │
├───────────────────┼────────────────────────────┤
│ data_num_workers  │ 4                          │
├───────────────────┼────────────────────────────┤
│ input_size        │ (640, 640)                 │
├───────────────────┼────────────────────────────┤
│ multiscale_range  │ 5                          │
├───────────────────┼────────────────────────────┤
│ data_dir          │ None                       │
├───────────────────┼────────────────────────────┤
│ train_ann         │ 'instances_train2017.json' │
├───────────────────┼────────────────────────────┤
│ val_ann           │ 'instances_val2017.json'   │
├───────────────────┼────────────────────────────┤
│ test_ann          │ 'instances_test2017.json'  │
├───────────────────┼────────────────────────────┤
│ mosaic_prob       │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ mixup_prob        │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ hsv_prob          │ 1.0                        │
├───────────────────┼────────────────────────────┤
│ flip_prob         │ 0.5                        │
├───────────────────┼────────────────────────────┤
│ degrees           │ 10.0                       │
├───────────────────┼────────────────────────────┤
│ translate         │ 0.1                        │
├───────────────────┼────────────────────────────┤
│ mosaic_scale      │ (0.1, 2)                   │
├───────────────────┼────────────────────────────┤
│ enable_mixup      │ True                       │
├───────────────────┼────────────────────────────┤
│ mixup_scale       │ (0.5, 1.5)                 │
├───────────────────┼────────────────────────────┤
│ shear             │ 2.0                        │
├───────────────────┼────────────────────────────┤
│ warmup_epochs     │ 1                          │
├───────────────────┼────────────────────────────┤
│ max_epoch         │ 300                        │
├───────────────────┼────────────────────────────┤
│ warmup_lr         │ 0                          │
├───────────────────┼────────────────────────────┤
│ min_lr_ratio      │ 0.05                       │
├───────────────────┼────────────────────────────┤
│ basic_lr_per_img  │ 0.00015625                 │
├───────────────────┼────────────────────────────┤
│ scheduler         │ 'yoloxwarmcos'             │
├───────────────────┼────────────────────────────┤
│ no_aug_epochs     │ 15                         │
├───────────────────┼────────────────────────────┤
│ ema               │ True                       │
├───────────────────┼────────────────────────────┤
│ weight_decay      │ 0.0005                     │
├───────────────────┼────────────────────────────┤
│ momentum          │ 0.9                        │
├───────────────────┼────────────────────────────┤
│ save_history_ckpt │ True                       │
├───────────────────┼────────────────────────────┤
│ exp_name          │ 'yolox_voc_s'              │
├───────────────────┼────────────────────────────┤
│ test_size         │ (640, 640)                 │
├───────────────────┼────────────────────────────┤
│ test_conf         │ 0.01                       │
├───────────────────┼────────────────────────────┤
│ nmsthre           │ 0.65                       │
╘═══════════════════╧════════════════════════════╛
2022-03-26 10:36:20 | INFO     | yolox.core.trainer:136 - Model Summary: Params: 8.94M, Gflops: 26.64
2022-03-26 10:36:20 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (477), thread 'MainThread' (140354340575104):
Traceback (most recent call last):

  File "tools/train.py", line 139, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='ex...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/drive/MyDrive/Colab/YOLOX-main/YOLOX-main/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fa6c7fdfe60>

  File "tools/train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fa5b7126ef0>
    └ <yolox.core.trainer.Trainer object at 0x7fa5ab377510>

  File "/content/drive/MyDrive/Colab/YOLOX-main/YOLOX-main/yolox/core/trainer.py", line 73, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fa5ab6bd290>
    └ <yolox.core.trainer.Trainer object at 0x7fa5ab377510>

  File "/content/drive/MyDrive/Colab/YOLOX-main/YOLOX-main/yolox/core/trainer.py", line 138, in before_train
    model.to(self.device)
    │     │  └ <yolox.core.trainer.Trainer object at 0x7fa5ab377510>
    │     └ <function Module.to at 0x7fa5c1321f80>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

AttributeError: 'Trainer' object has no attribute 'device'

**Comment by rahuja23** [comment]
I am getting the same issue. I am having a Mac M1 is there any solution for this?

**Comment by Leeway-95** [comment]
I am getting the same issue on Mac M2. Do you have some solutions?
