### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by byq-luo** [Megvii-BaseDetection/YOLOX#394]
(yolox) PS H:\traffic_luo\YOLOX> python tools/demo.py image -n yolox-s -c ./checkpoints/yolox_s.pth.tar --path ./assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
2021-08-06 13:44:08.733 | INFO     | __main__:main:240 - Args: Namespace(camid=0, ckpt='./checkpoints/yolox_s.pth.tar', conf=0.25, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, name='yolox-s', nms=0.45, path='./assets/dog.jpg', save_result=True, trt=False, tsize=640)
2021-08-06 13:44:08.898 | INFO     | __main__:main:250 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-08-06 13:44:10.188 | INFO     | __main__:main:261 - loading checkpoint
2021-08-06 13:44:10.293 | INFO     | __main__:main:265 - loaded checkpoint done.
2021-08-06 13:44:11.332 | INFO     | __main__:inference:151 - Infer time: 1.0054s
Traceback (most recent call last):
  File "tools/demo.py", line 296, in <module>
    main(exp, args)
  File "tools/demo.py", line 287, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 181, in image_demo
    result_image = predictor.visual(outputs[0], img_info, predictor.confthre)
  File "tools/demo.py", line 169, in visual
    vis_res = vis(img, bboxes, scores, cls, cls_conf, self.cls_names)
  File "h:\traffic_luo\yolox-main\yolox\utils\visualize.py", line 25, in vis
    text = '{}:{:.1f}%'.format(class_names[cls_id], score * 100)
IndexError: tuple index out of range

**Comment by zhuzhuzhu111222** [comment]
# ---------------- dataloader config ---------------- #
        # set worker to 4 for shorter dataloader init time
        self.data_num_workers = 4
        self.input_size = (640, 640)
        self.random_size = (14, 26)
        self.data_dir = None
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"
may be you modify  self.data_num_workers

**Comment by 18789447455** [comment]
> ```
>     # ---------------- dataloader config ---------------- #
>     # set worker to 4 for shorter dataloader init time
>     self.data_num_workers = 4
>     self.input_size = (640, 640)
>     self.random_size = (14, 26)
>     self.data_dir = None
>     self.train_ann = "instances_train2017.json"
>     self.val_ann = "instances_val2017.json"
> ```
> 
> may be you modify self.data_num_workers

应该修改为多少

**Comment by 18789447455** [comment]
> (yolox) PS H:\traffic_luo\YOLOX> python tools/demo.py image -n yolox-s -c ./checkpoints/yolox_s.pth.tar --path ./assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu 2021-08-06 13:44:08.733 | INFO | **main**:main:240 - Args: Namespace(camid=0, ckpt='./checkpoints/yolox_s.pth.tar', conf=0.25, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, name='yolox-s', nms=0.45, path='./assets/dog.jpg', save_result=True, trt=False, tsize=640) 2021-08-06 13:44:08.898 | INFO | **main**:main:250 - Model Summary: Params: 8.97M, Gflops: 26.81 2021-08-06 13:44:10.188 | INFO | **main**:main:261 - loading checkpoint 2021-08-06 13:44:10.293 | INFO | **main**:main:265 - loaded checkpoint done. 2021-08-06 13:44:11.332 | INFO | **main**:inference:151 - Infer time: 1.0054s Traceback (most recent call last): File "tools/demo.py", line 296, in main(exp, args) File "tools/demo.py", line 287, in main image_demo(predictor, vis_folder, args.path, current_time, args.save_result) File "tools/demo.py", line 181, in image_demo result_image = predictor.visual(outputs[0], img_info, predictor.confthre) File "tools/demo.py", line 169, in visual vis_res = vis(img, bboxes, scores, cls, cls_conf, self.cls_names) File "h:\traffic_luo\yolox-main\yolox\utils\visualize.py", line 25, in vis text = '{}:{:.1f}%'.format(class_names[cls_id], score * 100) IndexError: tuple index out of range

请问你这个问题解决了吗
