### ISSUE TITLE
datasets选择性报错

### ISSUE THREAD

**Issue by Zomcxj** [Megvii-BaseDetection/YOLOX#419]
使用自己标注的cat数据集可以跑train    而网上下载的肿瘤数据集出现报错
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\yolox-0.1.0-py3.8-win-amd64.egg\yolox\data\datasets\datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\yolox-0.1.0-py3.8-win-amd64.egg\yolox\data\datasets\mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "D:\JetBrains\Anaconda3\envs\yolox\lib\site-packages\yolox-0.1.0-py3.8-win-amd64.egg\yolox\data\datasets\voc.py", line 143, in pull_item
    height, width, _ = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

肿瘤的xml标签缺少path

**Comment by pazifik-cyber** [comment]
我也遇到一样的问题，请问你解决了么？

**Comment by pazifik-cyber** [comment]
似乎是数据的问题，网上爬的图片有些并不是24位深度的，重新保存为24位可以解决。

**Comment by Zomcxj** [comment]
> 似乎是数据的问题，网上爬的图片有些并不是24位深度的，重新保存为24位可以解决。

我这都是24位的，应该是图片类型不一样， 肿瘤数据集是png类型的    YOLOX代码只能读取jpg，jpeg的
