### ISSUE TITLE
利用自己的数据集训练出来的模型跑，结果有问题：

### ISSUE THREAD

**Issue by liuwei3612** [Megvii-BaseDetection/YOLOX#431]
我用自己的数据集训练出来的模型跑，出现下面的问题，请大佬们看下：
 python3 tools/demo.py image -n yolox-tiny -c pth/best_ckpt.pth --path assets/2021_07_16_14_36_41_C1.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device [cpu]
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-j_8jv8kd because the default path (/home/ewb/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2021-08-09 17:32:33.085 | INFO     | __main__:main:239 - Args: Namespace(camid=0, ckpt='pth/best_ckpt.pth', conf=0.25, demo='image', device='[cpu]', exp_file=None, experiment_name='yolox_tiny', fp16=False, fuse=False, name='yolox-tiny', nms=0.45, path='assets/2021_07_16_14_36_41_C1.jpg', save_result=True, trt=False, tsize=640)
/home/ewb/anaconda3/envs/YOLOX/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-08-09 17:32:34.280 | INFO     | __main__:main:249 - Model Summary: Params: 5.06M, Gflops: 15.27
2021-08-09 17:32:34.287 | INFO     | __main__:main:260 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo.py", line 295, in <module>
    main(exp, args)
  File "tools/demo.py", line 263, in main
    model.load_state_dict(ckpt["model"])
  File "/home/ewb/anaconda3/envs/YOLOX/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
	size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([15, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 96, 1, 1]).
	size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([15]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([15, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 96, 1, 1]).
	size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([15]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([15, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 96, 1, 1]).
	size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([15]) from checkpoint, the shape in current model is torch.Size([80]).

**Comment by jingruhou** [comment]
目测你的COCO_CLASSES没有改吧？ @liuwei3612

**Comment by liuwei3612** [comment]
> 目测你的COCO_CLASSES没有改吧？ @liuwei3612

谢谢你的回复，改了，还是一样的问题

**Comment by qingshanjiu** [comment]
我也遇到过这个问题不过是在训练过程中，问题原因是我的resume改成了ture。接着预训练模型训练去了，导致了一样的报错，虽然问题产生过程不一样，但希望能对你产生启发。

**Comment by zhangming8** [comment]
self.num_classes改了吗

**Comment by juechenzp** [comment]
请问你解决了吗，我也遇到了这个问题了

**Comment by ymw123** [comment]
除了类别数目，输入尺寸也要改

> > 目测你的COCO_CLASSES没有改吧？ @liuwei3612
> 
> 谢谢你的回复，改了，还是一样的问题

除了类别数目，输入尺寸也要改

**Comment by sheyu1005** [comment]
你好，请问你的问题解决了么

**Comment by lixiangMindSpore** [comment]
[cpu]不需要打括号

**Comment by Mobu59** [comment]
修改yolox/exp/yolox_base.py里面的self.num_classes=你的类别数

**Comment by wwwCielwww** [comment]
需要指定训练时exp文件的路径：`--expn /path/to/exp.py`
例如：`--expn exps/default/yolox_s.py`

**Comment by Best-effort** [comment]
请问一下您解决了吗？

**Comment by ShuShuai163** [comment]
请问您解决了吗

**Comment by qwtoe** [comment]
我是因为之前开了resume:True ，改成False就好啦

**Comment by zhaojiacheng123456** [comment]
> 

resume 是什么设定，在哪个文件里面修改

**Comment by xxdexh** [comment]
>关了resume如何接着之前的断点训练呢
