### ISSUE TITLE
转换成onnx之后想转瑞芯微的rknn格式失败，请问是否有rknn转换指导

### ISSUE THREAD

**Issue by BenjaminLiu1003** [Megvii-BaseDetection/YOLOX#434]
如题，在使用onnx验证之后（已经指定opset=10），想转成瑞芯微使用的rknn格式文件，报错如下，麻烦帮忙看下，谢谢了！

> I Try match Slice_Slice_9:out0
W Not match tensor Slice_Slice_9:out0 
E Try match Slice_Slice_9:out0 failed, catch exception!
W ----------------Warning(2)----------------
E Catch exception when loading onnx model: /home/benjamin/disk1/Work/NN_ALGO/yolo/YOLOX/yolox_s.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 826, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 728, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._onnx_push_ready_tensor
E TypeError: 'NoneType' object is not iterable
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 264, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 135, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 121, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 832, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.match_paragraph_and_param
E   File "rknn/api/rknn_log.py", line 312, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Try match Slice_Slice_9:out0 failed, catch exception!
--> Load onnx model failed!

**Comment by ruinmessi** [comment]
Seems rknn didn't support slice operation for Focus. You may have to replace the first layer of Focus with a conv 3x3-stride-2 layer and finetune your model first.

**Comment by BenjaminLiu1003** [comment]
没有

**Comment by BenjaminLiu1003** [comment]
请问一下

> Seems rknn didn't support slice operation for Focus. You may have to replace the first layer of Focus with a conv 3x3-stride-2 layer and finetune your model first.

rknn现在只支持opset=9,请问一下可以实现opset=9的onnx转换么？谢谢。

**Comment by ymw123** [comment]
我设置opset=9会报错，onnx直接不能转换，设置opset=10或11，可以成功转换为rknn，但是模型与原始模型不一致，差异太大，而且转换过程中似乎提示了错误信息，但是也能成功转换。

**Comment by ymw123** [comment]
我用的rknn1.7.1版本

**Comment by BenjaminLiu1003** [comment]
> pytorch直接转rknn，会提示有几个op不支持，但是先转onnx再转rknn，就没有提示op不支持的问题，所以目前只能通过onnx转换rknn。我是直接用官方的pth模型和onnx来转换的，没有自己训练模型，因为rknn目前只支持torch1.6，所以我怀疑是torch版本太高，所以我想自己用torch1.6训练模型，然后再设置opset=9来转换，看是否可以成功。

重新训练的话，我有yolov5的，而且太浪费时间了，就是想直接用它的，为什么瑞芯微告诉我的是最新的是1.6.1？你用的什么板子？

**Comment by ymw123** [comment]
> > pytorch直接转rknn，会提示有几个op不支持，但是先转onnx再转rknn，就没有提示op不支持的问题，所以目前只能通过onnx转换rknn。我是直接用官方的pth模型和onnx来转换的，没有自己训练模型，因为rknn目前只支持torch1.6，所以我怀疑是torch版本太高，所以我想自己用torch1.6训练模型，然后再设置opset=9来转换，看是否可以成功。
> 
> 重新训练的话，我有yolov5的，而且太浪费时间了，就是想直接用它的，为什么瑞芯微告诉我的是最新的是1.6.1？你用的什么板子？

 你这个错误是rk1.6出现的，我也出现过，使用rk1.7就没有错误了，这是瑞芯微内部提供给我们的preview版本，增加了一些op的支持。还是想转换yolox，毕竟速度比yolov5快。你有尝试转换nanodet吗？

**Comment by BenjaminLiu1003** [comment]
> > > pytorch直接转rknn，会提示有几个op不支持，但是先转onnx再转rknn，就没有提示op不支持的问题，所以目前只能通过onnx转换rknn。我是直接用官方的pth模型和onnx来转换的，没有自己训练模型，因为rknn目前只支持torch1.6，所以我怀疑是torch版本太高，所以我想自己用torch1.6训练模型，然后再设置opset=9来转换，看是否可以成功。
> > 
> > 
> > 重新训练的话，我有yolov5的，而且太浪费时间了，就是想直接用它的，为什么瑞芯微告诉我的是最新的是1.6.1？你用的什么板子？
> 
> 你这个错误是rk1.6出现的，我也出现过，使用rk1.7就没有错误了，这是瑞芯微内部提供给我们的preview版本，增加了一些op的支持。还是想转换yolox，毕竟速度比yolov5快。你有尝试转换nanodet吗？

nanodet没用过,你在RK什么板子试的，要不加个好友交流一下吧。

**Comment by ruinmessi** [comment]
@ymw123 我们也没有说比v5快啊。。。不过我们也注意到了v5的一些op兼容性一般。后续会有用conv换掉Focus的模型放出来。

**Comment by ymw123** [comment]
> @ymw123 我们也没有说比v5快啊。。。不过我们也注意到了v5的一些op兼容性一般。后续会有用conv换掉Focus的模型放出来。

我是推测的边缘设备上比v5快，因为在pc上比v5快一点

**Comment by ymw123** [comment]
> > > > pytorch直接转rknn，会提示有几个op不支持，但是先转onnx再转rknn，就没有提示op不支持的问题，所以目前只能通过onnx转换rknn。我是直接用官方的pth模型和onnx来转换的，没有自己训练模型，因为rknn目前只支持torch1.6，所以我怀疑是torch版本太高，所以我想自己用torch1.6训练模型，然后再设置opset=9来转换，看是否可以成功。
> > > 
> > > 
> > > 重新训练的话，我有yolov5的，而且太浪费时间了，就是想直接用它的，为什么瑞芯微告诉我的是最新的是1.6.1？你用的什么板子？
> > 
> > 
> > 你这个错误是rk1.6出现的，我也出现过，使用rk1.7就没有错误了，这是瑞芯微内部提供给我们的preview版本，增加了一些op的支持。还是想转换yolox，毕竟速度比yolov5快。你有尝试转换nanodet吗？
> 
> nanodet没用过,你在RK什么板子试的，要不加个好友交流一下吧。

我使用的是rk1806

**Comment by ymw123** [comment]
这是使用rk1.7.0转onnx成功的提示，只是转换后的rknn模型输出差异太大，中间有些层转换出错了。
![图片](https://user-images.githubusercontent.com/23358682/129008668-9ba6fa4f-2130-4e0d-beae-7b8b103382b4.png)
使用pt模型直接转rknn会提示['aten::expand', 'aten::copy_', 'aten::full', 'aten::mul_', 'aten::meshgrid']这些op不支持。

**Comment by ymw123** [comment]
@BenjaminLiu1003 github好像不可以私信

**Comment by BenjaminLiu1003** [comment]
@ymw123 我用了1.7.0的rknn-toolkit还是连转换完成都不行啊。。。

**Comment by ymw123** [comment]
@BenjaminLiu1003 weixin:YMWO_o

**Comment by liuwenhua6666** [comment]
我转成功了

**Comment by liuwenhua6666** [comment]
推理时间300ms左右
