### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ilem777** [Megvii-BaseDetection/YOLOX#435]
Hi developer, I used your code to run the yolox-s model with the command `python tools/train.py --name yolox-s --exp_file exps/default/yolox_s.py --devices 1 --batch-size 4 --occupy --ckpt pretrained-weights/yolox_s.pth.tar`, I am using a custom dataset in COCO format, which has been placed in the “datasets” folder as required. However, the following error occurs.
```
2021-08-10 11:18:34 | INFO     | yolox.core.trainer:192 - ---> start train epoch1
2021-08-10 11:18:46 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 20/400, mem: 3169Mb, iter_time: 0.598s, data_time: 0.002s, total_loss: 10.4, iou_loss: 2.9, l1_loss: 0.0,
conf_loss: 4.9, cls_loss: 2.6, lr: 6.250e-08, size: 832, ETA: 19:56:38
2021-08-10 11:18:54 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 40/400, mem: 3169Mb, iter_time: 0.408s, data_time: 0.001s, total_loss: 12.7, iou_loss: 3.2, l1_loss: 0.0,
conf_loss: 7.2, cls_loss: 2.4, lr: 2.500e-07, size: 640, ETA: 16:46:04
2021-08-10 11:19:01 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 60/400, mem: 3169Mb, iter_time: 0.342s, data_time: 0.001s, total_loss: 12.8, iou_loss: 3.1, l1_loss: 0.0,
conf_loss: 7.0, cls_loss: 2.7, lr: 5.625e-07, size: 480, ETA: 14:58:39
2021-08-10 11:19:09 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 80/400, mem: 3169Mb, iter_time: 0.398s, data_time: 0.001s, total_loss: 11.3, iou_loss: 2.6, l1_loss: 0.0,
conf_loss: 5.8, cls_loss: 2.9, lr: 1.000e-06, size: 576, ETA: 14:32:33
2021-08-10 11:19:22 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 100/400, mem: 3169Mb, iter_time: 0.620s, data_time: 0.001s, total_loss: 11.9, iou_loss: 3.4, l1_loss: 0.0,
 conf_loss: 6.1, cls_loss: 2.3, lr: 1.563e-06, size: 768, ETA: 15:45:47
2021-08-10 11:19:30 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 120/400, mem: 3169Mb, iter_time: 0.397s, data_time: 0.001s, total_loss: 10.4, iou_loss: 2.9, l1_loss: 0.0,
 conf_loss: 5.5, cls_loss: 2.0, lr: 2.250e-06, size: 640, ETA: 15:20:13
2021-08-10 11:19:35 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 140/400, mem: 3169Mb, iter_time: 0.261s, data_time: 0.001s, total_loss: 11.5, iou_loss: 3.3, l1_loss: 0.0,
 conf_loss: 5.7, cls_loss: 2.5, lr: 3.063e-06, size: 768, ETA: 14:23:05
2021-08-10 11:19:45 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 160/400, mem: 3169Mb, iter_time: 0.491s, data_time: 0.001s, total_loss: 10.2, iou_loss: 3.2, l1_loss: 0.0,
 conf_loss: 4.9, cls_loss: 2.1, lr: 4.000e-06, size: 608, ETA: 14:37:43
2021-08-10 11:19:52 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 180/400, mem: 3169Mb, iter_time: 0.295s, data_time: 0.001s, total_loss: 9.8, iou_loss: 3.0, l1_loss: 0.0,
conf_loss: 4.7, cls_loss: 2.1, lr: 5.063e-06, size: 768, ETA: 14:05:28
2021-08-10 11:20:02 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 200/400, mem: 3169Mb, iter_time: 0.527s, data_time: 0.001s, total_loss: 10.2, iou_loss: 2.7, l1_loss: 0.0,
 conf_loss: 5.4, cls_loss: 2.2, lr: 6.250e-06, size: 576, ETA: 14:26:02
2021-08-10 11:20:12 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 220/400, mem: 3169Mb, iter_time: 0.474s, data_time: 0.001s, total_loss: 8.8, iou_loss: 2.8, l1_loss: 0.0,
conf_loss: 4.1, cls_loss: 1.9, lr: 7.563e-06, size: 544, ETA: 14:33:09
2021-08-10 11:20:17 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 240/400, mem: 3169Mb, iter_time: 0.243s, data_time: 0.001s, total_loss: 9.3, iou_loss: 3.2, l1_loss: 0.0,
conf_loss: 4.5, cls_loss: 1.7, lr: 9.000e-06, size: 480, ETA: 14:00:38
2021-08-10 11:20:23 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 260/400, mem: 3169Mb, iter_time: 0.283s, data_time: 0.001s, total_loss: 8.1, iou_loss: 2.6, l1_loss: 0.0,
conf_loss: 3.8, cls_loss: 1.7, lr: 1.056e-05, size: 768, ETA: 13:39:15
2021-08-10 11:20:30 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 280/400, mem: 3169Mb, iter_time: 0.352s, data_time: 0.001s, total_loss: 9.1, iou_loss: 2.8, l1_loss: 0.0,
conf_loss: 4.7, cls_loss: 1.6, lr: 1.225e-05, size: 640, ETA: 13:30:48
2021-08-10 11:20:42 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 300/400, mem: 3169Mb, iter_time: 0.566s, data_time: 0.001s, total_loss: 9.3, iou_loss: 3.1, l1_loss: 0.0,
conf_loss: 4.4, cls_loss: 1.9, lr: 1.406e-05, size: 832, ETA: 13:51:54
2021-08-10 11:20:51 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 320/400, mem: 3169Mb, iter_time: 0.472s, data_time: 0.001s, total_loss: 9.5, iou_loss: 3.0, l1_loss: 0.0,
conf_loss: 4.7, cls_loss: 1.8, lr: 1.600e-05, size: 800, ETA: 13:58:39
2021-08-10 11:20:59 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 340/400, mem: 3169Mb, iter_time: 0.391s, data_time: 0.001s, total_loss: 7.6, iou_loss: 2.3, l1_loss: 0.0,
conf_loss: 3.7, cls_loss: 1.6, lr: 1.806e-05, size: 576, ETA: 13:55:07
2021-08-10 11:21:05 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 360/400, mem: 3169Mb, iter_time: 0.268s, data_time: 0.001s, total_loss: 7.3, iou_loss: 2.4, l1_loss: 0.0,
conf_loss: 3.4, cls_loss: 1.5, lr: 2.025e-05, size: 576, ETA: 13:38:19
2021-08-10 11:21:11 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 380/400, mem: 3169Mb, iter_time: 0.311s, data_time: 0.001s, total_loss: 7.8, iou_loss: 2.6, l1_loss: 0.0,
conf_loss: 3.7, cls_loss: 1.5, lr: 2.256e-05, size: 448, ETA: 13:27:46
2021-08-10 11:21:20 | INFO     | yolox.core.trainer:243 - epoch: 1/300, iter: 400/400, mem: 3169Mb, iter_time: 0.433s, data_time: 0.002s, total_loss: 7.2, iou_loss: 2.5, l1_loss: 0.0,
conf_loss: 3.5, cls_loss: 1.2, lr: 2.500e-05, size: 704, ETA: 13:30:27
2021-08-10 11:21:20 | INFO     | yolox.core.trainer:319 - Save weights to ./YOLOX_outputs\yolox_s
100%|##################################################################################################################################################| 50/50 [00:12<00:00,  3.97it/s]
2021-08-10 11:21:33 | INFO     | yolox.evaluators.coco_evaluator:171 - Evaluate in main process...
2021-08-10 11:21:33 | INFO     | yolox.evaluators.coco_evaluator:204 - Loading and preparing results...
2021-08-10 11:21:33 | INFO     | yolox.evaluators.coco_evaluator:204 - DONE (t=0.08s)
2021-08-10 11:21:33 | INFO     | pycocotools.coco:362 - creating index...
2021-08-10 11:21:33 | INFO     | pycocotools.coco:362 - index created!
2021-08-10 11:21:33 | INFO     | yolox.core.trainer:185 - Training of experiment is done and the best AP is 0.00
2021-08-10 11:21:33 | ERROR    | yolox.core.launch:91 - An error has been caught in function 'launch', process 'MainProcess' (12708), thread 'MainThread' (16660):
Traceback (most recent call last):

  File "tools\train.py", line 117, in <module>
    launch(
    └ <function launch at 0x00000240E9664E50>

> File "f:\pycharmprojects\yolox_env\yolox\yolox\core\launch.py", line 91, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x00000240EA831820>

  File "tools\train.py", line 103, in main
    trainer.train()
    │       └ <function Trainer.train at 0x00000240E9B2EE50>
    └ <yolox.core.trainer.Trainer object at 0x00000240EA83BEB0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\core\trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x00000240EA7ED430>
    └ <yolox.core.trainer.Trainer object at 0x00000240EA83BEB0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\core\trainer.py", line 80, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x00000240EA80AD30>
    └ <yolox.core.trainer.Trainer object at 0x00000240EA83BEB0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\core\trainer.py", line 212, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x00000240EA810040>
    └ <yolox.core.trainer.Trainer object at 0x00000240EA83BEB0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\core\trainer.py", line 303, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x00000240EA831D30>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x00000240EA83BEB0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\exp\yolox_base.py", line 251, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x00000240EA7ED9D0>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002408876BEE0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\evaluators\coco_evaluator.py", line 131, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 3.9300,  0.3992, 49.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 1, 'category_id': 1, 'bbox': [339.42138671875, 211.710205078125, 271.8203125, 339.4736328125], 'score': 0.45420...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x00000240EA7EDAF0>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002408876BEE0>

  File "f:\pycharmprojects\yolox_env\yolox\yolox\evaluators\coco_evaluator.py", line 212, in evaluate_prediction
    cocoEval = COCOeval(cocoGt, cocoDt, annType[1])
               │        │       │       └ ['segm', 'bbox', 'keypoints']
               │        │       └ <pycocotools.coco.COCO object at 0x00000240EA83B5B0>
               │        └ <pycocotools.coco.COCO object at 0x00000240F3C280A0>
               └ <class 'yolox.layers.fast_coco_eval_api.COCOeval_opt'>

  File "D:\Anaconda3\envs\yolox_env\lib\site-packages\pycocotools\cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
    │    │        │              └ 'bbox'
    │    │        └ <class 'pycocotools.cocoeval.Params'>
    │    └ {}
    └ <yolox.layers.fast_coco_eval_api.COCOeval_opt object at 0x00000240EA83BD60>

  File "D:\Anaconda3\envs\yolox_env\lib\site-packages\pycocotools\cocoeval.py", line 527, in __init__
    self.setDetParams()
    │    └ <function Params.setDetParams at 0x00000241003BB310>
    └ <pycocotools.cocoeval.Params object at 0x00000240F4819190>

  File "D:\Anaconda3\envs\yolox_env\lib\site-packages\pycocotools\cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
    │              │  │                  │  └ <function round_ at 0x00000240D1264EE0>
    │              │  │                  └ <module 'numpy' from 'D:\\Anaconda3\\envs\\yolox_env\\lib\\site-packages\\numpy\\__init__.py'>
    │              │  └ <function linspace at 0x00000240D12D8550>
    │              └ <module 'numpy' from 'D:\\Anaconda3\\envs\\yolox_env\\lib\\site-packages\\numpy\\__init__.py'>
    └ <pycocotools.cocoeval.Params object at 0x00000240F4819190>

  File "<__array_function__ internals>", line 5, in linspace

  File "D:\Anaconda3\envs\yolox_env\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
          │        │     └ 10.0
          │        └ <built-in function index>
          └ <module 'operator' from 'D:\\Anaconda3\\envs\\yolox_env\\lib\\operator.py'>

TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
What is the cause of this problem? And how can I fix it?
My numpy version is 1.21.1, my computer system is Win10, CUDA is 10.2. Thank you very much.

**Comment by ilem777** [comment]
The problem has been solved. Replace lines 506 and 507 in the cocoeval.py file under the pycocotools library with
    self.iouThrs = np.linspace(.5, 0.95, 10, endpoint=True)
    self.recThrs = np.linspace(.0, 1.00, 101, endpoint=True)
