### ISSUE TITLE
CUDA error: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by YujunZhong** [Megvii-BaseDetection/YOLOX#447]
Hello, 
I was trying to reproduce the results on COCO, everything seemed fine when I used FP32 format to train the model. 
But when I tried to **train with mixed precision training** by **adding --fp16 to the command**, this error appeared. 
### Run command
python tools/train.py -n yolox-s -d 1 -b 24 --fp16 -o
### Environment
torch: 1.7.1+cu101
torchvision: 0.8.2+cu101

#### V100
CUDA Version: 10.1
CUDA Driver Version: 418.39
CUDA Runtime Version: 10.1.105
### Error details
2021-08-11 10:55:34 | INFO     | yolox.core.trainer:193 - ---> start train epoch1
2021-08-11 10:55:47 | INFO     | yolox.core.trainer:188 - Training of experiment is done and the best AP is 0.00
2021-08-11 10:55:47 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (5577), thread 'MainThread' (139655580669760):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=24, ckpt='tools/pretrain_model/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file=Non...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/data2/code/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f03c0389598>

  File "tools/train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f03c1cdc268>
    └ <yolox.core.trainer.Trainer object at 0x7f0288d82d30>

  File "/data2/code/YOLOX/yolox/core/trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f03c0656400>
    └ <yolox.core.trainer.Trainer object at 0x7f0288d82d30>

  File "/data2/code/YOLOX/yolox/core/trainer.py", line 80, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f03c066f7b8>
    └ <yolox.core.trainer.Trainer object at 0x7f0288d82d30>

  File "/data2/code/YOLOX/yolox/core/trainer.py", line 86, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f03c066f840>
    └ <yolox.core.trainer.Trainer object at 0x7f0288d82d30>

  File "/data2/code/YOLOX/yolox/core/trainer.py", line 104, in train_one_iter
    scaled_loss.backward()
    │           └ <function Tensor.backward at 0x7f0296679400>
    └ tensor(473906.7500, device='cuda:0', grad_fn=<MulBackward0>)

  File "/home/anaconda3/envs/det/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
         │    └ <generator object scale_loss at 0x7efeb1dfa990>
         └ <contextlib._GeneratorContextManager object at 0x7f0296110fd0>
  File "/home/anaconda3/envs/det/lib/python3.6/site-packages/apex/amp/handle.py", line 123, in scale_loss
    optimizer._post_amp_backward(loss_scaler)
    │         │                  └ <apex.amp.scaler.LossScaler object at 0x7f0296110550>
    │         └ <bound method post_backward_no_master_weights of SGD (
    │           Parameter Group 0
    │               dampening: 0
    │               lr: 0
    │               momentum: 0.9
    │               nes...
    └ SGD (
      Parameter Group 0
          dampening: 0
          lr: 0
          momentum: 0.9
          nesterov: True
          weight_decay: 0

      Parameter Group ...
  File "/home/anaconda3/envs/det/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 249, in post_backward_no_master_weights
    post_backward_models_are_masters(scaler, params, stashed_grads)
    │                                │       │       └ [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None...
    │                                │       └ [Parameter containing:
    │                                │         tensor([1.4638, 2.6104, 2.7194, 1.5862, 3.4371, 2.4383, 2.6247, 1.4690, 2.1836,
    │                                │                 1.4712, 1.9817...
    │                                └ <apex.amp.scaler.LossScaler object at 0x7f0296110550>
    └ <function post_backward_models_are_masters at 0x7f0288858d90>
  File "/home/anaconda3/envs/det/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 128, in post_backward_models_are_masters
    scale_override=grads_have_scale/out_scale)
                   │                └ 1.0
                   └ 65536.0
  File "/home/anaconda3/envs/det/lib/python3.6/site-packages/apex/amp/scaler.py", line 117, in unscale
    1./scale)
       └ 65536.0
  File "/home/anaconda3/envs/det/lib/python3.6/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
     └ (1.52587890625e-05,)

RuntimeError: CUDA error: CUDA driver version is insufficient for CUDA runtime version

**Comment by YujunZhong** [comment]
#### For those who might encounter the same problem:
This error is generated from apex, you can try to reinstall apex as > https://github.com/NVIDIA/apex/issues/847

The command is
`pip3 install -v --no-cache-dir ./`

It works out in my scenario, and everything seems to be fine so far.
