### ISSUE TITLE
assertion error while training own dataset

### ISSUE THREAD

**Issue by ankitchandracs** [Megvii-BaseDetection/YOLOX#456]
2021-08-11 08:45:25 | ERROR    | yolox.core.launch:78 - An error has been caught in function 'launch', process 'MainProcess' (928), thread 'MainThread' (140666854238080):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, ckpt='/content/drive/MyDrive/yolox_x.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 78, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fef8bb3f9e0>

  File "tools/train.py", line 103, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fef14949a70>
    └ <yolox.core.trainer.Trainer object at 0x7fef12b20390>

  File "/content/YOLOX/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fef10c585f0>
    └ <yolox.core.trainer.Trainer object at 0x7fef12b20390>

  File "/content/YOLOX/yolox/core/trainer.py", line 154, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7fef10a17110>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7fef12b20390>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7fef12b20390>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 26, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7fef13ea0d40>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fef10a17090>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 30, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fef0d8b4210>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fef10a17090>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fef10a17090>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fef10a17090>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7fef2125a710>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fef0d8b4210>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7fef0cedb990>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7fef2125a830>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fef0d8b4210>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fef89913290>
    └ <torch._utils.ExceptionWrapper object at 0x7fef0cedb990>

  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/usr/local/lib/p...
          │    └ <class 'AssertionError'>
          └ <torch._utils.ExceptionWrapper object at 0x7fef0cedb990>

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/content/YOLOX/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/content/YOLOX/yolox/data/datasets/coco.py", line 105, in pull_item
    assert img is not None
AssertionError

**Comment by zhangming8** [comment]
Your image path is not right.

**Comment by loss133** [comment]
你好，这个问题你解决了么？我也是同样的报错，可以确定的是：
① 图片和标注文件没问题，同样的数据用另一个网络跑没问题
② 标注文件的coco格式也没有问题，拆分成一个只包含13张的小数据集是可以正常读取运行的，说明路径读取是没问题的，但是换成150张或者2000张的数据集就会报这个错
-d 1 -b 1，这个已经设置的很小了，不清楚怎么回事啊啊啊
