### ISSUE TITLE
The training model will report errors every 40 epoch

### ISSUE THREAD

**Issue by fyzhong** [Megvii-BaseDetection/YOLOX#468]
I was training yolox-s -d 4 batch size 64,errors every 40 epoch

2021-08-12 00:42:51.229 | INFO     | yolox.core.trainer:after_train:184 - Training of experiment is done and the best AP is 31.67
2021-08-12 00:42:51.230 | ERROR    | yolox.core.launch:_distributed_worker:104 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (13881), thread 'MainThread' (139988441229120):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               │     └ 25
               └ <function _main at 0x7f5197f7e170>
  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
           │    └ <function BaseProcess._bootstrap at 0x7f5198098170>
           └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f51980917a0>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7f4fa6620c20>, 0, (<function main at 0x7f5197bbf8c0>, 4, 4, 0, 'nccl', 'tcp://127.0.0.1:4...
    │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    └ <function _wrap at 0x7f4fa97e3ef0>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7f5197bbf8c0>, 4, 4, 0, 'nccl', 'tcp://127.0.0.1:41209', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7f4fa6620c20>

> File "/home/zzw/study/YOLOX/yolox/core/launch.py", line 104, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f5197bbf8c0>

  File "/home/zzw/study/YOLOX/tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f4fa660c680>
    └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>

  File "/home/zzw/study/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f4f9aab6d40>
    └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>

  File "/home/zzw/study/YOLOX/yolox/core/trainer.py", line 80, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f4f98fc9830>
    └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>

  File "/home/zzw/study/YOLOX/yolox/core/trainer.py", line 210, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f4f98fc9b00>
    └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>

  File "/home/zzw/study/YOLOX/yolox/core/trainer.py", line 293, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(evalmodel, self.evaluator, self.is_distributed)
                             │    │   │    │          │    │          │    └ True
                             │    │   │    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>
                             │    │   │    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f4ed7923490>
                             │    │   │    │          └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>
                             │    │   │    └ YOLOX(
                             │    │   │        (backbone): YOLOPAFPN(
                             │    │   │          (backbone): CSPDarknet(
                             │    │   │            (stem): Focus(
                             │    │   │              (conv): BaseConv(
                             │    │   │                (conv): ...
                             │    │   └ <function Exp.eval at 0x7f4f98f477a0>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x7f4f98ff1f90>

  File "/home/zzw/study/YOLOX/yolox/exp/yolox_base.py", line 250, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ True
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7f4f98fc5200>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7f4ed7923490>

  File "/home/zzw/study/YOLOX/yolox/evaluators/coco_evaluator.py", line 127, in evaluate
    data_list = gather(data_list, dst=0)
                │      └ [{'image_id': 397133, 'category_id': 1, 'bbox': [381.25, 65.75, 127.5, 279.75], 'score': 0.8900070190429688, 'segmentation': ...
                └ <function gather at 0x7f4fa93b64d0>

  File "/home/zzw/study/YOLOX/yolox/utils/dist.py", line 217, in gather
    size_list, tensor = _pad_to_largest_tensor(tensor, group)
                        │                      │       └ <torch._C._distributed_c10d.ProcessGroupGloo object at 0x7f4ed2a0a230>
                        │                      └ tensor([128,   3,  93,  ..., 117, 101,  46], dtype=torch.uint8)
                        └ <function _pad_to_largest_tensor at 0x7f4fa93b63b0>

  File "/home/zzw/study/YOLOX/yolox/utils/dist.py", line 141, in _pad_to_largest_tensor
    dist.all_gather(size_list, local_size, group=group)
    │    │          │          │                 └ <torch._C._distributed_c10d.ProcessGroupGloo object at 0x7f4ed2a0a230>
    │    │          │          └ tensor([6623559])
    │    │          └ [tensor([0]), tensor([0]), tensor([0]), tensor([0])]
    │    └ <function all_gather at 0x7f4fa9d04050>
    └ <module 'torch.distributed' from '/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/site-packages/torch/distributed/__ini...

  File "/home/zzw/software/anaconda3/envs/yolox/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1914, in all_gather
    work.wait()
    │    └ <instancemethod wait at 0x7f4fa9ce2450>
    └ <torch._C._distributed_c10d.Work object at 0x7f4ed784e1b0>

RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:36274

**Comment by wdf19961118** [comment]
I met the same problem. Have you solved it?

**Comment by Garvit-32** [comment]
same problem with me also

**Comment by HELLOBRANWORLD** [comment]
same problem

**Comment by lishanlu136** [comment]
same problem
