### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by yusufpraditya** [Megvii-BaseDetection/YOLOX#494]
Hi, I'm trying to export my custom model to TensorRT, but when I tried this command:

`python3 tools/trt.py -f ~/project/YOLOX/exps/default/yolox_s.py -c best_ckpt.pth.tar`

It throws some errors, here is the complete errors:

2021-08-13 17:37:32.028 | INFO     | __main__:main:52 - loaded checkpoint done.
2021-08-13 17:37:32.037 | ERROR    | __main__:<module>:77 - An error has been caught in function '<module>', process 'MainProcess' (11348), thread 'MainThread' (547916570640):
Traceback (most recent call last):

> File "tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7f59ea2730>

  File "tools/trt.py", line 54, in main
    model.cuda()
    │     └ <function Module.cuda at 0x7f61199048>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
           │    │                       └ None
           │    └ <function Module._apply at 0x7f61195ea0>
           └ YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv): BaseConv(
                       (conv): ...
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
    │      │      └ <function Module.cuda.<locals>.<lambda> at 0x7f59ead158>
    │      └ <function Module._apply at 0x7f61195ea0>
    └ YOLOPAFPN(
        (backbone): CSPDarknet(
          (stem): Focus(
            (conv): BaseConv(
              (conv): Conv2d(12, 32, kernel_size=(3...
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
    │      │      └ <function Module.cuda.<locals>.<lambda> at 0x7f59ead158>
    │      └ <function Module._apply at 0x7f61195ea0>
    └ CSPDarknet(
        (stem): Focus(
          (conv): BaseConv(
            (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1...
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
    │      │      └ <function Module.cuda.<locals>.<lambda> at 0x7f59ead158>
    │      └ <function Module._apply at 0x7f61195ea0>
    └ Focus(
        (conv): BaseConv(
          (conv): Conv2d(12, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn)...
  [Previous line repeated 2 more times]
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
                    │  └ Parameter containing:
                    │    tensor([[[[ 1.9104e-02,  2.6808e-02, -5.0284e-02],
                    │              [ 1.6802e-01,  1.8659e-01, -1.5115e-01],
                    │     ...
                    └ <function Module.cuda.<locals>.<lambda> at 0x7f59ead158>
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                              │  │ │    └ None
                              │  │ └ <method 'cuda' of 'torch._C._TensorBase' objects>
                              │  └ Parameter containing:
                              │    tensor([[[[ 1.9104e-02,  2.6808e-02, -5.0284e-02],
                              │              [ 1.6802e-01,  1.8659e-01, -1.5115e-01],
                              │     ...
                              └ Parameter containing:
                                tensor([[[[ 1.9104e-02,  2.6808e-02, -5.0284e-02],
                                          [ 1.6802e-01,  1.8659e-01, -1.5115e-01],
                                 ...
  File "/home/mavis/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

AssertionError: Torch not compiled with CUDA enabled

**Comment by yusufpraditya** [comment]
Just recently found the problem. Reinstalled pytorch by following the steps on this link:
[](https://qengineering.eu/install-pytorch-on-jetson-nano.html)

(using Jetson Nano)
