### ISSUE TITLE
coco2014 ---->error

### ISSUE THREAD

**Issue by KangChou** [Megvii-BaseDetection/YOLOX#502]
my use coco2014:
ubuntu16.04
python3.6
cuda11
torch1.8

`2021-08-14 12:20:02 | INFO | yolox.core.trainer:133 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-08-14 12:20:04 | INFO | apex.amp.frontend:328 - Selected optimization level O1: Insert automatic casts around Pytorch functions and Tensor methods.
2021-08-14 12:20:04 | INFO | apex.amp.frontend:329 - Defaults for this optimization level are:
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - enabled : True
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - opt_level : O1
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - cast_model_type : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - patch_torch_functions : True
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - keep_batchnorm_fp32 : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - master_weights : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:331 - loss_scale : dynamic
2021-08-14 12:20:04 | INFO | apex.amp.frontend:336 - Processing user overrides (additional kwargs that are not None)...
2021-08-14 12:20:04 | INFO | apex.amp.frontend:354 - After processing overrides, optimization options are:
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - enabled : True
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - opt_level : O1
path_coco---------------- /data/my_project/YOLOX/COCO/COCO
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - cast_model_type : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - patch_torch_functions : True
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - keep_batchnorm_fp32 : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - master_weights : None
2021-08-14 12:20:04 | INFO | apex.amp.frontend:356 - loss_scale : dynamic
2021-08-14 12:20:04 | INFO | yolox.data.datasets.coco:44 - loading annotations into memory...
2021-08-14 12:20:04 | ERROR | yolox.core.launch:78 - An error has been caught in function 'launch', process 'MainProcess' (3484), thread 'MainThread' (140363684980480):
Traceback (most recent call last):

File "tools/train.py", line 126, in
args=(exp, args),
│ └ Namespace(batch_size=4, ckpt=None, devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/default/yolox_s.py', experim...
└ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

    File "/data/my_project/YOLOX/yolox/core/launch.py", line 78, in launch
    main_func(*args)
    │ └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fa805313378>

File "tools/train.py", line 104, in main
trainer.train()
│ └ <function Trainer.train at 0x7fa78963d840>
└ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

File "/data/my_project/YOLOX/yolox/core/trainer.py", line 70, in train
self.before_train()
│ └ <function Trainer.before_train at 0x7fa805368510>
└ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

File "/data/my_project/YOLOX/yolox/core/trainer.py", line 151, in before_train
no_aug=self.no_aug,
│ └ False
└ <yolox.core.trainer.Trainer object at 0x7fa80531ebe0>

File "/data/my_project/YOLOX/yolox/exp/yolox_base.py", line 100, in get_data_loader
max_labels=50,

File "/data/my_project/YOLOX/yolox/data/datasets/coco.py", line 44, in init
self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
│ │ │ │ │ │ │ │ └ 'instances_train2017.json'
│ │ │ │ │ │ │ └ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>
│ │ │ │ │ │ └ '/data/my_project/YOLOX/COCO/COCO'
│ │ │ │ │ └ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>
│ │ │ │ └ <function join at 0x7fa8f782f2f0>
│ │ │ └ <module 'posixpath' from '/opt/conda/lib/python3.6/posixpath.py'>
│ │ └ <module 'os' from '/opt/conda/lib/python3.6/os.py'>
│ └ <class 'pycocotools.coco.COCO'>
└ <yolox.data.datasets.coco.COCODataset object at 0x7fa8050e2b38>

File "/opt/conda/lib/python3.6/site-packages/pycocotools/coco.py", line 84, in init
dataset = json.load(open(annotation_file, 'r'))
│ │ └ '/data/my_project/YOLOX/COCO/COCO/annotations/instances_train2017.json'
│ └ <function load at 0x7fa8f57d3730>
└ <module 'json' from '/opt/conda/lib/python3.6/json/init.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/data/my_project/YOLOX/COCO/COCO/annotations/instances_train2017.json'
root@ovo:/data/my_project/YOLOX# vim /etc/default/locale

[2]+ Stopped vim /etc/default/locale
`

**Comment by KangChou** [comment]
`
2021-08-16 08:27:57 | ERROR    | yolox.core.launch:78 - An error has been caught in function 'launch', process 'MainProcess' (846), thread 'MainThread' (140466267842304):
`


`
File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
`

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/opt/conda/lib/python3.6/site-packages/loguru/_file_sink.py", line 176, in write
    self._file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 447-571: ordinal not in range(128)
--- End of logging error ---

```
