### ISSUE TITLE
Need help to debug error

### ISSUE THREAD

**Issue by santhraul** [Megvii-BaseDetection/YOLOX#512]
I am getting below error. Can any one one help me in this. I am training a custom dataset, with 11 classes. But I am training for 3 classes. 'd50 is one of the label but I am not training it. datasettype is VOC'

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/content/YOLOX/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/content/YOLOX/yolox/data/datasets/voc.py", line 145, in pull_item
    target = self.load_anno(index)
  File "/content/YOLOX/yolox/data/datasets/voc.py", line 126, in load_anno
    target = self.target_transform(target)
  File "/content/YOLOX/yolox/data/datasets/voc.py", line 64, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'd50'

**Comment by FateScript** [comment]
seems your are using custom dataset, please make sure "d50" in your classes name
