### ISSUE TITLE
执行python3 setup.py develop后出现如下问题，请问应该如何解决？另，请问该指令与pip3 install -v -e .有何区别？

### ISSUE THREAD

**Issue by Joejwu** [Megvii-BaseDetection/YOLOX#519]
`running develop
running egg_info
writing yolox.egg-info/PKG-INFO
writing dependency_links to yolox.egg-info/dependency_links.txt
writing top-level names to yolox.egg-info/top_level.txt
reading manifest file 'yolox.egg-info/SOURCES.txt'
writing manifest file 'yolox.egg-info/SOURCES.txt'
running build_ext
/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:294: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'yolox._C' extension
/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:266: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.o.d -pthread -B /home/wuqiaojun/anaconda3/envs/mytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wuqiaojun/YOLOX/yolox/layers/csrc -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/TH -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/THC -I/home/wuqiaojun/anaconda3/envs/mytorch/include/python3.8 -c -c /home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.cpp -o /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.o 
c++ -MMD -MF /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.o.d -pthread -B /home/wuqiaojun/anaconda3/envs/mytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wuqiaojun/YOLOX/yolox/layers/csrc -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/TH -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/THC -I/home/wuqiaojun/anaconda3/envs/mytorch/include/python3.8 -c -c /home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.cpp -o /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/vision.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
c++: error: unrecognized command line option ‘-std=c++14’
[2/2] c++ -MMD -MF /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.o.d -pthread -B /home/wuqiaojun/anaconda3/envs/mytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wuqiaojun/YOLOX/yolox/layers/csrc -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/TH -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/THC -I/home/wuqiaojun/anaconda3/envs/mytorch/include/python3.8 -c -c /home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.cpp -o /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.o 
c++ -MMD -MF /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.o.d -pthread -B /home/wuqiaojun/anaconda3/envs/mytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wuqiaojun/YOLOX/yolox/layers/csrc -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/TH -I/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/include/THC -I/home/wuqiaojun/anaconda3/envs/mytorch/include/python3.8 -c -c /home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.cpp -o /home/wuqiaojun/YOLOX/build/temp.linux-x86_64-3.8/home/wuqiaojun/YOLOX/yolox/layers/csrc/cocoeval/cocoeval.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
c++: error: unrecognized command line option ‘-std=c++14’
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    setuptools.setup(
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/wuqiaojun/anaconda3/envs/mytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
`

**Comment by lazyn1997** [comment]
![image](https://user-images.githubusercontent.com/34644177/132125388-e967be8d-9c9f-4fb3-bfff-5d0e1d21dc91.png)
I have this problem.

**Comment by lazyn1997** [comment]
> ![image](https://user-images.githubusercontent.com/34644177/132125388-e967be8d-9c9f-4fb3-bfff-5d0e1d21dc91.png)
> I have this problem.

我是Windows 10环境，需要安装vs2017 c++和vs2019 c++，并且将vs2019 x64目录下的cl.exe根目录添加到环境变量中。
I am a Windows 10 environment. I need to install vs2017 C + + and vs2019 C + +, and add the cl.exe root directory under vs2019 x64 directory to the environment variable.
