### ISSUE TITLE
multiclass_nms后处理出错

### ISSUE THREAD

**Issue by pengtougu** [Megvii-BaseDetection/YOLOX#52]
Traceback (most recent call last):
  File "D:/coding/YOLO-stream/yolox-ort.py", line 178, in <module>
    yolox_detect(args.model, args.names, frame)
  File "D:/coding/YOLO-stream/yolox-ort.py", line 153, in yolox_detect
    dets = multiclass_nms(boxes_xyxy, scores, nms_thr=0.65, score_thr=0.1)
  File "D:/coding/YOLO-stream/yolox-ort.py", line 103, in multiclass_nms
    return np.concatenate(final_dets, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
大佬们，我在ort推理的时候，当摄像头没有识别的目标或者目标仅有一个的情况下，它就会跳以上的bug，建议还是改成nms直接处理比较好~

**Comment by Joker316701882** [comment]
”直接用nms处理“是什么意思？

**Comment by pengtougu** [comment]
感谢您和您团队的贡献，您的脚本应该是在这里卡bug了
return np.concatenate(final_dets, 0)
当无检测目标时会出现返回空值，导致dets无法进行下一步处理，可能您这边还要再优化一下

**Comment by Joker316701882** [comment]
@pengtougu Thank you for your suggestion, this bug has been fixed in PR #66

**Comment by pengtougu** [comment]
ok，I get it
