### ISSUE TITLE
Exception: Path to the weights  doesn't exist or it's a directory

### ISSUE THREAD

**Issue by XQF-FOREVER** [Megvii-BaseDetection/YOLOX#520]
在用openvino推理时出现这个问题，不知道什么原因，我已经把.xml和图片都放在同一个路径下了，还是不行
C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\demo\test_yolox>python openvino_inference.py -m yolox_10.xml -i assets\dog.jpg
[ INFO ] Creating Inference Engine
[ INFO ] Reading the network: yolox_10.xml
Traceback (most recent call last):
  File "openvino_inference.py", line 158, in <module>
    sys.exit(main())
  File "openvino_inference.py", line 89, in main
    net = ie.read_network(model=args.model)
  File "ie_api.pyx", line 262, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 287, in openvino.inference_engine.ie_api.IECore.read_network
Exception: Path to the weights  doesn't exist or it's a directory

**Comment by niuwenju** [comment]
把你的第89行改成这个net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")
