### ISSUE TITLE
voc.py中出现AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by gjr2019** [Megvii-BaseDetection/YOLOX#530]
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/train/src_repo/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/project/train/src_repo/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/project/train/src_repo/yolox/data/datasets/voc.py", line 146, in pull_item
    target = self.load_anno(index)
  File "/project/train/src_repo/yolox/data/datasets/voc.py", line 127, in load_anno
    target = self.target_transform(target)
  File "/project/train/src_repo/yolox/data/datasets/voc.py", line 51, in __call__
    difficult = int(obj.find("difficult").text) == 1
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by gjr2019** [comment]
但是训练又出现如下问题
`File "/project/train/src_repo/yolox/evaluators/voc_evaluator.py", line 166, in evaluate_prediction
    a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
                          │                 │           │    │          └ 16
                          │                 │           │    └ <torch.utils.data.dataloader.DataLoader object at 0x7ff22da9c4a8>
                          │                 │           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7ff25a806438>
                          │                 └ 0.0
                          └ 0.0
 
ZeroDivisionError: float division by zero`

**Comment by Hazel-Xiang** [comment]
请问AttributeError: 'NoneType' object has no attribute 'text'问题是什么解决的呢？
