### ISSUE TITLE
遇到错误 img is not None

### ISSUE THREAD

**Issue by 15162162323** [Megvii-BaseDetection/YOLOX#544]
2021-08-20 17:42:42 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (99094), thread 'MainThread' (140328019478336):
Traceback (most recent call last):

  File "tools/train.py", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/defau...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/home/hht/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f9f965541e0>

  File "tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f9d7ebc7bf8>
    └ <yolox.core.trainer.Trainer object at 0x7f9f9654f8d0>

  File "/home/hht/YOLOX/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f9f96a5d2f0>
    └ <yolox.core.trainer.Trainer object at 0x7f9f9654f8d0>

  File "/home/hht/YOLOX/yolox/core/trainer.py", line 152, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7f9f6c21ecf8>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7f9f9654f8d0>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7f9f9654f8d0>

  File "/home/hht/YOLOX/yolox/data/data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7f9d7ec39158>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f9d8dc27080>

  File "/home/hht/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f9d8dc274e0>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f9d8dc27080>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f9d8dc27080>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f9d8dc27080>

  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f9d8dc671e0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f9d8dc274e0>
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f9f962f83c8>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f9d8dc672f0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f9d8dc274e0>
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fa09dc821e0>
    └ <torch._utils.ExceptionWrapper object at 0x7f9f962f83c8>
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/root/anaconda3/...
          │    └ <class 'AssertionError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f9f962f83c8>

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pyht/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hht/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 110, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/hht/YOLOX/yolox/data/datasets/mosaicdetection.py", line 95, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/home/hht/YOLOX/yolox/data/datasets/coco.py", line 185, in pull_item
    img = self.load_resized_img(index)
  File "/home/hht/YOLOX/yolox/data/datasets/coco.py", line 158, in load_resized_img
    img = self.load_image(index)
  File "/home/hht/YOLOX/yolox/data/datasets/coco.py", line 173, in load_image
    assert img is not None
AssertionError

**Comment by 18789447455** [comment]
请问你解决这个问题了吗

**Comment by rosebbb** [comment]
Your img path is probably wong. If you are working on your custom dataset in coco format. In coco.py, a 'name' is added to the image path at line 169. This might be the cause.

**Comment by corleonechensiyu** [comment]
检查下voc.py第120行，你的图片格式是不是.jpg结尾的

**Comment by 18789447455** [comment]
> Your img path is probably wong. If you are working on your custom dataset in coco format. In coco.py, a 'name' is added to the image path at line 169. This might be the cause.

请问具体在括号的那个位置添加name
