### ISSUE TITLE
A bug maybe from pytorch

### ISSUE THREAD

**Issue by gyy0592** [Megvii-BaseDetection/YOLOX#548]
File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught RuntimeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/usr/local/lib/pyt...
          │    └ <class 'RuntimeError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f09618f3290>

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [] at entry 2

Can anybody help me with that?

**Comment by gyy0592** [comment]
File "/content/drive/My Drive/gyy/YOLOX/yolox/data/data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7f0967d81560>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f0960558a90>

  File "/content/drive/My Drive/gyy/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f09615a4090>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f0960558a90>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f0960558a90>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f0960558a90>

It's from dataloader I guess

**Comment by FateScript** [comment]
This issue is already solved in latest version. Feel Free to reopen.
