### ISSUE TITLE
When device=2, Exception: process 0 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by FrankXinqi** [Megvii-BaseDetection/YOLOX#593]
I can run with d=1, but when d=2

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    launch(
  File "/home/user_name/Project/YOLOX/yolox/core/launch.py", line 82, in launch
    mp.start_processes(
  File "/home/username/anaconda3/envs/yolox-0826/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/username/anaconda3/envs/yolox-0826/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 105, in join
    raise Exception(
Exception: process 0 terminated with signal SIGKILL
Exception ignored in: <function COCODataset.__del__ at 0x7effec4f4b80>
Traceback (most recent call last):
  File "/home/username/Project/YOLOX/yolox/data/datasets/coco.py", line 62, in __del__
    del self.imgs
AttributeError: imgs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/anaconda3/envs/yolox-0826/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/username/anaconda3/envs/yolox-0826/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
(yolox-0826) username@username-Desktop:~/Project/YOLOX$ python tools/train.py -f exps/default/yolox_tiny.py -c yolox_tiny.pth -d 2 -b 1/home/username/anaconda3/envs/yolox-0826/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 39 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
^C

![image](https://user-images.githubusercontent.com/13465175/130950544-1a68c483-1767-4251-b29f-edf80a36dd53.png)

**Comment by yurkovak** [comment]
Try reducing num workers by adding `data_num_workers 1` to the end of the command. The default is 4, so if it helps look for a maximum number between 1 and 3.
