### ISSUE TITLE
when train at last 15 epoch，meet a problem

### ISSUE THREAD

**Issue by lenka844** [Megvii-BaseDetection/YOLOX#610]
hithere， very appreciate  for your code, but when i try to ytain on my coco's format dataset,i meet a problem, it is when the training go to the 285 epoch, the aug is closed, and a error occurs, as fllows:
2021-08-28 19:32:16 | INFO     | yolox.core.trainer:191 - --->No mosaic aug now!
2021-08-28 19:32:16 | INFO     | yolox.core.trainer:193 - --->Add additional L1 loss now!
2021-08-28 19:32:16 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/CoCo
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++
2021-08-28 19:32:19 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 0.00
Process Process-2:2:
2021-08-28 19:32:19 | ERROR    | yolox.core.launch:147 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (2676), thread 'MainThread' (140173259503424):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               │     └ 9
               └ <function _main at 0x7f7c9f7f02f0>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
           │    └ <function BaseProcess._bootstrap at 0x7f7c9f9177b8>
           └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f7c9f907f28>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7f7c390a2d08>, 0, (<function main at 0x7f7c2d6ace18>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:3...
    │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    └ <function _wrap at 0x7f7c3cb44840>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7f7c2d6ace18>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:36773', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7f7c390a2d08>

> File "/home/ljh/Desktop/YOLOX/yolox/core/launch.py", line 147, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f7c2d6ace18>

  File "/home/ljh/Desktop/YOLOX/tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f7c2f04b6a8>
    └ <yolox.core.trainer.Trainer object at 0x7f7c2d6c4d30>

  File "/home/ljh/Desktop/YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f7c2e0b6950>
    └ <yolox.core.trainer.Trainer object at 0x7f7c2d6c4d30>

  File "/home/ljh/Desktop/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f7c2e0d2268>
    └ <yolox.core.trainer.Trainer object at 0x7f7c2d6c4d30>

  File "/home/ljh/Desktop/YOLOX/yolox/core/trainer.py", line 87, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f7c2e0d22f0>
    └ <yolox.core.trainer.Trainer object at 0x7f7c2d6c4d30>

  File "/home/ljh/Desktop/YOLOX/yolox/core/trainer.py", line 93, in train_one_iter
    inps, targets = self.prefetcher.next()
                    │    │          └ <function DataPrefetcher.next at 0x7f7c2f0b1bf8>
                    │    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f7c3c811320>
                    └ <yolox.core.trainer.Trainer object at 0x7f7c2d6c4d30>

  File "/home/ljh/Desktop/YOLOX/yolox/data/data_prefetcher.py", line 44, in next
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7f7c2f0b1b70>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f7c3c811320>

  File "/home/ljh/Desktop/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │    │           │    │                        │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f7c204cda20>
    │    │           │    │                        └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f7c3c811320>
    │    │           │    └ tensor([[[0., 0., 0., 0., 0.],
    │    │           │               [0., 0., 0., 0., 0.],
    │    │           │               [0., 0., 0., 0., 0.],
    │    │           │               [0., 0., 0., 0., 0.],
    │    │           │       ...
    │    │           └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f7c3c811320>
    │    └ tensor([[[[114., 114., 114.,  ..., 114., 114., 114.],
    │                [114., 114., 114.,  ..., 114., 114., 114.],
    │                [114., ...
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f7c3c811320>

  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f7c3c7b2a60>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f7c204cda20>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f7bdf004ba8>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f7c3c7b2b70>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f7c204cda20>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f7c9ec342f0>
    └ <torch._utils.ExceptionWrapper object at 0x7f7bdf004ba8>
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught TypeError in DataLoader worker process 1.\nOriginal Traceback (most recent call last):\n  File "/home/ljh/.conda/envs...
          │    └ <class 'TypeError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f7bdf004ba8>

TypeError: Caught TypeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ljh/.conda/envs/ylx/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 61, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem.dtype))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <U7

**Comment by lenka844** [comment]
can you help me to fix the problem, appreciate!

**Comment by Joker316701882** [comment]
Maybe this PR #603 already fix your problem? Could you try our latest branch?

**Comment by lenka844** [comment]
> Maybe this PR #603 already fix your problem? Could you try our latest branch?

well， actuall  i seems have not changed the mosaic_prob value, and i have try the new verision of ylx, but it seems didnt work, i will try  it again.

**Comment by lenka844** [comment]
2021-08-29 14:29:47 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/yolox_s
2021-08-29 14:29:48 | INFO     | yolox.core.trainer:188 - ---> start train epoch8
2021-08-29 14:29:48 | INFO     | yolox.core.trainer:191 - --->No mosaic aug now!
2021-08-29 14:29:48 | INFO     | yolox.core.trainer:193 - --->Add additional L1 loss now!
2021-08-29 14:29:48 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/yolox_s
2021-08-29 14:29:50 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 13.58
2021-08-29 14:29:50 | ERROR    | yolox.core.launch:147 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (24369), thread 'MainThread' (140621629986624):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               │     └ 9
               └ <function _main at 0x7fe50475a2f0>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
           │    └ <function BaseProcess._bootstrap at 0x7fe5048817b8>
           └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fe504871f28>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7fe49e00cbf8>, 0, (<function main at 0x7fe49260f950>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:3...
    │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    └ <function _wrap at 0x7fe4a1aae730>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7fe49260f950>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:33067', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7fe49e00cbf8>

> File "/home/ljh/YOLOX/yolox/core/launch.py", line 147, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fe49260f950>

  File "/home/ljh/YOLOX/tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fe493fb3510>
    └ <yolox.core.trainer.Trainer object at 0x7fe49261bbe0>

  File "/home/ljh/YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fe493021620>
    └ <yolox.core.trainer.Trainer object at 0x7fe49261bbe0>

  File "/home/ljh/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7fe493038d08>
    └ <yolox.core.trainer.Trainer object at 0x7fe49261bbe0>

  File "/home/ljh/YOLOX/yolox/core/trainer.py", line 87, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7fe493038d90>
    └ <yolox.core.trainer.Trainer object at 0x7fe49261bbe0>

  File "/home/ljh/YOLOX/yolox/core/trainer.py", line 93, in train_one_iter
    inps, targets = self.prefetcher.next()
                    │    │          └ <function DataPrefetcher.next at 0x7fe49401ba60>
                    │    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fe446cf7ef0>
                    └ <yolox.core.trainer.Trainer object at 0x7fe49261bbe0>

  File "/home/ljh/YOLOX/yolox/data/data_prefetcher.py", line 43, in next
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7fe49401b9d8>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fe446cf7ef0>

  File "/home/ljh/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │    │           │    │                        │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe446cf7f28>
    │    │           │    │                        └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fe446cf7ef0>
    │    │           │    └ tensor([[[  3.0000, 218.2926, 379.3279,  74.1916,  58.1691],
    │    │           │               [  3.0000, 449.9980, 291.3791,  92.9210,  69.9519],
    │    │           │         ...
    │    │           └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fe446cf7ef0>
    │    └ tensor([[[[ 50.,  49.,  47.,  ..., 134., 132., 129.],
    │                [ 53.,  48.,  46.,  ..., 130., 129., 130.],
    │                [ 47., ...
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fe446cf7ef0>

  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7fe4a171b950>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe446cf7f28>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7fe493593eb8>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7fe4a171ba60>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fe446cf7f28>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fe503b9f2f0>
    └ <torch._utils.ExceptionWrapper object at 0x7fe493593eb8>
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught TypeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/home/ljh/.conda/envs...
          │    └ <class 'TypeError'>
          └ <torch._utils.ExceptionWrapper object at 0x7fe493593eb8>

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ljh/.conda/envs/lix/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 61, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem.dtype))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <U7


still have this problem, after close aug, this problem occurs.
because i used my custom coco dataset, the image_id is like 'u00001' type, use the original pycocotools cannot load image, so i change as follows:
def loadImgs(self, ids=[]):
        """
        Load anns with the specified ids.
        :param ids (int array)       : integer ids specifying img
        :return: imgs (object array) : loaded img objects
        """
        # return self.loadImgs(ids)
        # print("==========",type(ids))
        if _isArrayLike(ids):
            # return [self.imgs[id] for id in ids]
            return [self.imgs[ids]]
        elif type(ids) == int:
            return [self.imgs[ids]]

and here:
def load_anno_from_ids(self, id_):
        im_ann = self.coco.loadImgs(id_)[0]
        width = im_ann["width"]
        height = im_ann["height"]
#anno_ids = self.coco.getAnnIds(imgIds=[int(id_)], iscrowd=False)
        anno_ids = self.coco.getAnnIds(imgIds=[(id_)], iscrowd=False)
        annotations = self.coco.loadAnns(anno_ids)
i will try to use the coco2017 to test whether is these place lead to error.

**Comment by lenka844** [comment]
fix it.

**Comment by trathpai** [comment]
i am getting similar error but before the start of training
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <U38
I am also using custom coco format dataset. Images and annotations seem to be loaded properly in coco.py . 

Not sure where to look further!

**Comment by lenka844** [comment]
> i am getting similar error but before the start of training TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <U38 I am also using custom coco format dataset. Images and annotations seem to be loaded properly in coco.py .
> 
> Not sure where to look further!

would u mind show more details about that?

**Comment by trathpai** [comment]
I created a new issue  [here](https://github.com/Megvii-BaseDetection/YOLOX/issues/762#issue-1011001994)
