### ISSUE TITLE
yolox_nano on trt.py error.

### ISSUE THREAD

**Issue by prateeksarangi** [Megvii-BaseDetection/YOLOX#627]
While running tools/trt.py on yolox_nano, I encountered the following error,

2021-09-01 06:48:13.413 | ERROR    | __main__:<module>:77 - An error has been caught in function '<module>', process 'MainProcess' (1845), thread 'MainThread' (140302752065344):
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f9ac6900f90>, origin='/root/.vsc...
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x7f9ac6949f60, file "/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles...

  File "/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
    │   └ <function main at 0x7f9ac5682c20>
    └ <module 'debugpy.server.cli' from '/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/...

  File "/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
    └ <function run_file at 0x7f9ac56829e0>

  File "/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
    │     │        │                       │      └ <function force_str at 0x7f9ac68a0e60>
    │     │        │                       └ <module 'debugpy.common.compat' from '/root/.vscode-server/extensions/ms-python.python-2021.8.1159798656/pythonFiles/lib/pyth...
    │     │        └ 'tools/trt.py'
    │     └ <function run_path at 0x7f9ac68a0290>
    └ <module 'runpy' from '/opt/conda/lib/python3.7/runpy.py'>

  File "/opt/conda/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
             │                     └ 'tools/trt.py'
             └ ''
  File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
    │         │         │         └ 'tools/trt.py'
    │         │         └ ''
    │         └ None
    └ '__main__'
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'tools/trt.py'...
         └ <code object <module> at 0x7f9ac463bc90, file "tools/trt.py", line 5>

> File "tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7f99dd7b1c20>

  File "tools/trt.py", line 62, in main
    max_workspace_size=(1 << 32),

  File "/opt/conda/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 377, in torch2trt
    outputs = module(*inputs)
              │       └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
              │                   [1., 1., 1.,  ..., 1., 1., 1.],
              │                   [1., 1., 1.,  ..., 1., 1., 1.]...
              └ YOLOX(
                  (backbone): YOLOPAFPN(
                    (backbone): CSPDarknet(
                      (stem): Focus(
                        (conv): BaseConv(
                          (conv): ...
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
             │    │                    [1., 1., 1.,  ..., 1., 1., 1.],
             │    │                    [1., 1., 1.,  ..., 1., 1., 1.]...
             │    └ <function YOLOX.forward at 0x7f99dd767710>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "/root/workspace/yolox/models/yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
               │             └ tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
               │                         [1., 1., 1.,  ..., 1., 1., 1.],
               │                         [1., 1., 1.,  ..., 1., 1., 1.],...
               └ YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                         (conv): BaseConv(
                           (conv): ...

  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
             │    │                    [1., 1., 1.,  ..., 1., 1., 1.],
             │    │                    [1., 1., 1.,  ..., 1., 1., 1.]...
             │    └ <function YOLOPAFPN.forward at 0x7f99dd767320>
             └ YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv): BaseConv(
                       (conv): Conv2d(12, 16, kernel_size=(3...

  File "/root/workspace/yolox/models/yolo_pafpn.py", line 100, in forward
    f_out0 = self.C3_p4(f_out0)  # 1024->512/16
             │          └ tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
             │                      [ 0.8215,  0.8215,  2.0322,  ...,  2.2360, ...
             └ YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv): BaseConv(
                       (conv): Conv2d(12, 16, kernel_size=(3...

  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
             │    │                    [ 0.8215,  0.8215,  2.0322,  ...,  2.2360,...
             │    └ <function CSPLayer.forward at 0x7f99dd7d3b00>
             └ CSPLayer(
                 (conv1): BaseConv(
                   (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
                   (bn): BatchNorm...

  File "/root/workspace/yolox/models/network_blocks.py", line 181, in forward
    x_1 = self.conv1(x)
          │          └ tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
          │                      [ 0.8215,  0.8215,  2.0322,  ...,  2.2360, ...
          └ CSPLayer(
              (conv1): BaseConv(
                (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
                (bn): BatchNorm...

  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
             │    │                    [ 0.8215,  0.8215,  2.0322,  ...,  2.2360,...
             │    └ <function BaseConv.forward at 0x7f99dd7d34d0>
             └ BaseConv(
                 (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
                 (bn): BatchNorm2d(64, eps=0.001, momentu...

  File "/root/workspace/yolox/models/network_blocks.py", line 51, in forward
    return self.act(self.bn(self.conv(x)))
           │        │       │         └ tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
           │        │       │                     [ 0.8215,  0.8215,  2.0322,  ...,  2.2360, ...
           │        │       └ BaseConv(
           │        │           (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
           │        │           (bn): BatchNorm2d(64, eps=0.001, momentu...
           │        └ BaseConv(
           │            (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
           │            (bn): BatchNorm2d(64, eps=0.001, momentu...
           └ BaseConv(
               (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
               (bn): BatchNorm2d(64, eps=0.001, momentu...

  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
             │    │                    [ 0.8215,  0.8215,  2.0322,  ...,  2.2360,...
             │    └ <function Conv2d.forward at 0x7f99eaa79200>
             └ Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
  File "/opt/conda/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
    │                      └ <torch2trt.torch2trt.ConversionContext object at 0x7f99dd5c1510>
    └ {'converter': <function convert_Conv2d at 0x7f99e70fe0e0>, 'is_real': True}
  File "/opt/conda/lib/python3.7/site-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
    input_trt = trt_(ctx.network, input)
                │    │   │        └ tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
                │    │   │                    [ 0.8215,  0.8215,  2.0322,  ...,  2.2360, ...
                │    │   └ <tensorrt.tensorrt.INetworkDefinition object at 0x7f99dd5c17f0>
                │    └ <torch2trt.torch2trt.ConversionContext object at 0x7f99dd5c1510>
                └ <function trt_ at 0x7f99ea443320>
  File "/opt/conda/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 116, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
                  │ │    └ <property object at 0x7f9ac40589b0>
                  │ └ <tensorrt.tensorrt.ITensor object at 0x7f99d4117570>
                  └ tensor([[[[ 0.8215,  0.8215,  2.0322,  ...,  2.2360,  0.6775,  0.6775],
                              [ 0.8215,  0.8215,  2.0322,  ...,  2.2360, ...

ValueError: __len__() should return >= 0

Can you please help me solve this problem. I want to test the yolox_nano model on the trt flag.

**Comment by vinceyzw** [comment]
have you solve it? I encounter the same problem @prateeksarangi

**Comment by prateeksarangi** [comment]
Not sure if it's the right answer but I guess, it was an error on memory overflow. Try decreasing the workspace size at https://github.com/Megvii-BaseDetection/YOLOX/blob/146d1ee57c989043d2cea80c0fa948ed827c93e3/tools/trt.py#L62
Worked for me but will be looking forward for a more concrete solution though.

**Comment by tensorturtle** [comment]
I had this issue and actually decreasing it to 29 solved it for me.
