### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for YOLOX:

### ISSUE THREAD

**Issue by xinsuinizhuan** [Megvii-BaseDetection/YOLOX#644]
windows下面，使用默认推理：
Traceback (most recent call last):
  File "E:/comm_Item/Item_done/YOLOX/YOLOX/tools/demo.py", line 306, in <module>
    main(exp, args)
  File "E:/comm_Item/Item_done/YOLOX/YOLOX/tools/demo.py", line 274, in main
    model.load_state_dict(ckpt["model"])
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
	size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
	size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
	size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
	size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).

**Comment by pistachio0812** [comment]
你解决了吗

**Comment by pistachio0812** [comment]
我这个好像应该没啥问题了，我是改了voc之后想跑一下作者的例子出现这个问题的。我这个代码是之前下载了修改之后的代码

**Comment by xinsuinizhuan** [comment]
没解决。

**Comment by lijianqing317** [comment]
模型保存类别数量和yolox_base.py中的类别数量不对应，把yolox_base.py中的num_classes=3 改为 num_classes=80，应该就可以了。

**Comment by jiahao12121** [comment]
> 

正解，就是这个原因

**Comment by yr-wang** [comment]
谢谢大佬，解决啦
