### ISSUE TITLE
更新到最新版本后不能训练了

### ISSUE THREAD

**Issue by xiaosai666** [Megvii-BaseDetection/YOLOX#654]
(yolox) root@xs2-desktop-szvxrjf-6cf46b4d48-svnt8:~/cloud/xs2/project/YOLOX# python tools/train.py -f exps/default/nano.py -d 4 -b 64 --fp16 -o
2021-09-06 14:16:57.351 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 0 initialization finished.
2021-09-06 14:16:57.360 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 2 initialization finished.
2021-09-06 14:16:57.375 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 3 initialization finished.
2021-09-06 14:16:57.386 | INFO     | yolox.core.launch:_distributed_worker:116 - Rank 1 initialization finished.
2021-09-06 14:17:00.319 | INFO     | yolox.utils.setup_env:configure_omp:46 - 
***************************************************************
We set `OMP_NUM_THREADS` for each process to 1 to speed up.
please further tune the variable for optimal performance.
***************************************************************
2021-09-06 14:17:00 | INFO     | yolox.core.trainer:126 - args: Namespace(batch_size=64, cache=False, ckpt=None, devices=4, dist_backend='nccl', dist_url=None, exp_file='exps/default/nano.py', experiment_name='nano', fp16=True, machine_rank=0, name=None, num_machines=1, occupy=True, opts=[], resume=False, start_epoch=None)
2021-09-06 14:17:00 | INFO     | yolox.core.trainer:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 80                         │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.25                       │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ perspective      │ 0.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ False                      │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 5                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'nano'                     │
├──────────────────┼────────────────────────────┤
│ test_size        │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
├──────────────────┼────────────────────────────┤
│ random_size      │ (10, 20)                   │
╘══════════════════╧════════════════════════════╛
2021-09-06 14:17:01 | INFO     | yolox.core.trainer:133 - Model Summary: Params: 0.91M, Gflops: 1.08
2021-09-06 14:17:01 | INFO     | yolox.data.datasets.coco:45 - loading annotations into memory...
2021-09-06 14:17:01 | INFO     | yolox.data.datasets.coco:45 - Done (t=0.41s)
2021-09-06 14:17:01 | INFO     | pycocotools.coco:89 - creating index...
2021-09-06 14:17:01 | INFO     | pycocotools.coco:89 - index created!
2021-09-06 14:17:03 | INFO     | yolox.core.trainer:151 - init prefetcher, this might take one minute or less...
2021-09-06 14:17:13 | ERROR    | yolox.core.launch:147 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (21481), thread 'MainThread' (140710934316800):
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/opt/conda/envs/yolox/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
               │     └ 9
               └ <function _main at 0x7ff9cfe2ca70>
  File "/opt/conda/envs/yolox/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
           │    └ <function BaseProcess._bootstrap at 0x7ff9cfeeb440>
           └ <SpawnProcess(SpawnProcess-1, started)>
  File "/opt/conda/envs/yolox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7ff9cfee5a70>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/opt/conda/envs/yolox/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    │        │    └ (<function _distributed_worker at 0x7ff946e0b4d0>, 0, (<function main at 0x7ff9cfd4dcb0>, 4, 4, 0, 'nccl', 'tcp://127.0.0.1:4...
    │    │        └ <SpawnProcess(SpawnProcess-1, started)>
    │    └ <function _wrap at 0x7ff955135a70>
    └ <SpawnProcess(SpawnProcess-1, started)>
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7ff9cfd4dcb0>, 4, 4, 0, 'nccl', 'tcp://127.0.0.1:40983', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7ff946e0b4d0>

> File "/root/cloud/xs2/project/YOLOX/yolox/core/launch.py", line 147, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff9cfd4dcb0>

  File "/root/cloud/xs2/project/YOLOX/tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7ff946d953b0>
    └ <yolox.core.trainer.Trainer object at 0x7ff955279f10>

  File "/root/cloud/xs2/project/YOLOX/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7ff9445bb170>
    └ <yolox.core.trainer.Trainer object at 0x7ff955279f10>

  File "/root/cloud/xs2/project/YOLOX/yolox/core/trainer.py", line 152, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7ff9302fd050>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7ff955279f10>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7ff955279f10>

  File "/root/cloud/xs2/project/YOLOX/yolox/data/data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7ff94646ef80>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff9445c4050>

  File "/root/cloud/xs2/project/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff930314a10>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff9445c4050>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff9445c4050>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7ff9445c4050>

  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7ff954d94a70>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff930314a10>
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7ff930314d50>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7ff954d94b90>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7ff930314a10>
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7ff9cf793b00>
    └ <torch._utils.ExceptionWrapper object at 0x7ff930314d50>
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught RuntimeError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/opt/conda/envs/yo...
          │    └ <class 'RuntimeError'>
          └ <torch._utils.ExceptionWrapper object at 0x7ff930314d50>

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/opt/conda/envs/yolox/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [1, 1] at entry 1

**Comment by ruinmessi** [comment]
pull the latest version. We fix this bug in #660

**Comment by FateScript** [comment]
Feel free to reopen.
