### ISSUE TITLE
视频预测的2个问题

### ISSUE THREAD

**Issue by monkeycc** [Megvii-BaseDetection/YOLOX#662]
第一个问题  视频打不开
python tools/demo.py video -n yolox-s -c F:\YOLOX\yolox_s.pth --path D:\vIDEO\1.mp4 --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu

```
python tools/demo.py video -n yolox-s -c F:\YOLOX\yolox_s.pth --path D:\vIDEO\1.mp4 --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
2021-09-07 20:40:25.797 | INFO     | __main__:main:250 - Args: Namespace(camid=0, ckpt='F:\\YOLOX\\yolox_s.pth', conf=0.25, demo='video', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.45, path='D:\\vIDEO\\1.mp4', save_result=True, trt=False, tsize=640)
E:\anaconda3\envs\YOLOX\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-09-07 20:40:25.970 | INFO     | __main__:main:260 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-09-07 20:40:28.512 | INFO     | __main__:main:271 - loading checkpoint
2021-09-07 20:40:28.600 | INFO     | __main__:main:275 - loaded checkpoint done.
2021-09-07 20:40:28.712 | INFO     | __main__:imageflow_demo:217 - video save_path is D:\vIDEO\1.mp4
```

直接覆盖原视频文件，视频打开也没有任何东西，没有正常保存

---------------
第二个问题  删除了--save_result参数 报错
python tools/demo.py video -n yolox-s -c F:\YOLOX\yolox_s.pth --path D:\vIDEO\1.mp4 --conf 0.25 --nms 0.45 --tsize 640  --device gpu
```

2021-09-07 20:42:14.720 | INFO     | __main__:main:250 - Args: Namespace(camid=0, ckpt='F:\\YOLOX\\yolox_s.pth', conf=0.25, demo='video', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.45, path='D:\\vIDEO\\1.mp4', save_result=False, trt=False, tsize=640)
E:\anaconda3\envs\YOLOX\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-09-07 20:42:14.901 | INFO     | __main__:main:260 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-09-07 20:42:17.381 | INFO     | __main__:main:271 - loading checkpoint
2021-09-07 20:42:17.467 | INFO     | __main__:main:275 - loaded checkpoint done.
Traceback (most recent call last):
  File "tools/demo.py", line 306, in <module>
    main(exp, args)
  File "tools/demo.py", line 299, in main
    imageflow_demo(predictor, vis_folder, current_time, args)
  File "tools/demo.py", line 209, in imageflow_demo
    save_folder = os.path.join(
  File "E:\anaconda3\envs\YOLOX\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by zhengaurora** [comment]
请问你解决了么后来
