### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by qixuxiang** [Megvii-BaseDetection/YOLOX#675]
Thanks for your awesome code share!

I trained 34 epoches and it was normal, but something wrong in 35th epoch.

The following information shows that the training evaluation is performed at the same time, resulting in insufficient memory. I don't know how did this happen, would you please help me, thanks a lot!
```
2021-09-10 03:04:55 | INFO     | yolox.core.trainer:238 - epoch: 34/40, iter: 1930/1930, mem: 8975Mb, iter_time: 0.272s, data_time: 0.002s, total_loss: 30.0, iou_loss: 4.2, l1_loss: 0.0, conf_loss: 25.1, cls_loss: 0.8, lr: 6.503e-05, size: 352, ETA: 1:42:37
2021-09-10 03:04:55 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-09-10 03:04:57 | INFO     | yolox.core.trainer:188 - ---> start train epoch35
2021-09-10 03:04:57 | INFO     | yolox.core.trainer:191 - --->No mosaic aug now!
2021-09-10 03:04:57 | INFO     | yolox.core.trainer:193 - --->Add additional L1 loss now!
2021-09-10 03:04:57 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-09-10 03:05:03 | INFO     | yolox.core.trainer:238 - epoch: 35/40, iter: 10/1930, mem: 8975Mb, iter_time: 0.599s, data_time: 0.002s, total_loss: 42.1, iou_loss: 4.2, l1_loss: 1.3, conf_loss: 35.8, cls_loss: 0.7, lr: 6.501e-05, size: 512, ETA: 1:42:32
2021-09-10 03:05:11 | INFO     | yolox.core.trainer:238 - epoch: 35/40, iter: 20/1930, mem: 8975Mb, iter_time: 0.799s, data_time: 0.002s, total_loss: 64.5, iou_loss: 4.4, l1_loss: 2.5, conf_loss: 57.0, cls_loss: 0.7, lr: 6.498e-05, size: 672, ETA: 1:42:27
2021-09-10 03:05:14 | ERROR    | yolox.models.yolo_head:330 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2021-09-10 03:05:14 | INFO     | yolox.core.trainer:183 - Training of experiment is done and the best AP is 45.14
2021-09-10 03:05:14 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (2526), thread 'MainThread' (139935622719296):
Traceback (most recent call last):

  File "YOLOX/yolox/models/yolo_head.py", line 313, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7f441d329a60>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(192, 192, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7f441d3299d0>

  File "YOLOX/yolox/models/yolo_head.py", line 510, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False], device='cuda:0')
        │    │                  │     │               │           └ 3
        │    │                  │     │               └ tensor([0., 0., 0.], device='cuda:0', dtype=torch.float16)
        │    │                  │     └ tensor([], device='cuda:0', size=(3, 0))
        │    │                  └ tensor([], device='cuda:0', size=(3, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7f441d329b80>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "YOLOX/yolox/models/yolo_head.py", line 622, in dynamic_k_matching
    _, pos_idx = torch.topk(
    │            │     └ <built-in method topk of type object at 0x7f454a039ec0>
    │            └ <module 'torch' from 'miniconda3/envs/py38/lib/python3.8/site-packages/torch/__init__.py'>
    └ tensor([], device='cuda:0', size=(3, 0), dtype=torch.int64)

RuntimeError: selected index k out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    launch(
    └ <function launch at 0x7f44291d9c10>

> File "YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f441d39da60>

  File "tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f441eda43a0>
    └ <yolox.core.trainer.Trainer object at 0x7f441d39f5e0>

  File "YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f441d420280>
    └ <yolox.core.trainer.Trainer object at 0x7f441d39f5e0>

  File "YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f441d428d30>
    └ <yolox.core.trainer.Trainer object at 0x7f441d39f5e0>

  File "YOLOX/yolox/core/trainer.py", line 87, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f441d428dc0>
    └ <yolox.core.trainer.Trainer object at 0x7f441d39f5e0>

  File "YOLOX/yolox/core/trainer.py", line 101, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[ 0.0000e+00, -9.4062e+01,  2.4038e+02,  1.3273e+01,  3.4125e+01],
              │    │     │                [ 0.0000e+00, -2.2612e+02,  2.3638e+02, ...
              │    │     └ tensor([[[[ 39.,  42.,  36.,  ..., 114., 114., 114.],
              │    │                 [ 40.,  39.,  47.,  ..., 114., 114., 114.],
              │    │                 [ 39., ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x7f441d39f5e0>

  File "miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ (tensor([[[[ 39.,  42.,  36.,  ..., 114., 114., 114.],
           │                         [ 40.,  39.,  47.,  ..., 114., 114., 114.],
           │                         [ 39.,...
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "YOLOX/yolox/models/yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
                                                           └ YOLOX(
                                                               (backbone): YOLOPAFPN(
                                                                 (backbone): CSPDarknet(
                                                                   (stem): Focus(
                                                                     (conv): BaseConv(
                                                                       (conv): ...

  File "miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ ((tensor([[[[ 7.8320e-01,  8.4814e-01,  1.0459e+00,  ...,  3.8892e-01,
           │                           3.4131e-01,  2.3267e-01],
           │                         [ 4.93...
           └ <bound method YOLOXHead.forward of YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (c...

  File "YOLOX/yolox/models/yolo_head.py", line 195, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x7f441d3298b0>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(192, 192, kernel_size=...

  File "YOLOX/yolox/models/yolo_head.py", line 342, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7f441d329a60>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(192, 192, kernel_size=...

  File "miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(192, 192, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7f441d3299d0>

  File "YOLOX/yolox/models/yolo_head.py", line 492, in get_assignments
    * obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
      │          │                   └ 3
      │          └ <method 'unsqueeze' of 'torch._C._TensorBase' objects>
      └ tensor([], size=(0, 1), dtype=torch.float16)

RuntimeError: "sigmoid_cpu" not implemented for 'Half'
Writing vertical VOC results file
Writing quadrate VOC results file
Writing horizontal VOC results file
Eval IoU : 0.50
AP for class1 = 0.6327
AP for class2 = 0.3184
AP for class3 = 0.7426
Mean AP = 0.5646
~~~~~~~~
Results:
0.633
0.318
0.743
0.565
~~~~~~~~

--------------------------------------------------------------
Results computed with the **unofficial** Python eval code.
Results should be very close to the official MATLAB eval code.
Recompute with `./tools/reval.py --matlab ...` for your paper.
-- Thanks, The Management
--------------------------------------------------------------
```

**Comment by zcy5417** [comment]
RuntimeError: selected index k out of range
这个到底是怎么回事啊!
