### ISSUE TITLE
pip install -v -e . error

### ISSUE THREAD

**Issue by ehdrndd** [Megvii-BaseDetection/YOLOX#680]
I use torch 1.9 and CUDA 11.4.. Win10

When i pip install -v -e .  or python setup.py devlop

error comming..

    Running command python setup.py egg_info
    running egg_info
    creating C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info
    writing C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\PKG-INFO
    writing dependency_links to C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\dependency_links.txt
    writing top-level names to C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\top_level.txt        
    writing manifest file 'C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\ehdrn\AppData\Local\Temp\pip-pip-egg-info-va16eb1p\yolox.egg-info\SOURCES.txt'
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\colorama\ansitowin32.py", line 59, in closed       
        return stream.closed
    ValueError: underlying buffer has been detached
    Installing collected packages: yolox
    Running setup.py develop for yolox
    Running command 'c:\users\ehdrn\anaconda3\envs\od\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\OD\\YOLOX\\setup.py'"'"'; __file__='"'"'C:\\OD\\YOLOX\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing yolox.egg-info\PKG-INFO
    writing dependency_links to yolox.egg-info\dependency_links.txt
    writing top-level names to yolox.egg-info\top_level.txt
    reading manifest file 'yolox.egg-info\SOURCES.txt'
    writing manifest file 'yolox.egg-info\SOURCES.txt'
    running build_ext
    building 'yolox._C' extension
    Emitting ninja build file C:\OD\YOLOX\build\temp.win-amd64-3.8\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 지정된 파일을 찾을  
    수 없습니다

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\OD\YOLOX\setup.py", line 54, in <module>
        setuptools.setup(
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\ehdrn\anaconda3\envs\od\lib\distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "c:\users\ehdrn\anaconda3\envs\od\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ERROR: Command errored out with exit status 1: 'c:\users\ehdrn\anaconda3\envs\od\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\OD\\YOLOX\\setup.py'"'"'; __file__='"'"'C:\\OD\\YOLOX\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code 
    = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by ehdrndd** [comment]
I solved myself. 

Window 10.

install pycocotools like

pip3 install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"

**Comment by FateScript** [comment]
Feel free to reopen if you have any further questions.
