### ISSUE TITLE
train custom dataset error

### ISSUE THREAD

**Issue by fxt960803** [Megvii-BaseDetection/YOLOX#687]
D:\anaconda\envs\pytorch1.8\python.exe D:/YOLOX-main/train.py -f exps/example/custom/yolox_s.py -d 0 -b 2 --fp16 -c yolox_l.pth
2021-09-12 17:21:04 | INFO     | yolox.core.trainer:122 - args: Namespace(batch_size=2, ckpt='yolox_l.pth', devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/example/custom/yolox_s.py', experiment_name='yolox_s', fp16=True, local_rank=0, machine_rank=0, name=None, num_machine=1, occupy=False, opts=[], resume=False, start_epoch=None)
2021-09-12 17:21:04 | INFO     | yolox.core.trainer:123 - exp value:
╒══════════════════╤════════════════════════════════╕
│ keys             │ values                         │
╞══════════════════╪════════════════════════════════╡
│ seed             │ None                           │
├──────────────────┼────────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'              │
├──────────────────┼────────────────────────────────┤
│ print_interval   │ 10                             │
├──────────────────┼────────────────────────────────┤
│ eval_interval    │ 1                              │
├──────────────────┼────────────────────────────────┤
│ num_classes      │ 2                              │
├──────────────────┼────────────────────────────────┤
│ depth            │ 1.0                            │
├──────────────────┼────────────────────────────────┤
│ width            │ 1.0                            │
├──────────────────┼────────────────────────────────┤
│ data_num_workers │ 4                              │
├──────────────────┼────────────────────────────────┤
│ input_size       │ (480, 640)                     │
├──────────────────┼────────────────────────────────┤
│ multiscale_range │ 5                              │
├──────────────────┼────────────────────────────────┤
│ data_dir         │ 'D:/YOLOX-main/datasets/coco/' │
├──────────────────┼────────────────────────────────┤
│ train_ann        │ 'instances_train2017.json'     │
├──────────────────┼────────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'       │
├──────────────────┼────────────────────────────────┤
│ mosaic_prob      │ 1.0                            │
├──────────────────┼────────────────────────────────┤
│ mixup_prob       │ 1.0                            │
├──────────────────┼────────────────────────────────┤
│ hsv_prob         │ 1.0                            │
├──────────────────┼────────────────────────────────┤
│ flip_prob        │ 0.5                            │
├──────────────────┼────────────────────────────────┤
│ degrees          │ 10.0                           │
├──────────────────┼────────────────────────────────┤
│ translate        │ 0.1                            │
├──────────────────┼────────────────────────────────┤
│ mosaic_scale     │ (0.1, 2)                       │
├──────────────────┼────────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                     │
├──────────────────┼────────────────────────────────┤
│ shear            │ 2.0                            │
├──────────────────┼────────────────────────────────┤
│ perspective      │ 0.0                            │
├──────────────────┼────────────────────────────────┤
│ enable_mixup     │ True                           │
├──────────────────┼────────────────────────────────┤
│ warmup_epochs    │ 5                              │
├──────────────────┼────────────────────────────────┤
│ max_epoch        │ 300                            │
├──────────────────┼────────────────────────────────┤
│ warmup_lr        │ 0                              │
├──────────────────┼────────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                     │
├──────────────────┼────────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'                 │
├──────────────────┼────────────────────────────────┤
│ no_aug_epochs    │ 15                             │
├──────────────────┼────────────────────────────────┤
│ min_lr_ratio     │ 0.05                           │
├──────────────────┼────────────────────────────────┤
│ ema              │ True                           │
├──────────────────┼────────────────────────────────┤
│ weight_decay     │ 0.0005                         │
├──────────────────┼────────────────────────────────┤
│ momentum         │ 0.9                            │
├──────────────────┼────────────────────────────────┤
│ exp_name         │ 'yolox_s'                      │
├──────────────────┼────────────────────────────────┤
│ test_size        │ (480, 640)                     │
├──────────────────┼────────────────────────────────┤
│ test_conf        │ 0.01                           │
├──────────────────┼────────────────────────────────┤
│ nmsthre          │ 0.65                           │
╘══════════════════╧════════════════════════════════╛
D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-09-12 17:21:04 | INFO     | yolox.core.trainer:128 - Model Summary: Params: 54.15M, Gflops: 116.49
2021-09-12 17:21:06 | INFO     | yolox.core.trainer:282 - loading checkpoint for fine tuning
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 256, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([2, 256, 1, 1]).
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([2]).
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 256, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([2, 256, 1, 1]).
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([2]).
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 256, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([2, 256, 1, 1]).
2021-09-12 17:21:06 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([2]).
2021-09-12 17:21:06 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (3444), thread 'MainThread' (3012):
Traceback (most recent call last):

  File "D:/YOLOX-main\train.py", line 113, in <module>
    launch(
    └ <function launch at 0x000001722BB453A0>

> File "D:\YOLOX-main\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001722CED0AF0>

  File "D:/YOLOX-main\train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001722C1D43A0>
    └ <yolox.core.trainer.Trainer object at 0x000001722CED7E50>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 66, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000001722CEB23A0>
    └ <yolox.core.trainer.Trainer object at 0x000001722CED7E50>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 145, in before_train
    cache_img=self.args.cache,
              │    └ Namespace(batch_size=2, ckpt='yolox_l.pth', devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/example/custom/yolo...
              └ <yolox.core.trainer.Trainer object at 0x000001722CED7E50>

AttributeError: 'Namespace' object has no attribute 'cache'

**Comment by RUIXUEZHAOFENGNIAN** [comment]
hi, how to fix it?
