### ISSUE TITLE
谢谢！！！

### ISSUE THREAD

**Issue by violet2422** [Megvii-BaseDetection/YOLOX#699]

**Comment by violet2422** [comment]
2021-09-14 14:14:53 | INFO     | yolox.core.trainer:188 - ---> start train epoch1
2021-09-14 14:14:55 | INFO     | yolox.core.trainer:183 - Training of experiment is done and the best AP is 0.00
2021-09-14 14:14:55 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (819), thread 'MainThread' (140010865182528):
Traceback (most recent call last):

  File "/ws/Ww/YOLOX/tools/train.py", line 125, in <module>
    launch(
    └ <function launch at 0x7f550c552a60>

> File "/ws/Ww/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f54fabb1670>

  File "/ws/Ww/YOLOX/tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f55021ec8b0>
    └ <yolox.core.trainer.Trainer object at 0x7f54fabbb2b0>

  File "/ws/Ww/YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f54faec0f70>
    └ <yolox.core.trainer.Trainer object at 0x7f54fabbb2b0>

  File "/ws/Ww/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7f54fabf95e0>
    └ <yolox.core.trainer.Trainer object at 0x7f54fabbb2b0>

  File "/ws/Ww/YOLOX/yolox/core/trainer.py", line 87, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7f54fabf9670>
    └ <yolox.core.trainer.Trainer object at 0x7f54fabbb2b0>

  File "/ws/Ww/YOLOX/yolox/core/trainer.py", line 93, in train_one_iter
    inps, targets = self.prefetcher.next()
                    │    │          └ <function DataPrefetcher.next at 0x7f55021ec040>
                    │    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f54f012a1f0>
                    └ <yolox.core.trainer.Trainer object at 0x7f54fabbb2b0>

  File "/ws/Ww/YOLOX/yolox/data/data_prefetcher.py", line 43, in next
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7f55021e6f70>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f54f012a1f0>

  File "/ws/Ww/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │    │           │    │                        │    └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x7f54f012a880>
    │    │           │    │                        └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f54f012a1f0>
    │    │           │    └ tensor([[[  1.0000, 174.8198,  31.9148,  63.6099,  63.8297],
    │    │           │               [  1.0000, 152.9091, 184.9186,  38.8529,  69.3401],
    │    │           │         ...
    │    │           └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f54f012a1f0>
    │    └ tensor([[[[ 38.,  94., 127.,  ...,  52.,  74.,  74.],
    │                [ 10.,  33.,  65.,  ...,  45.,  74.,  74.],
    │                [  4., ...
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7f54f012a1f0>

  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
           │    └ <function _SingleProcessDataLoaderIter._next_data at 0x7f56bed0c3a0>
           └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x7f54f012a880>
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           │    │                │     └ [(True, tensor(155)), (True, tensor(26))]
           │    │                └ <function _MapDatasetFetcher.fetch at 0x7f56bed07820>
           │    └ <torch.utils.data._utils.fetch._MapDatasetFetcher object at 0x7f54f012a280>
           └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x7f54f012a880>
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
           │    │          └ [(array([[[  0.,   0.,   0., ...,   0.,   0.,   0.],
           │    │                    [  0.,   0.,   0., ...,   0.,   0.,   0.],
           │    │                    [  0.,   0., ...
           │    └ <function default_collate at 0x7f56bed073a0>
           └ <torch.utils.data._utils.fetch._MapDatasetFetcher object at 0x7f54f012a280>
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
            │                                       └ <zip object at 0x7f5428bddc00>
            └ <function default_collate at 0x7f56bed073a0>
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
            │               │            └ (tensor(155), 71)
            │               └ (tensor(155), 71)
            └ <function default_collate at 0x7f56bed073a0>
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
           │     │     │             └ None
           │     │     └ (tensor(155), 71)
           │     └ <built-in method stack of type object at 0x7f56c11b3ca0>
           └ <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'>

TypeError: expected Tensor as element 1 in argument 0, but got int

**Comment by violet2422** [comment]
问题已经解决！！！
