### ISSUE TITLE
Demo.py error (Expected 88 from C header, got 80 from PyObject)

### ISSUE THREAD

**Issue by Isaac45** [Megvii-BaseDetection/YOLOX#706]
Traceback (most recent call last):
  File "C:/Users/Ike/PycharmProjects/YOLOXX/tools/demo.py", line 14, in <module>
    from yolox.data.data_augment import ValTransform
  File "C:\Users\Ike\PycharmProjects\YOLOXX\yolox\data\__init__.py", line 8, in <module>
    from .datasets import *
  File "C:\Users\Ike\PycharmProjects\YOLOXX\yolox\data\datasets\__init__.py", line 5, in <module>
    from .coco import COCODataset
  File "C:\Users\Ike\PycharmProjects\YOLOXX\yolox\data\datasets\coco.py", line 10, in <module>
    from pycocotools.coco import COCO
  File "C:\Users\Ike\anaconda3\envs\pytorchGPU\lib\site-packages\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "C:\Users\Ike\anaconda3\envs\pytorchGPU\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

Process finished with exit code 1

**Any lead on this issue?**

**Comment by ArkarPhyo1310** [comment]
Update numpy. 
`pip install -U numpy`

**Comment by Isaac45** [comment]
> 
> 
> Update numpy.
> `pip install -U numpy`

@ArkarPhyo1310 thanks, I initially tried that, and resulted in a funny error "ModuleNotFoundError"
![image](https://user-images.githubusercontent.com/22303833/133608141-025d2cae-0e9f-4e24-a0b1-09e36787f62f.png)

**Comment by Joker316701882** [comment]
@Isaac45 Try to reinstall YOLOX under the current environment.
