### ISSUE TITLE
ImportError: cannot import name '_C' from 'yolox' (/root/Desktop/YOLOX-main/yolox/__init__.py)

### ISSUE THREAD

**Issue by oliverwxg** [Megvii-BaseDetection/YOLOX#71]
I'm try to run 'python tools/train.py -n yolox-x  -b 4  ',and the following error occurs.
Traceback (most recent call last):

  File "/root/Desktop/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 206, in evaluate_prediction
    from yolox.layers import COCOeval_opt as COCOeval

  File "/root/Desktop/YOLOX-main/yolox/layers/__init__.py", line 5, in <module>
    from .fast_coco_eval_api import COCOeval_opt

  File "/root/Desktop/YOLOX-main/yolox/layers/fast_coco_eval_api.py", line 16, in <module>
    from yolox import _C

ImportError: cannot import name '_C' from 'yolox' (/root/Desktop/YOLOX-main/yolox/__init__.py)

**installing the project is ok!  as follow:**

  Running setup.py develop for yolox
    Running command /home/user/anaconda3/envs/open-mmlab3/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/Desktop/YOLOX-main/setup.py'"'"'; __file__='"'"'/root/Desktop/YOLOX-main/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing yolox.egg-info/PKG-INFO
    writing dependency_links to yolox.egg-info/dependency_links.txt
    writing top-level names to yolox.egg-info/top_level.txt
    reading manifest file 'yolox.egg-info/SOURCES.txt'
    writing manifest file 'yolox.egg-info/SOURCES.txt'
    running build_ext
    building 'yolox._C' extension
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc
    creating /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/cocoeval
    Emitting ninja build file /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] c++ -MMD -MF /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/cocoeval/cocoeval.o.d -pthread -B /home/user/anaconda3/envs/open-mmlab3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/Desktop/YOLOX-main/yolox/layers/csrc -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/TH -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/THC -I/home/user/anaconda3/envs/open-mmlab3/include/python3.7m -c -c /root/Desktop/YOLOX-main/yolox/layers/csrc/cocoeval/cocoeval.cpp -o /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/cocoeval/cocoeval.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    [2/2] c++ -MMD -MF /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/vision.o.d -pthread -B /home/user/anaconda3/envs/open-mmlab3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/Desktop/YOLOX-main/yolox/layers/csrc -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/TH -I/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/include/THC -I/home/user/anaconda3/envs/open-mmlab3/include/python3.7m -c -c /root/Desktop/YOLOX-main/yolox/layers/csrc/vision.cpp -o /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/vision.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/yolox
    g++ -pthread -shared -B /home/user/anaconda3/envs/open-mmlab3/compiler_compat -L/home/user/anaconda3/envs/open-mmlab3/lib -Wl,-rpath=/home/user/anaconda3/envs/open-mmlab3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/vision.o /root/Desktop/YOLOX-main/build/temp.linux-x86_64-3.7/root/Desktop/YOLOX-main/yolox/layers/csrc/cocoeval/cocoeval.o -L/home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/yolox/_C.cpython-37m-x86_64-linux-gnu.so
    copying build/lib.linux-x86_64-3.7/yolox/_C.cpython-37m-x86_64-linux-gnu.so -> yolox
    Creating /home/user/anaconda3/envs/open-mmlab3/lib/python3.7/site-packages/yolox.egg-link (link to .)
    Adding yolox 0.1.0 to easy-install.pth file

    Installed /root/Desktop/YOLOX-main
Successfully installed yolox-0.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removed build tracker: '/tmp/pip-req-tracker-ce7h20p1'

**Comment by oliverwxg** [comment]
i reinstall the project. fixed the problem

**Comment by niqbal996** [comment]
For anyone else running into the same problem, I did the naive mistake of building the yolox module with a different python3.7 version and using it inside a different conda environment with python3.8. I also reinstalled with my new conda python3.8 environment as suggested by @oliverwxg and it generated a _**_C.cpython-38-x86_64-linux-gnu.so**_ for the python3.8 version which fixed the error.
