### ISSUE TITLE
Calculating the Cost only Based on obj_preds_

### ISSUE THREAD

**Issue by barisbatuhan** [Megvii-BaseDetection/YOLOX#731]
In the original implementation, the cost is calculated by:

```python
cls_preds_ = (
    cls_preds_.float().unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
    * obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
)
pair_wise_cls_loss = F.binary_cross_entropy(
    cls_preds_.sqrt_(), gt_cls_per_image, reduction="none"
 ).sum(-1)
```
However, I train the model with only one class to detect and try to completely remove the **cls_pred** path in the YOLOX Head. In this piece of code, I plan to use only `obj_preds_` to calculate `pair_wise_cls_loss`. In order to do this, if I change the above piece of code to this format:

```python
cls_preds_ = (
    obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
)
pair_wise_cls_loss = F.binary_cross_entropy(
    cls_preds_, gt_cls_per_image, reduction="none"
 ).sum(-1)
```
or to this format in a more direct way:

```python
pair_wise_cls_loss = F.binary_cross_entropy(
    obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_(), 
    gt_cls_per_image, reduction="none"
 ).sum(-1)
```

first, the **OOM RuntimeError is raised due to huge memory cost and then cpu mode is enabled** (with the original version, I had no such an error), and then I get these errors below:

- Found dtype Float but expected Half
- "sigmoid_cpu" not implemented for 'Half'

The thing I don't understand is that, why do we need `cls_preds_` to process the lines above? If I change the code to this format:

```python
cls_preds_ = (
    torch.ones_like(cls_preds_.float().unsqueeze(0).repeat(num_gt, 1, 1))
    * obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
)
pair_wise_cls_loss = F.binary_cross_entropy(
    cls_preds_, gt_cls_per_image, reduction="none"
 ).sum(-1)
```

this piece of code still works. But still, I plan to remove the `cls_preds_` completely. The complete error is given below:

```cmd
2021-09-23 10:28:16 | INFO     | yolox.core.trainer:239 - ---> start train epoch1
------------CPU Mode for This Batch-------------
2021-09-23 10:28:19 | ERROR    | yolox.models.yolo_head:318 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
2021-09-23 10:28:19 | INFO     | yolox.core.trainer:234 - Training of experiment is done and the best Face AP: 0 and the best Body AP: 0
2021-09-23 10:28:19 | ERROR    | yolox.core.launch:147 - An error has been caught in function '_distributed_worker', process 'SpawnProcess-1' (90384), thread 'MainThread' (140600914200384):
Traceback (most recent call last):

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolo_head.py", line 301, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7fdf90b1faf0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(320, 320, kernel_size=...

  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(320, 320, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7fdf90b1fa60>

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolo_head.py", line 492, in get_assignments
    pair_wise_cls_loss = F.binary_cross_entropy(
                         │ └ <function binary_cross_entropy at 0x7fe02b871670>
                         └ <module 'torch.nn.functional' from '/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/function...

  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/functional.py", line 2893, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
           │     │  │   │                    │      │       │       └ 0
           │     │  │   │                    │      │       └ None
           │     │  │   │                    │      └ tensor([[[1.],
           │     │  │   │                    │                 [1.],
           │     │  │   │                    │                 [1.],
           │     │  │   │                    │                 ...,
           │     │  │   │                    │                 [1.],
           │     │  │   │                    │                 [1.],
           │     │  │   │                    │                 [1.]],
           │     │  │   │                    │
           │     │  │   │                    │                [[1.],
           │     │  │   │                    │            ...
           │     │  │   │                    └ tensor([[[0.0096],
           │     │  │   │                               [0.0099],
           │     │  │   │                               [0.0100],
           │     │  │   │                               ...,
           │     │  │   │                               [0.0098],
           │     │  │   │                               [0.0108],
           │     │  │   │                               [0.0097...
           │     │  │   └ <built-in function binary_cross_entropy>
           │     │  └ <module 'torch._C._nn'>
           │     └ <module 'torch._C' from '/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/_C.cpython-39-x86_64-l...
           └ <module 'torch' from '/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/__init__.py'>

RuntimeError: Found dtype Float but expected Half


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 9
               └ <function _main at 0x7fe02c32aa60>
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7fe02c3e1670>
           └ <SpawnProcess name='SpawnProcess-1' parent=58942 started>
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fe02c3d7ca0>
    └ <SpawnProcess name='SpawnProcess-1' parent=58942 started>
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=58942 started>
    │    │        │    └ (<function _distributed_worker at 0x7fdfa1eeb790>, 0, (<function main at 0x7fdf916220d0>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:3...
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=58942 started>
    │    └ <function _wrap at 0x7fdfa58e6430>
    └ <SpawnProcess name='SpawnProcess-1' parent=58942 started>
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
    │  │   └ (<function main at 0x7fdf916220d0>, 2, 2, 0, 'nccl', 'tcp://127.0.0.1:35384', (╒══════════════════╤══════════════════════════...
    │  └ 0
    └ <function _distributed_worker at 0x7fdfa1eeb790>

> File "/scratch/users/baristopal20/modules_yolox/yolox/core/launch.py", line 147, in _distributed_worker
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fdf916220d0>

  File "/scratch/users/baristopal20/modules_yolox/tools/train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fdf98042ee0>
    └ <yolox.core.trainer.Trainer object at 0x7fdf915bd6a0>

  File "/scratch/users/baristopal20/modules_yolox/yolox/core/trainer.py", line 75, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fdf91657c10>
    └ <yolox.core.trainer.Trainer object at 0x7fdf915bd6a0>

  File "/scratch/users/baristopal20/modules_yolox/yolox/core/trainer.py", line 84, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7fdf915e53a0>
    └ <yolox.core.trainer.Trainer object at 0x7fdf915bd6a0>

  File "/scratch/users/baristopal20/modules_yolox/yolox/core/trainer.py", line 90, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7fdf915e5af0>
    └ <yolox.core.trainer.Trainer object at 0x7fdf915bd6a0>

  File "/scratch/users/baristopal20/modules_yolox/yolox/core/trainer.py", line 105, in train_one_iter
    foutputs = self.model(inps, targets, mode=1)
               │    │     │     └ tensor([[[  0.0000,  54.8438, 372.5000,  38.6875,  31.5781],
               │    │     │                [  0.0000, 572.5000, 513.5000, 134.7500, 225.0000],
               │    │     │          ...
               │    │     └ tensor([[[[116., 116., 116.,  ..., 116., 116., 116.],
               │    │                 [116., 116., 116.,  ..., 116., 116., 116.],
               │    │                 [116., ...
               │    └ DistributedDataParallel(
               │        (module): YOLOX(
               │          (backbone): YOLOPAFPN(
               │            (backbone): CSPDarknet(
               │              (stem): Focus(
               │       ...
               └ <yolox.core.trainer.Trainer object at 0x7fdf915bd6a0>

  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {'mode': 1}
           │             └ (tensor([[[[116., 116., 116.,  ..., 116., 116., 116.],
           │                         [116., 116., 116.,  ..., 116., 116., 116.],
           │                         [116.,...
           └ <bound method DistributedDataParallel.forward of DistributedDataParallel(
               (module): YOLOX(
                 (backbone): YOLOPAFPN(
                  ...
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
             │            │            └ ({'mode': 1},)
             │            └ ((tensor([[[[116., 116., 116.,  ..., 116., 116., 116.],
             │                        [116., 116., 116.,  ..., 116., 116., 116.],
             │                        [116....
             └ DistributedDataParallel(
                 (module): YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                ...
  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {'mode': 1}
           │             └ (tensor([[[[116., 116., 116.,  ..., 116., 116., 116.],
           │                         [116., 116., 116.,  ..., 116., 116., 116.],
           │                         [116.,...
           └ <bound method YOLOX.forward of YOLOX(
               (backbone): YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv...

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolox.py", line 60, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = head(
                                                           └ YOLOXHead(
                                                               (cls_convs): ModuleList(
                                                                 (0): Sequential(
                                                                   (0): BaseConv(
                                                                     (conv): Conv2d(320, 320, kernel_size=...

  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {'labels': tensor([[[  0.0000,  54.8438, 372.5000,  38.6875,  31.5781],
           │             │                   [  0.0000, 572.5000, 513.5000, 134.7500, 225...
           │             └ ([tensor([[[[-9.5642e-02, -9.6313e-02, -8.2092e-02,  ..., -7.6416e-02,
           │                          -6.4941e-02, -6.2042e-02],
           │                         [-1.16...
           └ <bound method YOLOXHead.forward of YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (c...

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolo_head.py", line 183, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x7fdf90b1f940>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(320, 320, kernel_size=...

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolo_head.py", line 330, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x7fdf90b1faf0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(320, 320, kernel_size=...

  File "/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(320, 320, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x7fdf90b1fa60>

  File "/scratch/users/baristopal20/modules_yolox/yolox/models/yolo_head.py", line 493, in get_assignments
    torch.sigmoid(obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1)),
    │     │       │          │                   └ 2
    │     │       │          └ <method 'unsqueeze' of 'torch._C._TensorBase' objects>
    │     │       └ tensor([[-4.6406],
    │     │                 [-4.6055],
    │     │                 [-4.5938],
    │     │                 [-4.5859],
    │     │                 [-4.5781],
    │     │                 [-4.6055],
    │     │                 [-4...
    │     └ <built-in method sigmoid of type object at 0x7fe010678ea0>
    └ <module 'torch' from '/kuacc/users/baristopal20/.conda/envs/yolox/lib/python3.9/site-packages/torch/__init__.py'>

RuntimeError: "sigmoid_cpu" not implemented for 'Half'

```

**Comment by barisbatuhan** [comment]
Instead of using `F.binary_cross_entropy`, if `F.binary_cross_entropy_with_logits` is preferred, then the problem is solved I guess. 

```python
pair_wise_cls_loss = F.binary_cross_entropy_with_logits(
    obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1), 
    gt_cls_per_image, reduction="none"
 ).sum(-1)
```

With the code piece above, the model works but still, I do not get the difference of taking sigmoid first and useing BCE or using BCE w/ logits without taking sigmoid. They are basically the same operation anyway. It would be nice if you approve that this will yield to the same result.
