### ISSUE TITLE
TRT version on jetson with jetpack 4.6

### ISSUE THREAD

**Issue by mosheliv** [Megvii-BaseDetection/YOLOX#756]
I am curating a list of object detectors for the jetson nano (see https://github.com/mosheliv/jetson-nano-object-detection-benchmark) and wanted to include yolox.

I have encountered a few problems with the trt process as without the trt is is very slow (720ms for tsize 320).
first of all, i get the following when converting using trt.py:
```
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_unary
Warning: Encountered known unsupported method torch.nn.functional.silu
```
probably some layer library is missing?

when running the detection i get after the warmup rounds :
```
Traceback (most recent call last):
  File "tools/demo.py", line 316, in <module>
    main(exp, args)
  File "tools/demo.py", line 307, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 198, in image_demo
    result_image = predictor.visual(outputs[0], img_info, predictor.confthre)
  File "tools/demo.py", line 183, in visual
    vis_res = vis(img, bboxes, scores, cls, cls_conf, self.cls_names)
  File "/home/m/tests/YOLOX/yolox/utils/visualize.py", line 20, in vis
    y0 = int(box[1])
OverflowError: cannot convert float infinity to integer
```
it might be an outcome of the first problem, i don't know

lastly, there is no minimal example of using yolox in python, just calling the scripts. can it be done?

Thank you

**Comment by tensorturtle** [comment]
Hi, I have been able to run YOLOX nano model on Jetson Nano 4GB with TensorRT with no problems.
Just guessing, but do you have the latest PyTorch installed on your Jetson Nano? I think SiLU might be a relatively new addition to PyTorch.
See https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048 for Jetson Nano PyTorch installation instructions.

**Comment by tensorturtle** [comment]
You might also want to see https://github.com/Megvii-BaseDetection/YOLOX/issues/627 to fix a common issue when running `trt.py` on Jetson Nano

**Comment by mosheliv** [comment]
I did reduce the workspace, otherwise it won't get to this stage.
I do use the newest pytorch with the appropriate torchvision (I think).
python 3.6.9
pytorch 1.9.0
torchvision 0.11.0a0+972ca65
tensorrt 8.0.1.6

If you can please check the versions on your jetson? it's probably
something stupid

**Comment by tensorturtle** [comment]
Jetpack 32.5.2
CUDA 10.2.89
OpenCV 4.5.0
TensorRT 7.1.3.0
cuDNN 8.0.0.180
Python 3.6.9
PyTorch 1.8.0
TorchVision 0.9.0

**Comment by mosheliv** [comment]
Ahhh so its probably something introduced with the newer version.

**Comment by mosheliv** [comment]
Btw, the issue still stands. With jetpack 4.6 yolox trt fails

**Comment by RGring** [comment]
@tensorturtle  Since you have successfully deployed on the Nano, I was wondering how you succeeded the conversion. I have even a Xavier NX and I run out of memory when I want to convert the model to tensorrt. Or did you convert on a different machine? I would appreciate your help on that!

**Comment by RGring** [comment]
Update: Setting the max workspace size (--workspace) solved my issue. And I am able to run YOLOX also with Jetpack 4.4.

**Comment by tulbureandreit** [comment]
@RGring could you please provide more details? I really struggle to run YOLOX on an nvidia xavier AGX

**Comment by tensorturtle** [comment]
@tulbureandreit the workspace size fix that @RGring is about using `YOLOX/tools/trt.py` to convert models to TensorRT for faster inference on Jetson platform. Lowering the value to 29 fixed it for me. See:
https://github.com/Megvii-BaseDetection/YOLOX/issues/627#issuecomment-914474035
If that's not the issue you're having, it would help if you described what specific error message at what stage you are seeing.
