### ISSUE TITLE
Traininig errors with 2 GPUs

### ISSUE THREAD

**Issue by Leesoon1984** [Megvii-BaseDetection/YOLOX#76]
Traceback (most recent call last):
  File "tools/train.py", line 113, in <module>
    launch(
  File "/home/leesoon/Projects/Detection/YOLO/YOLOX/yolox/core/launch.py", line 58, in launch
    mp.spawn(
  File "/home/leesoon/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/leesoon/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/leesoon/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leesoon/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/leesoon/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by FateScript** [comment]
This is caused because your memory is not enough, you could modify num_workers [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L27) to samller number and try again.

**Comment by Leesoon1984** [comment]
> This exception is raised because your memory is not enough, you could modify num_workers [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L27) to samller number and try again.

Thank you for your prompt response. The problem has been solved.
