### ISSUE TITLE
raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file)) ImportError: exps/default/nano.py doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by zhuzhuzhu111222** [Megvii-BaseDetection/YOLOX#784]
li@li-desktop:~/Desktop/YOLOX-main$ python3 tools/demo.py image -f exps/default/nano.py -c yolox_nano.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu

Traceback (most recent call last):
  File "/home/li/Desktop/YOLOX-main/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "exps/default/nano.py", line 36
    backbone = YOLOPAFPN(self.depth, self.width, in_channels=in_channels, self.act, depthwise=True)
                                                                         ^
SyntaxError: positional argument follows keyword argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/demo.py", line 312, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/li/Desktop/YOLOX-main/yolox/exp/build.py", line 51, in get_exp
    return get_exp_by_file(exp_file)
  File "/home/li/Desktop/YOLOX-main/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: exps/default/nano.py doesn't contains class named 'Exp'

![1](https://user-images.githubusercontent.com/87367234/136888996-c50d5574-2c18-47e7-98dd-e388c39712bb.png)

**Comment by zhuzhuzhu111222** [comment]
Thank you very much
it’s useful

**Comment by abushattal1** [comment]
> please pull our latest update, this bug is fixed now.

Hi,
I have updated the nano.py code but i still have the same problem.... any suggestion

**Comment by diaozhuo99** [comment]
改称绝对路径就好了
