### ISSUE TITLE
cannot import name 'UnencryptedCookieSessionFactoryConfig' 

### ISSUE THREAD

**Issue by xiaomujiang** [Megvii-BaseDetection/YOLOX#8]
s使用推理YOLOX-main python openvino_inference.py -m /project/train/yolox/YOLOX-main/yolox_nano/yolox_10.xml -i /home/1..jpg  出现问题如下
Traceback (most recent call last):
  File "openvino_inference.py", line 17, in <module>
    from yolox.data.data_augment import preproc as preprocess
  File "/project/train/yolox/YOLOX-main/yolox/__init__.py", line 4, in <module>
    from .utils import configure_module
  File "/project/train/yolox/YOLOX-main/yolox/utils/__init__.py", line 10, in <module>
    from .ema import ModelEMA
  File "/project/train/yolox/YOLOX-main/yolox/utils/ema.py", line 7, in <module>
    import apex
  File "/usr/local/lib/python3.6/dist-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'

**Comment by Joker316701882** [comment]
@xiaomujiang Hi, did u manage to work it out?

**Comment by xiaomujiang** [comment]
it is problem of apex versions.

**Comment by qq1243196045** [comment]
请问apex版本是多少，我也报错了
