### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox.data.datasets'

### ISSUE THREAD

**Issue by ericdoug-qi** [Megvii-BaseDetection/YOLOX#815]
I am running with "Quick Start" in README.md, but get the Error information as below:

python tools/demo.py image -n yolox-s -c yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from yolox.data.data_augment import ValTransform
  File "/tmp/anaconda3/envs/image/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/data/__init__.py", line 8, in <module>
    from .datasets import *
ModuleNotFoundError: No module named 'yolox.data.datasets'

**Comment by naeunhub** [comment]
I faced same problem. How did you fix it?
