### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'legacy'

### ISSUE THREAD

**Issue by job2003** [Megvii-BaseDetection/YOLOX#878]
python tools\demo.py video -n yolox-x -c ..\weights\yolox\yolox_x.pth --path MOT16-03.mp4 --conf 0.25 --nms 0.4 --tsize 640 --save_result --device gpu
2021-11-05 22:50:29.807 | INFO     | __main__:main:255 - Args: Namespace(camid=0, ckpt='..\\weights\\yolox\\yolox_x.pth', conf=0.25, demo='video', device='gpu', exp_file=None, experiment_name='yolox_x', fp16=False, fuse=False, legacy=False, name='yolox-x', nms=0.4, path='MOT16-03.mp4', save_result=True, trt=False, tsize=640)
2021-11-05 22:50:30.537 | INFO     | __main__:main:265 - Model Summary: Params: 99.07M, Gflops: 281.93
2021-11-05 22:50:33.059 | INFO     | __main__:main:278 - loading checkpoint
2021-11-05 22:50:33.510 | INFO     | __main__:main:282 - loaded checkpoint done.
Traceback (most recent call last):
  File "tools\demo.py", line 316, in <module>
    main(exp, args)
  File "tools\demo.py", line 303, in main
    args.device, args.fp16, args.legacy,
  File "tools\demo.py", line 121, in __init__
    self.preproc = ValTransform(legacy=legacy)
TypeError: __init__() got an unexpected keyword argument 'legacy'

**Comment by pullover00** [comment]
Could you resolve it? I am having the same error

**Comment by FateScript** [comment]
Just add legacy keyword parser.

**Comment by Best-effort** [comment]
您好 请问您解决了吗，我也出现了相同的问题

**Comment by job2003** [comment]
目前运行没有这个问题了，但我忘记是怎么解决的了。不好意思。
















在 2022-04-25 12:55:02，"Best-effort" ***@***.***> 写道：

您好 请问您解决了吗，我也出现了相同的问题

**Comment by shuyu888** [comment]
same
