### ISSUE TITLE
error pip3 install -v -e .

### ISSUE THREAD

**Issue by job2003** [Megvii-BaseDetection/YOLOX#879]
windows 10, cuda 11.1

当运行pip3 install -v -e .时，报错：

(FairMOT) PS D:\workspaces\YOLO\YOLOX> pip install -v -e .
Using pip 21.3.1 from c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\pip (python 3.6)
Obtaining file:///D:/workspaces/YOLO/YOLOX
  Running command python setup.py egg_info
  running egg_info
  creating C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info
  writing C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\PKG-INFO
  writing dependency_links to C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\dependency_links.txt
  writing top-level names to C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\top_level.txt
  writing manifest file 'C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\SOURCES.txt'
  writing manifest file 'C:\Users\whu_c\AppData\Local\Temp\pip-pip-egg-info-clb7emvm\yolox.egg-info\SOURCES.txt'
  _**Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\initialise.py", line 20, in reset_all
      AnsiToWin32(orig_stdout).reset_all()
    File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\ansitowin32.py", line 71, in __init__
      strip = conversion_supported or (not is_stream_closed(wrapped) and not is_a_tty(wrapped))
    File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\ansitowin32.py", line 17, in is_stream_closed
      return not hasattr(stream, 'closed') or stream.closed
  ValueError: underlying buffer has been detached**_
  Preparing metadata (setup.py) ... done
Installing collected packages: yolox
  Attempting uninstall: yolox
    Found existing installation: yolox 0.1.0
    Uninstalling yolox-0.1.0:
      Removing file or directory c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\yolox.egg-link
      Removing pth entries from c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\easy-install.pth:
      Removing entry: d:\workspaces\yolo\yolox
      Successfully uninstalled yolox-0.1.0
  Running setup.py develop for yolox
    Running command 'c:\users\whu_c\anaconda3\envs\fairmot\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\workspaces\\YOLO\\YOLOX\\setup.py'"'"'; __file__='"'"'D:\\workspaces\\YOLO\\YOLOX\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing yolox.egg-info\PKG-INFO
    writing dependency_links to yolox.egg-info\dependency_links.txt
    writing top-level names to yolox.egg-info\top_level.txt
    reading manifest file 'yolox.egg-info\SOURCES.txt'
    writing manifest file 'yolox.egg-info\SOURCES.txt'
    running build_ext
    building 'yolox._C' extension
    Emitting ninja build file D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\build.ninja...
    Compiling objects...
    _**Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。**_
      warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
    ninja: no work to do.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\torch\lib /LIBPATH:c:\users\whu_c\anaconda3\envs\fairmot\libs /LIBPATH:c:\users\whu_c\anaconda3\envs\fairmot\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\workspaces\YOLO\YOLOX\yolox\layers\csrc\vision.obj D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\workspaces\YOLO\YOLOX\yolox\layers\csrc\cocoeval\cocoeval.obj /OUT:build\lib.win-amd64-3.6\yolox\_C.cp36-win_amd64.pyd /IMPLIB:D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\workspaces\YOLO\YOLOX\yolox\layers\csrc\_C.cp36-win_amd64.lib
      正在创建库 D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\workspaces\YOLO\YOLOX\yolox\layers\csrc\_C.cp36-win_amd64.lib 和对象 D:\workspaces\YOLO\YOLOX\build\temp.win-amd64-3.6\Release\workspaces\YOLO\YOLOX\yolox\layers\csrc\_C.cp36-win_amd64.exp
    正在生成代码
    已完成代码的生成
    copying build\lib.win-amd64-3.6\yolox\_C.cp36-win_amd64.pyd -> yolox
    Creating c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\yolox.egg-link (link to .)
    Adding yolox 0.1.0 to easy-install.pth file

    Installed d:\workspaces\yolo\yolox
    **_Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\initialise.py", line 20, in reset_all
        AnsiToWin32(orig_stdout).reset_all()
      File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\ansitowin32.py", line 71, in __init__
        strip = conversion_supported or (not is_stream_closed(wrapped) and not is_a_tty(wrapped))
      File "c:\users\whu_c\anaconda3\envs\fairmot\lib\site-packages\colorama\ansitowin32.py", line 17, in is_stream_closed
        return not hasattr(stream, 'closed') or stream.closed
    ValueError: underlying buffer has been detached_**
Successfully installed yolox-0.1.0

**Comment by FateScript** [comment]
what's your numpy version? try to upgrade your numpy?

**Comment by lllxq** [comment]
same question, have you solved?
