### ISSUE TITLE
ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by jie311** [Megvii-BaseDetection/YOLOX#88]
I meet thi error：
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from yolox.core import Trainer, launch
  File "/home/DATA/liaozhongke/git/YOLOX/yolox/__init__.py", line 6, in <module>
    configure_module()
  File "/home/DATA/liaozhongke/git/YOLOX/yolox/utils/setup_env.py", line 35, in configure_module
    resource.setrlimit(resource.RLIMIT_NOFILE, (ulimit_value, rlimit[1]))
ValueError: current limit exceeds maximum limit

**Comment by Joker316701882** [comment]
Please pull our latest main branch and try to run the code again.
