### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by qiuzhewei** [Megvii-BaseDetection/YOLOX#888]
你好，
在安装yolox的时候，到最后一步的时候：pip3 install -v -e . 出错
错误信息如下所示：
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/search/odin/qiuzhewei/project/qb_album/code/YOLOX/setup.py", line 54, in <module>
        setuptools.setup(
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1336, in _write_ninja_file_and_compile_objects
        check_compiler_abi_compatibility(compiler)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 283, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 243, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/search/odin/xujianhua/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', 'g++ -std=gnu++0x']' returned non-zero exit status 1.

**Comment by FateScript** [comment]
Did you install g++?

**Comment by ljy-002** [comment]
+1，我也出现同样的问题
