### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by 18789447455** [Megvii-BaseDetection/YOLOX#890]
zhaolimin@gpuv100:~/YOLOX$ python tools/demo.py image -n yolox-s -c /home/zhaolimin/YOLOX/path/to/your/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
2021-11-09 10:53:17.385 | INFO     | __main__:main:250 - Args: Namespace(camid=0, ckpt='/home/zhaolimin/YOLOX/path/to/your/yolox_s.pth', conf=0.25, demo='image', device='gpu', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name='yolox-s', nms=0.45, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)
/home/zhaolimin/anaconda3/envs/YOLOX/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-11-09 10:53:21.485 | INFO     | __main__:main:260 - Model Summary: Params: 8.97M, Gflops: 26.87
2021-11-09 10:53:27.553 | INFO     | __main__:main:271 - loading checkpoint
2021-11-09 10:53:27.728 | INFO     | __main__:main:275 - loaded checkpoint done.
2021-11-09 10:53:27.787 | INFO     | __main__:inference:160 - Infer time: 0.0422s
Traceback (most recent call last):
  File "tools/demo.py", line 306, in <module>
    main(exp, args)
  File "tools/demo.py", line 297, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 190, in image_demo
    result_image = predictor.visual(outputs[0], img_info, predictor.confthre)
  File "tools/demo.py", line 178, in visual
    vis_res = vis(img, bboxes, scores, cls, cls_conf, self.cls_names)
  File "/home/zhaolimin/YOLOX/yolox/utils/visualize.py", line 25, in vis
    text = '{}:{:.1f}%'.format(class_names[cls_id], score * 100)
IndexError: tuple index out of range

**Comment by fellowbak** [comment]
I have the same problem

**Comment by 18789447455** [comment]
> I have the same problem

改了类别数和类别名

**Comment by fellowbak** [comment]
Yes, that was my problem too. I came here to suggest this solution as well. To future readers: In my case this happened because the categories specified in YOLOX\yolox\data\datasets coco_classes.py did not match the categories that the model was trained on.

**Comment by Avnsx** [comment]
> Yes, that was my problem too. I came here to suggest this solution as well. To future readers: In my case this happened because the categories specified in YOLOX\yolox\data\datasets coco_classes.py did not match the categories that the model was trained on.

Do you have any clue how to remove the classes directly from the model itsself in first place then? So that we could afterwards remove them from the ``coco_classes.py`` file, without getting any errors?
