### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by 18789447455** [Megvii-BaseDetection/YOLOX#900]
请问这个问题怎么解决

**Comment by FateScript** [comment]
Did you modify any code?

**Comment by tan90du-sx** [comment]
2022-07-11 10:18:46 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainPr                                             ocess' (1259733), thread 'MainThread' (140300944110400):
Traceback (most recent call last):

  File "tools/train.py", line 144, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, cache=False, ckpt='yolox_s.pth', devices=1, dist_backend='nccl', dist_url=Non                                             e, exp_file='exps/exampl...
          └ ╒═══════════════════╤═════════════════════════════════════════════════════════════════════════════════════                                             ═══════════════════...

> File "/home/sunxue/anaconda3/envs/py36-new/lib/python3.6/site-packages/yolox-0.3.0-py3.6-linux-x86_64.egg/yolox/core                                             /launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════                                             ════════════════════════...
    └ <function main at 0x7f995fccec80>

  File "tools/train.py", line 121, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f995d7a9b70>
    └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>

  File "/home/sunxue/anaconda3/envs/py36-new/lib/python3.6/site-packages/yolox-0.3.0-py3.6-linux-x86_64.egg/yolox/core                                             /trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f995d704400>
    └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>
  File "/home/sunxue/anaconda3/envs/py36-new/lib/python3.6/site-packages/yolox-0.3.0-py3.6-linux-x86_64.egg/yolox/core                                             /trainer.py", line 86, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f995d704730>
    └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>
  File "/home/sunxue/anaconda3/envs/py36-new/lib/python3.6/site-packages/yolox-0.3.0-py3.6-linux-x86_64.egg/yolox/core                                             /trainer.py", line 222, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f995d7049d8>
    └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>
  File "/home/sunxue/anaconda3/envs/py36-new/lib/python3.6/site-packages/yolox-0.3.0-py3.6-linux-x86_64.egg/yolox/core                                             /trainer.py", line 329, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>
    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f9955cc3588>
    │          └ <yolox.core.trainer.Trainer object at 0x7f995d7ab908>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

ValueError: too many values to unpack (expected 2)

我遇到了同样的问题，请问有人知道为什么以及如何解决吗？

**Comment by FateScript** [comment]
It's a bug and fixed in #1416 , Plz pull our latest branch to fix this issue.

**Comment by seenthestars** [comment]
ValueError: too many values to unpack (expected 2)
