### ISSUE TITLE
Caught KeyError in DataLoader worker process 0

### ISSUE THREAD

**Issue by yichen200** [Megvii-BaseDetection/YOLOX#929]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/opt/conda/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/data/datasets/mosaicdetection.py", line 91, in __getitem__
    img, _labels, _, _ = self._dataset.pull_item(index)
  File "/opt/conda/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/data/datasets/voc.py", line 154, in pull_item
    target = self.load_anno(index)
  File "/opt/conda/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/data/datasets/voc.py", line 128, in load_anno
    target = self.target_transform(target)
  File "/opt/conda/lib/python3.8/site-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/data/datasets/voc.py", line 65, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'crack'

**Comment by shivanshdarshan** [comment]
try printing class_to_ind in the function __call__ 
probably dictionary is not {"crack":0} (assuming you have single label)
but  {'c':0,'r':1,'a':2,'c':3,'k':4}
maybe you have to check VOC_CLASSES variable for single class the tuple should contain  ' ,  0 'else it will break class name  into characters

**Comment by TekayaNidham** [comment]
In case anyone else ran into this issue ; 
For my case i'm working with upper cased annotations and i was using an old fork of this repo, so i deleted the lower() in the call function but it has been solved in this @[hhngdcz](https://github.com/Megvii-BaseDetection/YOLOX/commits?author=hhngdcz)'s [commit](https://github.com/Megvii-BaseDetection/YOLOX/commit/73ea2068fb70e38fe977b55dc5c5515f6732bd83)

**Comment by SimonCaignart** [comment]
> try printing class_to_ind in the function **call** probably dictionary is not {"crack":0} (assuming you have single label) but {'c':0,'r':1,'a':2,'c':3,'k':4} maybe you have to check VOC_CLASSES variable for single class the tuple should contain ' , 0 'else it will break class name into characters

I have this problem about the classname being breaking into characters, but I do not understand the ' , 0 ' explanation, can you give some more details ?
