### ISSUE TITLE
pls help!!! EOFError: Ran out of input

### ISSUE THREAD

**Issue by PhoenyHan** [Megvii-BaseDetection/YOLOX#93]
python /root/share/YOLOX/tools/demo.py image -f /root/share/YOLOX/exps/default/yolox_x.py -c /root/share/YOLOX/yolox_x.pth.tar --path /root/share/YOLOX/assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result

2021-07-23 02:08:45.124 | INFO     | __main__:main:220 - Args: Namespace(camid=0, ckpt='/root/share/YOLOX/yolox_x.pth.tar', conf=0.3, demo='image', device='cpu', exp_file='/root/share/YOLOX/exps/default/yolox_x.py', experiment_name='yolox_x', fp16=False, fuse=False, name=None, nms=0.65, path='/root/share/YOLOX/assets/dog.jpg', save_result=True, trt=False, tsize=640)
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-07-23 02:08:45.986 | INFO     | __main__:main:230 - Model Summary: Params: 99.07M, Gflops: 281.93
2021-07-23 02:08:45.987 | INFO     | __main__:main:241 - loading checkpoint
Traceback (most recent call last):
  File "/root/share/YOLOX/tools/demo.py", line 277, in <module>
    main(exp, args)
  File "/root/share/YOLOX/tools/demo.py", line 242, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

I got this error when running the demo, anyone can help? Thx!!!

**Comment by PhoenyHan** [comment]
solved

**Comment by xinsuinizhuan** [comment]
> 
> 
> solved

怎么解决的呢？我也遇到了

**Comment by Wanter-Z** [comment]
I got this error too when I set "--cache" mode, just like:

OverflowError: cannot serialize a bytes object larger than 4 GiB
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\AI_package\anaconda\envs\mmdetection\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\AI_package\anaconda\envs\mmdetection\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

I tried to change the parameter self.data_num_workers = 0 and reduced the batchsize, but both didn't make sense. Anyone can help？ Thx.

**Comment by Wanter-Z** [comment]
> solved

Could you tell me how to solve it， I got the same error.

**Comment by PhoenyHan** [comment]
@Wanter-Z   sorry, i don't remember...
