### ISSUE TITLE
An error has been caught in function 'launch', process 'MainProcess' (1793), thread 'MainThread' (139874455205696)

### ISSUE THREAD

**Issue by smartparty** [Megvii-BaseDetection/YOLOX#968]
2021-12-06 12:28:05 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (1856), thread 'MainThread' (139822869251904):
Traceback (most recent call last):

  File "tools/train.py", line 125, in <module>
    launch(
    └ <function launch at 0x7f2a92847700>

> File "/usr/local/lib/python3.8/dist-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════╕
    │            │ keys             │ values                     │
    │            ╞══════════════════╪════...
    └ <function main at 0x7f2a906f85e0>

  File "tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f2aa02f90d0>
    └ <yolox.core.trainer.Trainer object at 0x7f2a90676520>

  File "/usr/local/lib/python3.8/dist-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/core/trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7f2a906f2f70>
    └ <yolox.core.trainer.Trainer object at 0x7f2a90676520>

  File "/usr/local/lib/python3.8/dist-packages/yolox-0.1.0-py3.8-linux-x86_64.egg/yolox/core/trainer.py", line 130, in before_train
    torch.cuda.set_device(self.local_rank)
    │     │    │          │    └ 0
    │     │    │          └ <yolox.core.trainer.Trainer object at 0x7f2a90676520>
    │     │    └ <function set_device at 0x7f2aac8495e0>
    │     └ <module 'torch.cuda' from '/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py'>
    └ <module 'torch' from '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 311, in set_device
    torch._C._cuda_setDevice(device)
    │     │  │               └ 0
    │     │  └ <built-in function _cuda_setDevice>
    │     └ <module 'torch._C' from '/usr/local/lib/python3.8/dist-packages/torch/_C.cpython-38-x86_64-linux-gnu.so'>
    └ <module 'torch' from '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
    │     │  └ <built-in function _cuda_init>
    │     └ <module 'torch._C' from '/usr/local/lib/python3.8/dist-packages/torch/_C.cpython-38-x86_64-linux-gnu.so'>
    └ <module 'torch' from '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'>

**Comment by mbl1234** [comment]
请问解决了吗
