### ISSUE TITLE
转onnx模型失败：EOFError: Ran out of input

### ISSUE THREAD

**Issue by xinsuinizhuan** [Megvii-BaseDetection/YOLOX#981]
(yolox) E:\Item\Item_done\yoloX\YOLOX-main>python tools/export_onnx.py --output-name yolox_s.onnx -f exps/default/yolox_s.py -c yolox_s.pth
2021-12-09 20:48:18.658 | INFO     | __main__:main:59 - args value: Namespace(batch_size=1, ckpt='yolox_s.pth', dynamic=False, exp_file='exps/default/yolox_s.py', experiment_name=None, input='images', name=None, no_onnxsim=False, opset=11, opts=[], output='output', output_name='yolox_s.onnx')
2021-12-09 20:48:18.714 | ERROR    | __main__:<module>:116 - An error has been caught in function '<module>', process 'MainProcess' (2092), thread 'MainThread' (20008):
Traceback (most recent call last):

> File "tools\export_onnx.py", line 116, in <module>
    main()
    └ <function main at 0x000001A410967678>

  File "tools\export_onnx.py", line 74, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
           │     │    └ 'yolox_s.pth'
           │     └ <function load at 0x000001A4702CDF78>
           └ <module 'torch' from 'C:\\ProgramData\\Anaconda3\\envs\\yolox\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\ProgramData\Anaconda3\envs\yolox\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           │            │            │             │                └ {'encoding': 'utf-8'}
           │            │            │             └ <module 'pickle' from 'C:\\ProgramData\\Anaconda3\\envs\\yolox\\lib\\pickle.py'>
           │            │            └ 'cpu'
           │            └ <_io.BufferedReader name='yolox_s.pth'>
           └ <function _legacy_load at 0x000001A4702D1168>

  File "C:\ProgramData\Anaconda3\envs\yolox\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   │             │    │    └ {'encoding': 'utf-8'}
                   │             │    └ <_io.BufferedReader name='yolox_s.pth'>
                   │             └ <built-in function load>
                   └ <module 'pickle' from 'C:\\ProgramData\\Anaconda3\\envs\\yolox\\lib\\pickle.py'>

EOFError: Ran out of input

**Comment by FateScript** [comment]
[This](https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file) might help you. Search engine is your friend. Plz learn to use it.
