### ISSUE TITLE
ImportError: /home/xyx/code/YOLOX-main/yolox/exp/yolox_base.py doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by Xiang99** [Megvii-BaseDetection/YOLOX#99]
Traceback (most recent call last):
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/home/td/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyx/code/YOLOX-main/tools/train.py", line 116, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 48, in get_exp
    return get_exp_by_file(exp_file)
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: yolox/exp/yolox_base.py doesn't contains class named 'Exp'

Process finished with exit code 1

**Comment by JasenWangLab** [comment]
https://github.com/Megvii-BaseDetection/YOLOX/pull/42/commits/8180c60664a0388af2e72577f8d67451c65309dd  你或许可以参考下这个
